package org.apache.jsp.pages.company;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>公司管理</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\"/>    \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/style.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/form.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/jquery-ui-1.8.15.custom.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeStyle.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeIcons.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/gt_grid.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/default/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/green/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/mac/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/china/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/vista/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/calendar/calendar-blue.css\"  />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/public.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.layout.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-ui-1.8.5.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/tree/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/lib/jquery.metadata.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-en.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-setup.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_grid_all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_msg_cn.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"pages/treedrag.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t//tab页\r\n");
      out.write("\tloadTab();\r\n");
      out.write("\t\r\n");
      out.write("\t//加载布局\r\n");
      out.write("\t$('#myContent').layout({\r\n");
      out.write("        west: {size:\"300\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("  \t//加载树\r\n");
      out.write("    buildCompanyTree();\r\n");
      out.write("  \t\r\n");
      out.write("  \t//加载职务\r\n");
      out.write("\tloadMyJobGrid();\r\n");
      out.write("  \t\r\n");
      out.write("\t//加载职级\r\n");
      out.write("\tloadMyRankGrid();\r\n");
      out.write("\t\r\n");
      out.write("\t//加载职级\r\n");
      out.write("\tloadMyBudgetypeGrid();\r\n");
      out.write("    \r\n");
      out.write("    //加载表单验证\r\n");
      out.write("    $(\"#myForm\").validate();\r\n");
      out.write("    $('#myForm').ajaxForm(function(data) {\r\n");
      out.write("        //节点处理\r\n");
      out.write("    \tvar nameValue=data.companyname;\r\n");
      out.write("    \t\r\n");
      out.write("    \tif(add){//新增\r\n");
      out.write("    \t\tvar newNode = {id:data.companyid, name:nameValue,iconSkin:\"company\",code:\"company\",marker:data.companycode,ename:1,isaudit:true};\r\n");
      out.write("       \t\tzTree.addNodes(selectNode, newNode);\r\n");
      out.write("        }else{\r\n");
      out.write("        \tselectNode.name = nameValue;\r\n");
      out.write("   \t\t\tzTree.updateNode(selectNode);\r\n");
      out.write("   \t\t\tzTree.selectNode(selectNode);\r\n");
      out.write("        }\r\n");
      out.write("    \tadd=false;\r\n");
      out.write("    \t//不可编辑\r\n");
      out.write("    \tformDisabled(true);\r\n");
      out.write("    \t//取消状态\r\n");
      out.write("    \tonCancel();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("  \t//把表单置为不可编辑\r\n");
      out.write("    formDisabled(true);\r\n");
      out.write("  \t\r\n");
      out.write("\t//日期\r\n");
      out.write("    $(\".datepicker\").datepicker({\r\n");
      out.write("        dateFormat: 'yy-mm-dd',\r\n");
      out.write("       \tbeforeShow: function(input, inst) {\r\n");
      out.write("   \t\t\tif($(input).attr(\"readonly\"))\r\n");
      out.write("   \t\t\t\tinst.inline=true;\r\n");
      out.write("   \t\t}\r\n");
      out.write("    });\r\n");
      out.write("  \t\r\n");
      out.write("    //关闭等待层\r\n");
      out.write("    if(window.parent.hidenLoading)\r\n");
      out.write("    \twindow.parent.hidenLoading();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//tab页\r\n");
      out.write("var tabIndex=0;\r\n");
      out.write("function loadTab(){\r\n");
      out.write("\t$(\"#mytab\").tabs({\r\n");
      out.write("    \tselect: function(event, ui) {\r\n");
      out.write("    \t\ttabIndex=ui.index;\r\n");
      out.write("    \t\t$(\".gruop_hidden\").hide();\r\n");
      out.write("    \t\t$(\"#tab\"+tabIndex).show();\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t//控制tab\r\n");
      out.write("\t\t\tif(selectNode!=null){\r\n");
      out.write("\t\t\t\tif(selectNode.isaudit)\r\n");
      out.write("\t\t\t\t\t$(\"#group\"+tabIndex).show();\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t$(\"#group\"+tabIndex).hide();\r\n");
      out.write("\t\t\t\tif(tabIndex==1){\r\n");
      out.write("\t\t\t\t\tmyjobgrid.reload();\r\n");
      out.write("\t\t\t\t}else if(tabIndex==2){\r\n");
      out.write("\t\t\t\t\tmyrankgrid.reload();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tmyBudgetypegrid.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#group\"+tabIndex).hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//树\r\n");
      out.write("var zTree;\r\n");
      out.write("//选中节点\r\n");
      out.write("var selectNode=null;\r\n");
      out.write("function buildCompanyTree(){\r\n");
      out.write("//配置\r\n");
      out.write("var setting = {\r\n");
      out.write("\tedit: {\r\n");
      out.write("\t\tdrag: {\r\n");
      out.write("\t\t\tautoExpandTrigger: true,\r\n");
      out.write("\t\t\tprev: dropPrev,\r\n");
      out.write("\t\t\tinner: dropInner,\r\n");
      out.write("\t\t\tnext: dropNext\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tenable: true,\r\n");
      out.write("\t\tshowRemoveBtn: false,\r\n");
      out.write("\t\tshowRenameBtn: false\r\n");
      out.write("\t},\r\n");
      out.write("\tcallback:{\r\n");
      out.write("\t\tbeforeDrag: beforeDrag,\r\n");
      out.write("\t\tbeforeDrop: beforeDrop,\r\n");
      out.write("\t\tbeforeDragOpen: beforeDragOpen,\r\n");
      out.write("\t\tonDrag: onDrag,\r\n");
      out.write("\t\tonDrop: onDrop,\r\n");
      out.write("\t\tbeforeClick: function(treeId, treeNode) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t$(\"#myForm\").clearForm();\r\n");
      out.write("\t\tselectNode=treeNode;\r\n");
      out.write("\t\tformDisabled(true);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//出现按钮组一\r\n");
      out.write("\t\t$('#b1').show();\r\n");
      out.write("\t\t$('#b2').hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//只能新增\r\n");
      out.write("\t\tif(treeNode.code!='company'){\r\n");
      out.write("\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${add==true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t$('#new').show();\r\n");
      out.write("\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t}else if(treeNode.code=='company'){\r\n");
      out.write("\t\t\t//有效的\r\n");
      out.write("\t\t\tif(treeNode.ename==1){\r\n");
      out.write("\t\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${edit==true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t\t$('#edit').show();\r\n");
      out.write("\t\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${add==true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t\t$('#new').show();\r\n");
      out.write("\t\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${del==true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t\t$('#del').show();\r\n");
      out.write("\t\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t\t$('#new').hide();\r\n");
      out.write("\t\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${revert==true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t\t$(\"#recover\").show();\r\n");
      out.write("\t\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${valid==true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t\t$(\"#remove\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t//取数据\r\n");
      out.write("\t\t\tloadData(treeNode.id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t$('#new').hide();\r\n");
      out.write("\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t}}};\r\n");
      out.write("\tvar myvalid=$(\"#myvalid\").attr(\"checked\")?1:0;\r\n");
      out.write("    $.getJSON(\"company/buildCompanyTree.do\",{valid:myvalid}, function(tdata) {\r\n");
      out.write("    \tzTree = $.fn.zTree.init($(\"#tree\"),setting, tdata);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//节点排序\r\n");
      out.write("function onDrop(event, treeId, treeNodes, targetNode, moveType, isCopy) {\r\n");
      out.write("\tif(treeNodes.lenght>0){\r\n");
      out.write("\t\talert(\"请选择1个节点进行排序！\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(targetNode==null\t)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tselectNode=treeNodes[0];\r\n");
      out.write("\t$.post(\"company/orderCompany.do\",{id:selectNode.id,targetid:targetNode.id,moveType:moveType}, function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//加载数据\r\n");
      out.write("function loadData(tid){\r\n");
      out.write("\t$(\"#myForm\").clearForm();\r\n");
      out.write("\tif(tid!=null&&tid!=''&&tid!='null')\r\n");
      out.write("\t\t$.getJSON(\"company/getCompanyById.do\", {id:tid}, function(data) {\r\n");
      out.write("\t\t\tif(data!=null){\r\n");
      out.write("\t\t\t\tfor (var key in data) {\r\n");
      out.write("\t\t\t        var el = $('#myForm #' + key);\r\n");
      out.write("\t\t\t        if(el) \r\n");
      out.write("\t\t\t            el.val(data[key]);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//控制tab\r\n");
      out.write("\t\t\t\tif(selectNode!=null){\r\n");
      out.write("\t\t\t\t\tif(selectNode.isaudit)\r\n");
      out.write("\t\t\t\t\t\t$(\"#group\"+tabIndex).show();\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t$(\"#group\"+tabIndex).hide();\r\n");
      out.write("\t\t\t\t\tif(tabIndex==1){\r\n");
      out.write("\t\t\t\t\t\tmyjobgrid.reload();\r\n");
      out.write("\t\t\t\t\t}else if(tabIndex==2){\r\n");
      out.write("\t\t\t\t\t\tmyrankgrid.reload();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tmyBudgetypegrid.reload();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#group\"+tabIndex).hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//新增\r\n");
      out.write("var add=false;\r\n");
      out.write("function addNode(){\r\n");
      out.write("\t$('#b1').hide();\r\n");
      out.write("\t$('#b2').show();\r\n");
      out.write("\t$(\"#myForm\").clearForm();\r\n");
      out.write("\tformDisabled(false);\r\n");
      out.write("\tadd=true;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#myForm #state\").val(1);\r\n");
      out.write("\t$(\"#modiuser\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("\t\r\n");
      out.write("\t//设置上级\r\n");
      out.write("\tif(selectNode!=null){\r\n");
      out.write("\t\tvar pcompanyid=selectNode.id;\r\n");
      out.write("\t\tif(pcompanyid!=null&&pcompanyid!=''){\r\n");
      out.write("\t\t\t$('#pcompanyid').val(pcompanyid);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//编辑\r\n");
      out.write("function editNode(){\r\n");
      out.write("\t$('#b1').hide();\r\n");
      out.write("\t$('#b2').show();\r\n");
      out.write("\tformDisabled(false);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//保存\r\n");
      out.write("function save(){\r\n");
      out.write("\t$('#myForm').submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//取消\r\n");
      out.write("function onCancel(){\r\n");
      out.write("\t//取数据\r\n");
      out.write("\tif(selectNode!=null){\r\n");
      out.write("\t\tif(selectNode.code=='company'){\r\n");
      out.write("\t\t\tloadData(selectNode.id);\r\n");
      out.write("\t\t\t$('#b1').show();\r\n");
      out.write("\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#del').show();\r\n");
      out.write("\t\t\t$('#edit').show();\r\n");
      out.write("\t\t\t$('#new').show();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#b1').show();\r\n");
      out.write("\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#new').show();\r\n");
      out.write("\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tformDisabled(true);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//删除\r\n");
      out.write("function delNode(){\r\n");
      out.write("\t$.post(\"department/getDepartmentByCompanyCode.do\",{companycode:selectNode.marker},function(data){\r\n");
      out.write("\t\tif(data){\r\n");
      out.write("\t\t\talert(\"此公司下还有部门信息,不能删除\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tif(!confirm('确认要删除吗？')){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.post(\"company/delCompanyByCompanyCode.do\",{id:selectNode.id}, function() {\r\n");
      out.write("\t\t\t\tzTree.removeNode(selectNode);\r\n");
      out.write("\t\t\t\t$(\"#myForm\").clearForm();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t \t\t$('#b1').show();\r\n");
      out.write("\t\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t\t$('#new').hide();\r\n");
      out.write("\t\t \t\tformDisabled(true);\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//无效\r\n");
      out.write("function validCompany(valid){\r\n");
      out.write("\tif(selectNode==null)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tif(!confirm('确认要把选中的公司置为无效吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.post(\"company/validCompanyById.do\",{companyid:selectNode.id,valid:valid}, function() {\r\n");
      out.write("\t\tselectNode.iconSkin = \"remove\";\r\n");
      out.write("\t\tselectNode.ename = 0;\r\n");
      out.write("\t\tzTree.updateNode(selectNode);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#b1').show();\r\n");
      out.write("\t\t$('#b2').hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#del').hide();\r\n");
      out.write("\t\t$('#edit').hide();\r\n");
      out.write("\t\t$('#new').hide();\r\n");
      out.write("\t\t$(\"#recover\").show();\r\n");
      out.write("\t\t$(\"#remove\").show();\r\n");
      out.write("\t\tformDisabled(true);\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//还原\r\n");
      out.write("function recoverCompany(valid){\r\n");
      out.write("\tif(selectNode==null)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t$.post(\"company/validCompanyById.do\",{companyid:selectNode.id,valid:valid}, function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tselectNode.iconSkin = \"company\";\r\n");
      out.write("\t\tselectNode.ename = 1;\r\n");
      out.write("\t\tzTree.updateNode(selectNode);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#b1').show();\r\n");
      out.write("\t\t$('#b2').hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#del').show();\r\n");
      out.write("\t\t$('#edit').show();\r\n");
      out.write("\t\t$('#new').show();\r\n");
      out.write("\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\tformDisabled(true);\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//导出公司树\r\n");
      out.write("function expTree(){\r\n");
      out.write("\twindow.open(\"company/exportCompany.do\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"sort\">\r\n");
      out.write("\t<div class=\"sort-title\">\r\n");
      out.write("\t\t<h3>公司管理</h3>\r\n");
      out.write("\t\t<div class=\"title-ctrl\">\r\n");
      out.write("\t\t\t<a class=\"btn-ctrl\" href=\"javascript:chevronUpDown('.sort-cont',false);\"><i class=\"icon icon-chevron-up\"></i></a>\r\n");
      out.write("\t\t\t<a class=\"btn-ctrl\" href=\"javascript:chevronUpDown('.sort-cont',true);\"><i class=\"icon icon-chevron-down\"></i></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"sort-cont sort-table\">\r\n");
      out.write("\t\t<div class=\"table\">\r\n");
      out.write("\t\t\t<div class=\"table-bar\">\r\n");
      out.write("\t\t\t\t<div class=\"table-title\">\r\n");
      out.write("\t\t\t\t表格名称 \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-ctrl\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<span id=\"group0\" class=\"gruop_hidden\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"myvalid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"myvalid\" type=\"checkbox\" class=\"checkboxstyle\" onclick=\"javascript:buildCompanyTree();\" checked=\"true\"/> 只显示当前有效公司\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a id=\"exp\" class=\"btn\" href=\"javascript:expTree();\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exp?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-download\"></i><span>导出</span></a>\r\n");
      out.write("\t\t\t\t\t   \t<span id=\"b1\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"new\" class=\"btn\" href=\"javascript:addNode();\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${add?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-plus\"></i><span>新增</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"edit\" class=\"btn\" href=\"javascript:editNode()\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${edit?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-pencil\"></i><span>修改</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"del\"  class=\"btn\"  href=\"javascript:validCompany(0);\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${valid?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-trash\"></i><span>失效</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"recover\" class=\"btn\" href=\"javascript:recoverCompany(1);\"  style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${\"revert\"?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-repeat\"></i><span>恢复</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"remove\"  class=\"btn\" href=\"javascript:delNode();\"  style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${del?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-remove\"></i><span>删除</span></a>\r\n");
      out.write("\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t   \t\t<span id=\"b2\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn\"  href=\"javascript:save();\"><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn\"  href=\"javascript:onCancel();\"><i class=\"icon icon-share\"></i><span>取消</span></a>\r\n");
      out.write("\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t   \t<span id=\"group1\" class=\"gruop_hidden\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t   \t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"myjobvalid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"myjobvalid\" type=\"checkbox\" class=\"checkboxstyle\" onclick=\"myjobgrid.reload();\" checked=\"true\"/> 只显示有效的数据\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:addMyJob();\"><i class=\"icon icon-plus\"></i><span>新增</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:expJobGrid();\"><i class=\"icon icon-download\"></i><span>导出</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\"  href=\"javascript:validJob(0);\" ><i class=\"icon icon-trash\"></i><span>失效</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:validJob(1);\"><i class=\"icon icon-repeat\"></i><span>恢复</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:removeMyJob();\"><i class=\"icon icon-remove\"></i><span>删除</span></a>\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t   \t\r\n");
      out.write("\t\t\t\t   \t<span id=\"group2\" class=\"gruop_hidden\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"myrankvalid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"myrankvalid\" type=\"checkbox\" class=\"checkboxstyle\" onclick=\"myrankgrid.reload();\" checked=\"true\"/> 只显示有效的数据\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:addMyRank();\"><i class=\"icon icon-plus\"></i><span>新增</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:expRankGrid();\"><i class=\"icon icon-download\"></i><span>导出</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:validRank(0);\"><i class=\"icon icon-trash\"></i><span>失效</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:validRank(1);\"><i class=\"icon icon-repeat\"></i><span>恢复</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:removeMyRank();\"><i class=\"icon icon-remove\"></i><span>删除</span></a>\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t   \t\r\n");
      out.write("\t\t\t\t   \t<span id=\"group3\" class=\"gruop_hidden\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"myBudgetypevalid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"myBudgetypevalid\" type=\"checkbox\" class=\"checkboxstyle\" onclick=\"myBudgetypegrid.reload();\" checked=\"true\"/> 只显示有效的数据\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:addMyBudgetype();\"><i class=\"icon icon-plus\"></i><span>新增</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:expBudgetypeGrid();\"><i class=\"icon icon-download\"></i><span>导出</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:validBudgetype(0);\"><i class=\"icon icon-trash\"></i><span>失效</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:validBudgetype(1);\"><i class=\"icon icon-repeat\"></i><span>恢复</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:removeMyBudgetype();\"><i class=\"icon icon-remove\"></i><span>删除</span></a>\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t   \t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"table-wrapper\" id=\"myContent\" style=\"height:550px;\">\r\n");
      out.write("\t\t\t\t<div class=\"ui-layout-west\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"tree\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"ui-layout-center\" style=\"overflow:hidden;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"mytab\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li ><a href=\"#tab0\">基本信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${job?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><a href=\"#tab1\">公司职务</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rank?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><a href=\"#tab2\">公司职级</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${budgetype?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><a href=\"#tab3\">编制类型</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tab0\" style=\"overflow:auto;height:508px;\">\r\n");
      out.write("\t\t\t\t\t        <form action=\"company/saveOrUpdateCompany.do\" method=\"post\" id=\"myForm\" class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"companyid\" name=\"companyid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"pcompanyid\" name=\"pcompanyid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"state\" name=\"state\" type=\"hidden\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"modiuser\" name=\"modiuser\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"modimemo\" name=\"modimemo\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t    <input id=\"companycode\" name=\"companycode\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<legend>基本信息</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t            \t<li>\r\n");
      out.write("\t\t\t\t\t\t            \t\t<span><em class=\"red\">* </em>公司名称：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"companyname\" name=\"companyname\" class=\"{required:true,maxlength:40} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t                    </li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t            \t<li>\r\n");
      out.write("\t\t\t\t\t\t            \t\t<span>公司代码：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"interfacecode\" name=\"interfacecode\" class=\"{maxlength:30} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t                    </li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t             <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span><em class=\"red\">* </em>公司类型：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"companytype\" name=\"companytype\" type=\"hidden\"/>\r\n");
      out.write("\t\t\t\t\t    \t\t\t\t\t<input id=\"companytypename\" name=\"companytypename\" class=\"{required:true} inputselectstyle\" onclick=\"chooseOptionTree('#companytype','#companytypename','COMPANYTYPE');\"/>\r\n");
      out.write("\t\t\t\t\t    \t\t\t\t\t<div class=\"select-trigger\" onclick=\"chooseOptionTree('#companytype','#companytypename','COMPANYTYPE');\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t            \t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span><em class=\"red\">* </em>创立时间：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"createdate\" name=\"createdate\" class=\"{required:true,dateISO:true} inputselectstyle datepicker\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"date-trigger\"  onclick=\"$('#createdate').focus();\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span>注册资金(万元)：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     <input id=\"regcapital\" name=\"regcapital\"  class=\"{number:true,maxlength:16} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span>法人代表：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"legalperson\" name=\"legalperson\" class=\"{maxlength:30} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t </ul>\r\n");
      out.write("\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span>办公地址：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"officeaddress\" name=\"officeaddress\" class=\"{maxlength:100} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t             \t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span>经营范围：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t     \t<textarea id=\"businessscope\" name=\"businessscope\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\" ></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span>公司简介：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t     \t<textarea id=\"description\" name=\"description\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\" ></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t            <ul style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span>备注：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     <textarea id=\"memo\" name=\"memo\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\" ></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t       </form>\r\n");
      out.write("   \t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t        <div id=\"tab1\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"padding-top:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"myjobTable\" style=\"margin:0px auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"jobgridbox\" ></div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    <div id=\"tab2\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t    \t<div style=\"padding-top:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"myrankTable\" style=\"margin:0px auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"rankgridbox\" ></div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    <div id=\"tab3\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t    \t<div style=\"padding-top:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"myBudgetypeTable\" style=\"margin:0px auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"Budgetypegridbox\" ></div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 添加职务信息窗口 -->\r\n");
      out.write("<div id=\"addJobWindow\" title=\"职务信息\" style=\"display:none;\">\r\n");
      out.write("\t<form action=\"job/saveOrUpdateJob.do\" id=\"addJobForm\" class=\"form\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"jobid\" name=\"jobid\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"companyid\" name=\"companyid\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"state\" name=\"state\" value=\"1\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"modiuser\" name=\"modiuser\" value=\"\"/>\r\n");
      out.write("\t\t<input id=\"modimemo\" name=\"modimemo\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t<input id=\"memo\" name=\"memo\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>排序号：</span>\r\n");
      out.write("\t\t\t\t<input  id=\"dorder\" name=\"dorder\"  class=\"{required:true,number:true,maxlength:100} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>职务名称：</span>\r\n");
      out.write("\t\t\t\t<input id=\"jobname\" name=\"jobname\"  class=\"{required:true,maxlength:50} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span>描述：</span>\r\n");
      out.write("\t\t\t\t<textarea id=\"description\" name=\"description\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\"></textarea>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 添加职级信息窗口 -->\r\n");
      out.write("<div id=\"addRankWindow\" title=\"职级信息\" style=\"display:none;\">\r\n");
      out.write("\t<form action=\"rank/saveOrUpdateRank.do\" id=\"addRankForm\" class=\"form\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"rankid\" name=\"rankid\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"companyid\" name=\"companyid\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"state\" name=\"state\" value=\"1\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"modiuser\" name=\"modiuser\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t\t<input id=\"modimemo\" name=\"modimemo\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t<input id=\"memo\" name=\"memo\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>排序号：</span>\r\n");
      out.write("\t\t\t\t<input  id=\"dorder\" name=\"dorder\"  class=\"{required:true,number:true,maxlength:100} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>代码：</span>\r\n");
      out.write("\t\t\t\t<input  id=\"interfacecode\" name=\"interfacecode\"  class=\"{required:true,number:true,maxlength:38} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>职级名称：</span>\r\n");
      out.write("\t\t\t\t<input id=\"levelname\" name=\"levelname\"  class=\"{required:true,maxlength:40} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span>描述：</span>\r\n");
      out.write("\t\t\t\t<textarea id=\"description\" name=\"description\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\"></textarea>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 添加编制类型信息窗口 -->\r\n");
      out.write("<div id=\"addBudgetypeWindow\" title=\"编制类型信息\" style=\"display:none;\">\r\n");
      out.write("\t<form action=\"budgetype/saveOrUpdateBudgetype.do\" id=\"addBudgetypeForm\" class=\"form\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"budgettypeid\" name=\"budgettypeid\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"companyid\" name=\"companyid\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"state\" name=\"state\" value=\"1\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"modiuser\" name=\"modiuser\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t\t<input id=\"modimemo\" name=\"modimemo\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>排序号：</span>\r\n");
      out.write("\t\t\t\t<input  id=\"dorder\" name=\"dorder\"  class=\"{required:true,number:true,maxlength:100} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>编制类型：</span>\r\n");
      out.write("\t\t\t\t<input id=\"budgettypename\" name=\"budgettypename\"  class=\"{required:true,maxlength:30} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span>备注：</span>\r\n");
      out.write("\t\t\t\t<textarea id=\"memo\" name=\"memo\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\"></textarea>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//职务\r\n");
      out.write("var myjobgrid=null;\r\n");
      out.write("function loadMyJobGrid(){\r\n");
      out.write("\tvar size=getGridSize();\r\n");
      out.write("\tvar wh=$(document.body).outerWidth()-360;\r\n");
      out.write("\t$(\"#myjobTable\").css({width:wh,height:460});\r\n");
      out.write("\t\r\n");
      out.write("\tvar grid_demo_id = \"myGrid1\";\r\n");
      out.write("\tvar dsOption = {\r\n");
      out.write("\t        fields :[\r\n");
      out.write("\t            {name : 'jobid'},\r\n");
      out.write("\t            {name : 'jobname'},\r\n");
      out.write("\t            {name : 'description'},\r\n");
      out.write("\t            {name : 'state'},\r\n");
      out.write("\t            {name : 'dorder'},\r\n");
      out.write("\t            {name : 'memo'},\r\n");
      out.write("\t            {name : 'modiuser'},\r\n");
      out.write("\t            {name : 'moditimestamp'}\r\n");
      out.write("\t        ]\r\n");
      out.write("\t    };\r\n");
      out.write("\t    var colsOption = [\r\n");
      out.write("\t        {id: '选择' ,isCheckColumn : true, editable:false,headAlign:'center',align:'center' },\r\n");
      out.write("\t        {id: 'state', header: \"操作\", width :60 ,headAlign:'center',align:'center',renderer:function(value ,record,colObj,grid,colNo,rowNo){\r\n");
      out.write("\t        \tvar htm='';\r\n");
      out.write("\t        \tif(selectNode!=null&&selectNode.isaudit){\r\n");
      out.write("\t        \t\thtm+='<a href=\"javascript:editMyJob(\\''+record.jobid+'\\');\" class=\"ui-button ui-button-icon-only\" title=\"修改\"><span class=\"ui-icon ui-icon-pencil\"></span>&nbsp;</a>';\r\n");
      out.write("\t\t\t\t\tif(value==1)\r\n");
      out.write("\t\t        \t\thtm+='<a href=\"javascript:recoverJob(\\''+record.jobid+'\\',0);\" class=\"ui-button ui-button-icon-only\" title=\"置为无效\"><span class=\"ui-icon ui-icon-trash\"></span>&nbsp;</a>';\r\n");
      out.write("\t\t        \telse\r\n");
      out.write("\t\t        \t\thtm+='<a href=\"javascript:recoverJob(\\''+record.jobid+'\\',1);\" class=\"ui-button ui-button-icon-only\" title=\"还原\"><span class=\"ui-icon ui-icon-check\"></span>&nbsp;</a>';\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t\t\t\treturn htm;\r\n");
      out.write("\t\t\t}},\r\n");
      out.write("\t        {id: 'dorder' , header: \"排序号\" ,headAlign:'center',align:'center', width :50},\r\n");
      out.write("\t        {id: 'jobname' , header: \"职务名称\" ,width:120,headAlign:'center',align:'left'},\r\n");
      out.write("\t        {id: 'description', header: \"描述\",width:250,headAlign:'center',align:'left'}\r\n");
      out.write("\t    ];\r\n");
      out.write("\t\r\n");
      out.write("\tvar gridOption={\r\n");
      out.write("\t\tid : grid_demo_id,\r\n");
      out.write("\t\tloadURL : 'job/searchJob.do',\r\n");
      out.write("\t\tbeforeLoad:function(reqParam){\r\n");
      out.write("\t\t\tinitJobPagePam();\r\n");
      out.write("\t\t\treqParam['parameters']=pam;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texportURL : 'job/searchJob.do?export=true',\r\n");
      out.write("\t\tbeforeExport:function(){\r\n");
      out.write("\t\t\tinitJobPagePam();\r\n");
      out.write("\t\t\tpam.expAll=$('input[name=\"xls\"]:checked').val();\r\n");
      out.write("\t\t\tmyjobgrid.parameters=pam;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texportFileName : '职务信息表.xls',\r\n");
      out.write("\t\twidth:'100%',\r\n");
      out.write("\t\theight:\"460\",  //\"100%\", // 330,\r\n");
      out.write("\t\tcontainer : 'jobgridbox',\r\n");
      out.write("\t\tautoLoad:false,\r\n");
      out.write("\t\tstripeRows: false,\r\n");
      out.write("\t\tremoteFilter:true,\r\n");
      out.write("\t\tshowIndexColumn:false,\r\n");
      out.write("\t\tselectRowByCheck:true,\r\n");
      out.write("\t\treplaceContainer : true,\r\n");
      out.write("\t\tdataset : dsOption ,\r\n");
      out.write("\t\tcolumns : colsOption,\r\n");
      out.write("\t\ttoolbarContent : 'nav | pagesize  state',\r\n");
      out.write("\t\tpageSizeList : [size,size*2,size*4,size*6,size*8,size*10],\r\n");
      out.write("\t\tpageSize:size,\r\n");
      out.write("\t\tskin:getGridSkin(),\r\n");
      out.write("\t\tonDblClickCell:function(value, record , cell, row, colNO, rowNO,columnObj,grid){\r\n");
      out.write("\t\t\tif(colNO!=0){\r\n");
      out.write("\t\t\t\teditMyJob(record.jobid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tmyjobgrid=new Sigma.Grid( gridOption );\r\n");
      out.write("\tSigma.Util.onLoad( Sigma.Grid.render(myjobgrid) );\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//参数设置\r\n");
      out.write("var pam=null;\r\n");
      out.write("function initJobPagePam(){\r\n");
      out.write("\tpam={};\r\n");
      out.write("\tpam.expAll=0;\r\n");
      out.write("\tif(selectNode!=null)\r\n");
      out.write("\tpam.comid=selectNode.id;\r\n");
      out.write("\tpam.valid=$(\"#myjobvalid\").attr(\"checked\")?1:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//新增\r\n");
      out.write("var addJobForm=null;\r\n");
      out.write("function addMyJob(){\r\n");
      out.write("\t$(\"#addJobWindow\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:480,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\tif(addJobForm.form){\r\n");
      out.write("\t\t\t\t\t$(\"#addJobForm\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},open:function(){\r\n");
      out.write("\t\t\t$(\"#addJobForm\").clearForm();\r\n");
      out.write("\t\t\tif(selectNode==null)\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t$(\"#addJobForm input[id=companyid]\").val(selectNode.id);\r\n");
      out.write("\t\t\t$(\"#addJobForm input[id=state]\").val(1);\r\n");
      out.write("\t\t\t$(\"#addJobForm input[id=modiuser]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tformDisabled(false);\r\n");
      out.write("\t\t\taddJobForm=$(\"#addJobForm\").validate({submitHandler: function(form) {\r\n");
      out.write("\t\t\t    \t$(\"#addJobForm\").ajaxSubmit(function(data) {\r\n");
      out.write("\t\t\t    \t\tmyjobgrid.reload();\r\n");
      out.write("\t\t\t    \t\t$(\"#addJobWindow\").dialog(\"close\");\r\n");
      out.write("\t\t\t        });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//导出\r\n");
      out.write("function expJobGrid(){\r\n");
      out.write("\t$(\"#dialog_exp\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tmodel:true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:400,\r\n");
      out.write("\t\theight:130,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\tmyjobgrid.exportGrid('xls');\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tclose: function() {\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//得到数据\r\n");
      out.write("function loadMyJob(tid){\r\n");
      out.write("\t$(\"#addJobForm\").clearForm();\r\n");
      out.write("\tif(tid!=null&&tid!=''&&tid!='null')\r\n");
      out.write("\t\t$.getJSON(\"job/getJobById.do\", {id:tid}, function(data) {\r\n");
      out.write("\t\t\tif(data!=null){\r\n");
      out.write("\t\t\t\tfor (var key in data) {\r\n");
      out.write("\t\t\t        var el = $('#addJobForm input[id=' + key+'],#addJobForm textarea[id=' + key+']');\r\n");
      out.write("\t\t\t        if(el) \r\n");
      out.write("\t\t\t            el.val(data[key]);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//修改\r\n");
      out.write("function editMyJob(tid){\r\n");
      out.write("\t$(\"#addJobWindow\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:480,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\tif(addJobForm.form){\r\n");
      out.write("\t\t\t\t\t$(\"#addJobForm\").submit();\r\n");
      out.write("\t\t\t\t\tmyjobgrid.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},open:function(){\r\n");
      out.write("\t\t\t$(\"#addJobForm\").clearForm();\r\n");
      out.write("\t\t\tloadMyJob(tid);\r\n");
      out.write("\t\t\tformDisabled(!(selectNode!=null&&selectNode.isaudit));\r\n");
      out.write("\t\t\tif(addJobForm==null)\r\n");
      out.write("\t\t\taddJobForm=$(\"#addJobForm\").validate({debug:true,submitHandler: function(form) {\r\n");
      out.write("\t\t\t    \t$(form).ajaxSubmit(function(data) {\r\n");
      out.write("\t\t\t    \t\tmyjobgrid.reload();\r\n");
      out.write("\t\t\t    \t\t$(\"#addJobWindow\").dialog(\"close\");\r\n");
      out.write("\t\t\t        });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//删除\r\n");
      out.write("function removeMyJob(){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tvar cords=myjobgrid.getSelectedRecords();\r\n");
      out.write("\tfor(var i=0;i<cords.length;i++){\r\n");
      out.write("\t\tarray.push(cords[i].jobid);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(array.length<=0){\r\n");
      out.write("\t\talert('请选择要删除的数据！');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!confirm('确认要删除选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.post(\"job/delJobById.do\",{ids:array.toString()}, function() {\r\n");
      out.write("\t\tmyjobgrid.reload();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//失效恢复\r\n");
      out.write("function validJob(valid){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tvar cords=myjobgrid.getSelectedRecords();\r\n");
      out.write("\tfor(var i=0;i<cords.length;i++){\r\n");
      out.write("\t\tvar obj=cords[i];\r\n");
      out.write("\t\tif(obj.state!=valid)\r\n");
      out.write("\t\t\tarray.push(obj.jobid);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(array.length<=0){\r\n");
      out.write("\t\talert('请选择要'+(valid==0?'失效':'恢复')+'的数据！');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!confirm('确认要'+(valid==0?'失效':'恢复')+'选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.post(\"job/validJobById.do\",{ids:array.toString(),valid:valid}, function() {\r\n");
      out.write("\t\tmyjobgrid.reload();\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//恢复\r\n");
      out.write("function recoverJob(id,valid){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tarray.push(id);\r\n");
      out.write("\t\r\n");
      out.write("\tif(!confirm('确认要'+(valid==0?'失效':'恢复')+'选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.post(\"job/validJobById.do\",{ids:array.toString(),valid:valid}, function() {\r\n");
      out.write("\t\tmyjobgrid.reload();\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//职级\r\n");
      out.write("var myrankgrid=null;\r\n");
      out.write("function loadMyRankGrid(){\r\n");
      out.write("\tvar size=getGridSize();\r\n");
      out.write("\tvar wh=$(document.body).outerWidth()-360;\r\n");
      out.write("\t$(\"#myrankTable\").css({width:wh,height:460});\r\n");
      out.write("\t\r\n");
      out.write("\tvar grid_demo_id = \"myGrid2\";\r\n");
      out.write("\tvar dsOption = {\r\n");
      out.write("\t        fields :[\r\n");
      out.write("\t            {name : 'rankid'},\r\n");
      out.write("\t            {name : 'levelname'},\r\n");
      out.write("\t            {name : 'description'},\r\n");
      out.write("\t            {name : 'state'},\r\n");
      out.write("\t            {name : 'dorder'},\r\n");
      out.write("\t            {name : 'memo'},\r\n");
      out.write("\t            {name : 'modiuser'},\r\n");
      out.write("\t            {name : 'moditimestamp'},\r\n");
      out.write("\t            {name : 'interfacecode'}\r\n");
      out.write("\t        ]\r\n");
      out.write("\t    };\r\n");
      out.write("\t    var colsOption = [\r\n");
      out.write("\t        {id: '选择' ,isCheckColumn : true, editable:false,headAlign:'center',align:'center' },\r\n");
      out.write("\t        {id: 'state', header: \"操作\", width :60 ,headAlign:'center',align:'center',renderer:function(value ,record,colObj,grid,colNo,rowNo){\r\n");
      out.write("\t        \tvar htm='';\r\n");
      out.write("\t        \tif(selectNode!=null&&selectNode.isaudit){\r\n");
      out.write("\t\t        \thtm+='<a href=\"javascript:editMyRank(\\''+record.rankid+'\\');\" class=\"ui-button ui-button-icon-only\" title=\"修改\"><span class=\"ui-icon ui-icon-pencil\"></span>&nbsp;</a>';\r\n");
      out.write("\t\t\t\t\tif(value==1)\r\n");
      out.write("\t\t        \t\thtm+='<a href=\"javascript:recoverRank(\\''+record.rankid+'\\',0);\" class=\"ui-button ui-button-icon-only\" title=\"置为无效\"><span class=\"ui-icon ui-icon-trash\"></span>&nbsp;</a>';\r\n");
      out.write("\t\t        \telse\r\n");
      out.write("\t\t        \t\thtm+='<a href=\"javascript:recoverRank(\\''+record.rankid+'\\',1);\" class=\"ui-button ui-button-icon-only\" title=\"还原\"><span class=\"ui-icon ui-icon-check\"></span>&nbsp;</a>';\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t\t\t\treturn htm;\r\n");
      out.write("\t\t\t}},\r\n");
      out.write("\t        {id: 'dorder' , header: \"排序号\" ,headAlign:'center',align:'center', width :50},\r\n");
      out.write("\t        {id: 'levelname' , header: \"职级名称\" ,width:120,headAlign:'center',align:'left'},\r\n");
      out.write("\t        {id: 'description', header: \"描述\",width:250,headAlign:'center',align:'left'}\r\n");
      out.write("\t    ];\r\n");
      out.write("\t\r\n");
      out.write("\tvar gridOption={\r\n");
      out.write("\t\tid : grid_demo_id,\r\n");
      out.write("\t\tloadURL : 'rank/searchRank.do',\r\n");
      out.write("\t\tbeforeLoad:function(reqParam){\r\n");
      out.write("\t\t\tinitRankPagePam();\r\n");
      out.write("\t\t\treqParam['parameters']=pam;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texportURL : 'rank/searchRank.do?export=true',\r\n");
      out.write("\t\tbeforeExport:function(){\r\n");
      out.write("\t\t\tinitRankPagePam();\r\n");
      out.write("\t\t\tpam.expAll=$('input[name=\"xls\"]:checked').val();\r\n");
      out.write("\t\t\tmyrankgrid.parameters=pam;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texportFileName : '职级信息表.xls',\r\n");
      out.write("\t\twidth:'100%',\r\n");
      out.write("\t\theight:\"460\",  //\"100%\", // 330,\r\n");
      out.write("\t\tcontainer : 'rankgridbox',\r\n");
      out.write("\t\tautoLoad:false,\r\n");
      out.write("\t\tstripeRows: false,\r\n");
      out.write("\t\tremoteFilter:true,\r\n");
      out.write("\t\tshowIndexColumn:false,\r\n");
      out.write("\t\tselectRowByCheck:true,\r\n");
      out.write("\t\treplaceContainer : true,\r\n");
      out.write("\t\tdataset : dsOption ,\r\n");
      out.write("\t\tcolumns : colsOption,\r\n");
      out.write("\t\ttoolbarContent : 'nav | pagesize  state',\r\n");
      out.write("\t\tpageSizeList : [size,size*2,size*4,size*6,size*8,size*10],\r\n");
      out.write("\t\tpageSize:size,\r\n");
      out.write("\t\tskin:getGridSkin(),\r\n");
      out.write("\t\tonDblClickCell:function(value, record , cell, row, colNO, rowNO,columnObj,grid){\r\n");
      out.write("\t\t\tif(colNO!=0){\r\n");
      out.write("\t\t\t\teditMyRank(record.rankid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tmyrankgrid=new Sigma.Grid( gridOption );\r\n");
      out.write("\tSigma.Util.onLoad( Sigma.Grid.render(myrankgrid) );\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//参数设置\r\n");
      out.write("var pam=null;\r\n");
      out.write("function initRankPagePam(){\r\n");
      out.write("\tpam={};\r\n");
      out.write("\tpam.expAll=0;\r\n");
      out.write("\tif(selectNode!=null)\r\n");
      out.write("\tpam.comid=selectNode.id;\r\n");
      out.write("\tpam.valid=$(\"#myrankvalid\").attr(\"checked\")?1:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//导出\r\n");
      out.write("function expRankGrid(){\r\n");
      out.write("\t$(\"#dialog_exp\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tmodel:true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:400,\r\n");
      out.write("\t\theight:130,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\tmyrankgrid.exportGrid('xls');\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tclose: function() {\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//新增\r\n");
      out.write("var addRankForm=null;\r\n");
      out.write("function addMyRank(){\r\n");
      out.write("\t$(\"#addRankWindow\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:480,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\tif(addRankForm.form){\r\n");
      out.write("\t\t\t\t\t$(\"#addRankForm\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},open:function(){\r\n");
      out.write("\t\t\t$(\"#addRankForm\").clearForm();\r\n");
      out.write("\t\t\tif(selectNode==null)\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t$(\"#addRankForm input[id=companyid]\").val(selectNode.id);\r\n");
      out.write("\t\t\t$(\"#addRankForm input[id=state]\").val(1);\r\n");
      out.write("\t\t\t$(\"#addRankForm input[id=modiuser]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("\t\t\tformDisabled(false);\r\n");
      out.write("\t\t\tif(addRankForm==null)\r\n");
      out.write("\t\t\t\taddRankForm=$(\"#addRankForm\").validate({submitHandler: function(form) {\r\n");
      out.write("\t\t\t    \t$(form).ajaxSubmit(function(data) {\r\n");
      out.write("\t\t\t    \t\tmyrankgrid.reload();\r\n");
      out.write("\t\t\t    \t\t$(\"#addRankWindow\").dialog(\"close\");\r\n");
      out.write("\t\t\t        });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//得到数据\r\n");
      out.write("function loadMyRank(tid){\r\n");
      out.write("\t$(\"#addRankForm\").clearForm();\r\n");
      out.write("\tif(tid!=null&&tid!=''&&tid!='null')\r\n");
      out.write("\t\t$.getJSON(\"rank/getRankById.do\", {id:tid}, function(data) {\r\n");
      out.write("\t\t\tif(data!=null){\r\n");
      out.write("\t\t\t\tfor (var key in data) {\r\n");
      out.write("\t\t\t\t\tvar el = $('#addRankForm input[id=' + key+'],#addRankForm textarea[id=' + key+']');\r\n");
      out.write("\t\t\t        if(el) \r\n");
      out.write("\t\t\t            el.val(data[key]);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//修改\r\n");
      out.write("function editMyRank(tid){\r\n");
      out.write("\t$(\"#addRankWindow\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:480,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\tif(addRankForm.form){\r\n");
      out.write("\t\t\t\t\t$(\"#addRankForm\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},open:function(){\r\n");
      out.write("\t\t\t$(\"#addRankForm\").clearForm();\r\n");
      out.write("\t\t\tloadMyRank(tid);\r\n");
      out.write("\t\t\tformDisabled(!(selectNode!=null&&selectNode.isaudit));\r\n");
      out.write("\t\t\tif(addRankForm==null)\r\n");
      out.write("\t\t\t\taddRankForm=$(\"#addRankForm\").validate({debug:true,submitHandler: function(form) {\r\n");
      out.write("\t\t\t    \t$(form).ajaxSubmit(function(data) {\r\n");
      out.write("\t\t\t    \t\tmyrankgrid.reload();\r\n");
      out.write("\t\t\t    \t\t$(\"#addRankWindow\").dialog(\"close\");\r\n");
      out.write("\t\t\t        });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//删除\r\n");
      out.write("function removeMyRank(){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tvar cords=myrankgrid.getSelectedRecords();\r\n");
      out.write("\tfor(var i=0;i<cords.length;i++){\r\n");
      out.write("\t\tarray.push(cords[i].rankid);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(array.length<=0){\r\n");
      out.write("\t\talert('请选择要删除的数据！');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!confirm('确认要删除选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.post(\"rank/delRankById.do\",{ids:array.toString()}, function() {\r\n");
      out.write("\t\tmyrankgrid.reload();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//失效恢复\r\n");
      out.write("function validRank(valid){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tvar cords=myrankgrid.getSelectedRecords();\r\n");
      out.write("\tfor(var i=0;i<cords.length;i++){\r\n");
      out.write("\t\tvar obj=cords[i];\r\n");
      out.write("\t\tif(obj.state!=valid)\r\n");
      out.write("\t\t\tarray.push(obj.rankid);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(array.length<=0){\r\n");
      out.write("\t\talert('请选择要'+(valid==0?'失效':'恢复')+'的数据！');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!confirm('确认要'+(valid==0?'失效':'恢复')+'选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.post(\"rank/validRankById.do\",{ids:array.toString(),valid:valid}, function() {\r\n");
      out.write("\t\tmyrankgrid.reload();\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//恢复\r\n");
      out.write("function recoverRank(id,valid){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tarray.push(id);\r\n");
      out.write("\t\r\n");
      out.write("\tif(!confirm('确认要'+(valid==0?'失效':'恢复')+'选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.post(\"rank/validRankById.do\",{ids:array.toString(),valid:valid}, function() {\r\n");
      out.write("\t\tmyrankgrid.reload();\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//编制类型\r\n");
      out.write("var myBudgetypegrid=null;\r\n");
      out.write("function loadMyBudgetypeGrid(){\r\n");
      out.write("\tvar size=getGridSize();\r\n");
      out.write("\tvar wh=$(document.body).outerWidth()-360;\r\n");
      out.write("\t$(\"#myBudgetypeTable\").css({width:wh,height:460});\r\n");
      out.write("\t\r\n");
      out.write("\tvar grid_demo_id = \"myGrid3\";\r\n");
      out.write("\tvar dsOption = {\r\n");
      out.write("\t        fields :[\r\n");
      out.write("\t            {name : 'budgettypeid'},\r\n");
      out.write("\t            {name : 'budgettypename'},\r\n");
      out.write("\t            {name : 'state'},\r\n");
      out.write("\t            {name : 'dorder'},\r\n");
      out.write("\t            {name : 'memo'},\r\n");
      out.write("\t            {name : 'modiuser'},\r\n");
      out.write("\t            {name : 'moditimestamp'}\r\n");
      out.write("\t        ]\r\n");
      out.write("\t    };\r\n");
      out.write("\t    var colsOption = [\r\n");
      out.write("\t        {id: '选择' ,isCheckColumn : true, editable:false,headAlign:'center',align:'center' },\r\n");
      out.write("\t        {id: 'state', header: \"操作\", width :80 ,headAlign:'center',align:'center',renderer:function(value ,record,colObj,grid,colNo,rowNo){\r\n");
      out.write("\t        \tvar htm='';\r\n");
      out.write("\t        \tif(selectNode!=null&&selectNode.isaudit){\r\n");
      out.write("\t\t        \thtm+='<a href=\"javascript:editMyBudgetype(\\''+record.budgettypeid+'\\');\" class=\"ui-button ui-button-icon-only\" title=\"修改\"><span class=\"ui-icon ui-icon-pencil\"></span>&nbsp;</a>';\r\n");
      out.write("\t\t\t\t\tif(value==1)\r\n");
      out.write("\t\t        \t\thtm+='<a href=\"javascript:recoverBudgetype(\\''+record.budgettypeid+'\\',0);\" class=\"ui-button ui-button-icon-only\" title=\"置为无效\"><span class=\"ui-icon ui-icon-trash\"></span>&nbsp;</a>';\r\n");
      out.write("\t\t        \telse\r\n");
      out.write("\t\t        \t\thtm+='<a href=\"javascript:recoverBudgetype(\\''+record.budgettypeid+'\\',1);\" class=\"ui-button ui-button-icon-only\" title=\"还原\"><span class=\"ui-icon ui-icon-check\"></span>&nbsp;</a>';\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t\t\t\treturn htm;\r\n");
      out.write("\t\t\t}},\r\n");
      out.write("\t        {id: 'dorder' , header: \"排序号\" ,headAlign:'center',align:'center', width :50},\r\n");
      out.write("\t        {id: 'budgettypename' , header: \"编制类型名称\" ,width:150,headAlign:'center',align:'left'},\r\n");
      out.write("\t       \t{id: 'memo', header: \"备注\",width:250,headAlign:'center',align:'left'}\r\n");
      out.write("\t    ];\r\n");
      out.write("\t\r\n");
      out.write("\tvar gridOption={\r\n");
      out.write("\t\tid : grid_demo_id,\r\n");
      out.write("\t\tloadURL : 'budgetype/searchBudgetype.do',\r\n");
      out.write("\t\tbeforeLoad:function(reqParam){\r\n");
      out.write("\t\t\tinitBudgetypePagePam();\r\n");
      out.write("\t\t\treqParam['parameters']=pam;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texportURL : 'budgetype/searchBudgetype.do?export=true',\r\n");
      out.write("\t\tbeforeExport:function(){\r\n");
      out.write("\t\t\tinitBudgetypePagePam();\r\n");
      out.write("\t\t\tpam.expAll=$('input[name=\"xls\"]:checked').val();\r\n");
      out.write("\t\t\tmygrid.parameters=pam;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texportFileName : '编制类型信息表.xls',\r\n");
      out.write("\t\twidth:'100%',\r\n");
      out.write("\t\theight:\"460\",  //\"100%\", // 330,\r\n");
      out.write("\t\tcontainer : 'Budgetypegridbox',\r\n");
      out.write("\t\tautoLoad:false,\r\n");
      out.write("\t\tstripeRows: false,\r\n");
      out.write("\t\tremoteFilter:true,\r\n");
      out.write("\t\tshowIndexColumn:false,\r\n");
      out.write("\t\tselectRowByCheck:true,\r\n");
      out.write("\t\treplaceContainer : true,\r\n");
      out.write("\t\tdataset : dsOption ,\r\n");
      out.write("\t\tcolumns : colsOption,\r\n");
      out.write("\t\ttoolbarContent : 'nav | pagesize  state',\r\n");
      out.write("\t\tpageSizeList : [size,size*2,size*4,size*6,size*8,size*10],\r\n");
      out.write("\t\tpageSize:size,\r\n");
      out.write("\t\tskin:getGridSkin(),\r\n");
      out.write("\t\tonDblClickCell:function(value, record , cell, row, colNO, rowNO,columnObj,grid){\r\n");
      out.write("\t\t\tif(colNO!=0){\r\n");
      out.write("\t\t\t\teditMyBudgetype(record.budgettypeid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tmyBudgetypegrid=new Sigma.Grid( gridOption );\r\n");
      out.write("\tSigma.Util.onLoad( Sigma.Grid.render(myBudgetypegrid) );\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//参数设置\r\n");
      out.write("var pam=null;\r\n");
      out.write("function initBudgetypePagePam(){\r\n");
      out.write("\tpam={};\r\n");
      out.write("\tpam.expAll=0;\r\n");
      out.write("\tif(selectNode!=null)\r\n");
      out.write("\tpam.comid=selectNode.id;\r\n");
      out.write("\tpam.valid=$(\"#myBudgetypevalid\").attr(\"checked\")?1:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//导出\r\n");
      out.write("function expBudgetypeGrid(){\r\n");
      out.write("\t$(\"#dialog_exp\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tmodel:true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:400,\r\n");
      out.write("\t\theight:130,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\tmyBudgetypegrid.exportGrid('xls');\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tclose: function() {\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//新增\r\n");
      out.write("var addBudgetypeForm=null;\r\n");
      out.write("function addMyBudgetype(){\r\n");
      out.write("\t$(\"#addBudgetypeWindow\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:480,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\tif(addBudgetypeForm.form){\r\n");
      out.write("\t\t\t\t\t$(\"#addBudgetypeForm\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},open:function(){\r\n");
      out.write("\t\t\t$(\"#addBudgetypeForm\").clearForm();\r\n");
      out.write("\t\t\tif(selectNode==null)\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#addBudgetypeForm input[id=companyid]\").val(selectNode.id);\r\n");
      out.write("\t\t\t$(\"#addBudgetypeForm input[id=state]\").val(1);\r\n");
      out.write("\t\t\t$(\"#addBudgetypeForm input[id=modiuser]\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tformDisabled(false);\r\n");
      out.write("\t\t\tif(addBudgetypeForm==null)\r\n");
      out.write("\t\t\t\taddBudgetypeForm=$(\"#addBudgetypeForm\").validate({submitHandler: function(form) {\r\n");
      out.write("\t\t\t    \t$(form).ajaxSubmit(function(data) {\r\n");
      out.write("\t\t\t    \t\tmyBudgetypegrid.reload();\r\n");
      out.write("\t\t\t    \t\t$(\"#addBudgetypeWindow\").dialog(\"close\");\r\n");
      out.write("\t\t\t        });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//得到数据\r\n");
      out.write("function loadMyBudgetype(tid){\r\n");
      out.write("\t$(\"#addBudgetypeForm\").clearForm();\r\n");
      out.write("\tif(tid!=null&&tid!=''&&tid!='null')\r\n");
      out.write("\t\t$.getJSON(\"budgetype/getBudgetypeById.do\", {id:tid}, function(data) {\r\n");
      out.write("\t\t\tif(data!=null){\r\n");
      out.write("\t\t\t\tfor (var key in data) {\r\n");
      out.write("\t\t\t\t\tvar el = $('#addBudgetypeForm input[id=' + key+'],#addBudgetypeForm textarea[id=' + key+']');\r\n");
      out.write("\t\t\t        if(el)\r\n");
      out.write("\t\t\t            el.val(data[key]);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//修改\r\n");
      out.write("function editMyBudgetype(tid){\r\n");
      out.write("\t$(\"#addBudgetypeWindow\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:480,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\tif(addBudgetypeForm.form){\r\n");
      out.write("\t\t\t\t\t$(\"#addBudgetypeForm\").submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},open:function(){\r\n");
      out.write("\t\t\t$(\"#addBudgetypeForm\").clearForm();\r\n");
      out.write("\t\t\tloadMyBudgetype(tid);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tformDisabled(!(selectNode!=null&&selectNode.isaudit));\r\n");
      out.write("\t\t\tif(addBudgetypeForm==null)\r\n");
      out.write("\t\t\t\taddBudgetypeForm=$(\"#addBudgetypeForm\").validate({submitHandler: function(form) {\r\n");
      out.write("\t\t\t    \t$(form).ajaxSubmit(function(data) {\r\n");
      out.write("\t\t\t    \t\tmyBudgetypegrid.reload();\r\n");
      out.write("\t\t\t    \t\t$(\"#addBudgetypeWindow\").dialog(\"close\");\r\n");
      out.write("\t\t\t        });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//删除\r\n");
      out.write("function removeMyBudgetype(){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tvar cords=myBudgetypegrid.getSelectedRecords();\r\n");
      out.write("\tfor(var i=0;i<cords.length;i++){\r\n");
      out.write("\t\tarray.push(cords[i].budgettypeid);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(array.length<=0){\r\n");
      out.write("\t\talert('请选择要删除的数据！');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!confirm('确认要删除选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.post(\"budgetype/delBudgetypeById.do\",{ids:array.toString()}, function() {\r\n");
      out.write("\t\tmyBudgetypegrid.reload();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//失效恢复\r\n");
      out.write("function validBudgetype(valid){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tvar cords=myBudgetypegrid.getSelectedRecords();\r\n");
      out.write("\tfor(var i=0;i<cords.length;i++){\r\n");
      out.write("\t\tvar obj=cords[i];\r\n");
      out.write("\t\tif(obj.state!=valid)\r\n");
      out.write("\t\t\tarray.push(obj.budgettypeid);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(array.length<=0){\r\n");
      out.write("\t\talert('请选择要'+(valid==0?'失效':'恢复')+'的数据！');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!confirm('确认要'+(valid==0?'失效':'恢复')+'选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.post(\"budgetype/validBudgetypeById.do\",{ids:array.toString(),valid:valid}, function() {\r\n");
      out.write("\t\tmyBudgetypegrid.reload();\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//恢复\r\n");
      out.write("function recoverBudgetype(id,valid){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tarray.push(id);\r\n");
      out.write("\t\r\n");
      out.write("\tif(!confirm('确认要'+(valid==0?'失效':'恢复')+'选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.post(\"budgetype/validBudgetypeById.do\",{ids:array.toString(),valid:valid}, function() {\r\n");
      out.write("\t\tmyBudgetypegrid.reload();\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 导出 -->\r\n");
      out.write("<div id=\"dialog_exp\" style=\"display:none;\" title=\"数据导出\" >\r\n");
      out.write("\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t  \t&nbsp;\r\n");
      out.write("\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t  \t&nbsp;\r\n");
      out.write("\t\t\t\t<label for=\"xls1\">\r\n");
      out.write("\t\t\t\t\t<input id=\"xls1\" type=\"radio\" name=\"xls\" value=\"0\" checked=\"true\" class=\"checkboxstyle\"/>导出本页\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t  \t&nbsp;\r\n");
      out.write("\t\t\t  \t&nbsp;\r\n");
      out.write("\t\t\t  \t<label for=\"xls2\">\r\n");
      out.write("\t\t\t  \t\t<input id=\"xls2\" type=\"radio\" name=\"xls\" value=\"1\" class=\"checkboxstyle\"/>全部导出\r\n");
      out.write("\t\t\t  \t</label>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
