package org.apache.jsp.pages.employee;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>员工管理</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\"/>    \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/style.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/form.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/jquery-ui-1.8.15.custom.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeStyle.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeIcons.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/gt_grid.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/default/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/green/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/mac/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/china/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/vista/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/calendar/calendar-blue.css\"  />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/public.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.json-2.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.layout.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-ui-1.8.5.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/tree/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/lib/jquery.metadata.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-en.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-setup.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_grid_all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_msg_cn.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"pages/tree.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("\t\r\n");
      out.write("    //列表加载\r\n");
      out.write("    loadGrid();\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  //日期\r\n");
      out.write("    $(\".datepicker\").datepicker({\r\n");
      out.write("        dateFormat: 'yy-mm-dd'\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    //关闭等待层\r\n");
      out.write("    if(window.parent.hidenLoading)\r\n");
      out.write("    \twindow.parent.hidenLoading();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//导出\r\n");
      out.write("function expGrid(){\r\n");
      out.write("\t$(\"#dialog_exp\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tmodel:true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:400,\r\n");
      out.write("\t\theight:130,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\tmygrid.exportGrid('xls');\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tclose: function() {\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//删除\r\n");
      out.write("function remove(){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tvar cords=mygrid.getSelectedRecords();\r\n");
      out.write("\tfor(var i=0;i<cords.length;i++){\r\n");
      out.write("\t\tvar obj=cords[i];\r\n");
      out.write("\t\tvar emp={};\r\n");
      out.write("\t\temp.employeeid=obj.employeeid;\r\n");
      out.write("\t\temp.postionguid=obj.postionguid;\r\n");
      out.write("\t\temp.state=obj.state;\r\n");
      out.write("\t\temp.isstaff=obj.isstaff;\r\n");
      out.write("\t\temp.name=obj.name;\r\n");
      out.write("\t\tarray.push(emp);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(array.length<=0){\r\n");
      out.write("\t\talert('请选择要删除的数据！');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!confirm('确认要删除选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t//参数\r\n");
      out.write("\t$.ajax({  \r\n");
      out.write("        url: \"employee/delEmployeeById.do\",  \r\n");
      out.write("        contentType: \"application/json; charset=utf-8\",  \r\n");
      out.write("        type: \"POST\",  \r\n");
      out.write("        dataType: \"json\",  \r\n");
      out.write("        data: JSON.stringify({list:array}),\r\n");
      out.write("        success: function(result) { \r\n");
      out.write("        \tmygrid.reload();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//兼任\r\n");
      out.write("function onPluralism(id){\r\n");
      out.write("\t$(\"#pluralism\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:700,\r\n");
      out.write("\t\theight:550,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"关闭\": function() {\r\n");
      out.write("\t\t\t\t// 关闭\r\n");
      out.write("\t\t\t\tvar content = document.getElementById('myPluralism');\r\n");
      out.write("\t\t\t\tif (content != null && content.contentWindow!=null&& content.contentWindow.getPageState != null){\r\n");
      out.write("\t\t\t\t\tif(content.contentWindow.getPageState())\r\n");
      out.write("\t\t\t\t\t\tmygrid.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\topen:function(){\r\n");
      out.write("\t\t\tvar url='employee.do?page=list_position&id='+id;\r\n");
      out.write("\t\t\tvar htm='<iframe id=\"myPluralism\" name=\"myPluralism\" width=\"100%\" height=\"450px\" frameborder=\"0\" src=\"'+url+'\" scrolling=\"no\"></iframe>';\r\n");
      out.write("\t\t\t$(\"#pluralism\").html(htm);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tclose:function(){\r\n");
      out.write("\t\t\t$(\"#pluralism\").html(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//取消兼任\r\n");
      out.write("var canclePluralismForm=null;\r\n");
      out.write("function onCanclePluralism(pid){\r\n");
      out.write("\t$(\"#canclePluralism\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:470,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\":function(){\r\n");
      out.write("\t\t\t\tif(canclePluralismForm.form()){\r\n");
      out.write("\t\t\t\t\tvar enddate=$(\"#enddate\").val();\r\n");
      out.write("\t\t\t\t\t$.post(\"employee/endPositionById.do\",{postionguid:pid,enddate:enddate}, function() {\r\n");
      out.write("\t\t\t\t\t\talert(\"取消兼任成功!\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#canclePluralism\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\tmygrid.reload();\r\n");
      out.write("\t\t\t\t  \t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"关闭\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\topen:function(){\r\n");
      out.write("\t\t\t//校验\r\n");
      out.write("\t\t\tif(canclePluralismForm==null)\r\n");
      out.write("\t\t\t\tcanclePluralismForm=$(\"#canclePluralismForm\").validate();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//搜索\r\n");
      out.write("var searchForm=null;\r\n");
      out.write("function searchGrid(){\r\n");
      out.write("\t$(\"#search\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:470,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\":function(){\r\n");
      out.write("\t\t\t\tif(searchForm.form()){\r\n");
      out.write("\t\t\t\t\tmygrid.reload();\r\n");
      out.write("\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"重置\":function(){\r\n");
      out.write("\t\t\t\t$(\"#searchForm\").clearForm();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"关闭\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\topen:function(){\r\n");
      out.write("\t\t\t//校验\r\n");
      out.write("\t\t\tif(searchForm==null)\r\n");
      out.write("\t\t\t\tsearchForm=$(\"#searchForm\").validate();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//公司回调\r\n");
      out.write("function callBackCompany(){\r\n");
      out.write("\t$(\"#deptid\").val(null);\r\n");
      out.write("\t$(\"#deptname\").val(null);\r\n");
      out.write("\t\r\n");
      out.write("\t//部门选择回调\r\n");
      out.write("\tcallbackDept();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//部门选择回调\r\n");
      out.write("function callbackDept(){\r\n");
      out.write("\t$(\"#postid\").val(null);\r\n");
      out.write("\t$(\"#postname\").val(null);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//参数设置\r\n");
      out.write("var pam=null;\r\n");
      out.write("function initPagePam(){\r\n");
      out.write("\tpam={};\r\n");
      out.write("\tpam.expAll=0;\r\n");
      out.write("\tpam.userguid='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar ws=$(\"#workstate\").val();\r\n");
      out.write("\tif(ws!=null&&ws!='')\r\n");
      out.write("\t\tpam.workstate=\"=\"+ws;\r\n");
      out.write("\tpam.secrecy=$(\"#secrecy\").val();\r\n");
      out.write("\tpam.companyid=$(\"#companyid\").val();\r\n");
      out.write("\tpam.deptid=$(\"#deptid\").val();\r\n");
      out.write("\tpam.postid=$(\"#postid\").val();\r\n");
      out.write("\tpam.startdate=$(\"#startdate\").val();\r\n");
      out.write("\tpam.isstaff=$(\"#isstaff\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tpam.name=$(\"#name\").val();\r\n");
      out.write("\tpam.sex=$(\"#sex\").val();\r\n");
      out.write("\tpam.jobnumber=$(\"#jobnumber\").val();\r\n");
      out.write("\t\r\n");
      out.write("\tpam.birthday_s=$(\"#birthday_s\").val();\r\n");
      out.write("\tpam.birthday_e=$(\"#birthday_e\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t//pam.classification=$(\"#classification\").val();\r\n");
      out.write("\tpam.employtype=$(\"#employtype\").val();\r\n");
      out.write("\tpam.joindate_s=$(\"#joindate_s\").val();\r\n");
      out.write("\tpam.joindate_e=$(\"#joindate_e\").val();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//切换视图\r\n");
      out.write("function convertView(url){\r\n");
      out.write("\tif ($(\".sort\").css(\"display\")!=\"none\") {\r\n");
      out.write("\t\t$(\".sort\").hide();\r\n");
      out.write("\t\t$(\"#detail\").show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#detail\").attr(\"src\",url);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$(\"#detail\").height(0);\r\n");
      out.write("\t\t$(\"#detail\").removeAttr(\"src\");\r\n");
      out.write("\t\t$(\".sort\").show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//计算高度\r\n");
      out.write("\t\t_autoHeight();\r\n");
      out.write("\t\tif(url==null)\r\n");
      out.write("\t\t\tmygrid.reload();\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\t\r\n");
      out.write("var mygrid=null;\r\n");
      out.write("function loadGrid(){\r\n");
      out.write("\tvar size=getGridSize();\r\n");
      out.write("\tvar grid_demo_id = \"myGrid1\";\r\n");
      out.write("\tvar dsOption= {\r\n");
      out.write("\t\t\tfields :[\r\n");
      out.write("\t\t\t\t{name : 'employeeid'},\r\n");
      out.write("\t\t\t\t{name : 'name'},\r\n");
      out.write("\t\t\t\t{name : 'sex'},\r\n");
      out.write("\t\t\t\t{name : 'birthday'},\r\n");
      out.write("\t\t\t\t{name : 'cardnumber'},\r\n");
      out.write("\t\t\t\t{name : 'culture'},\r\n");
      out.write("\t\t\t\t{name : 'nation'},\r\n");
      out.write("\t\t\t\t{name : 'mobile'},\r\n");
      out.write("\t\t\t\t{name : 'residenceplace'},\r\n");
      out.write("\t\t\t\t{name : 'homephone'},\r\n");
      out.write("\t\t\t\t{name : 'homeplace'},\r\n");
      out.write("\t\t\t\t{name : 'bloodtype'},\r\n");
      out.write("\t\t\t\t{name : 'domicilplace'},\r\n");
      out.write("\t\t\t\t{name : 'nativeplace'},\r\n");
      out.write("\t\t\t\t{name : 'politics'},\r\n");
      out.write("\t\t\t\t{name : 'married'},\r\n");
      out.write("\t\t\t\t{name : 'privateemail'},\r\n");
      out.write("\t\t\t\t{name : 'photo'},\r\n");
      out.write("\t\t\t\t{name : 'joinworkdate'},\r\n");
      out.write("\t\t\t\t{name : 'joingroupdate'},\r\n");
      out.write("\t\t\t\t{name : 'workstate'},\r\n");
      out.write("\t\t\t\t{name : 'jobnumber'},\r\n");
      out.write("\t\t\t\t{name : 'secrecy'},\r\n");
      out.write("\t\t\t\t{name : 'dorder'},\r\n");
      out.write("\t\t\t\t{name : 'classification'},\r\n");
      out.write("\t\t\t\t{name : 'employtype'},\r\n");
      out.write("\t\t\t\t{name : 'checknumber'},\r\n");
      out.write("\t\t\t\t{name : 'joindate'},\r\n");
      out.write("\t\t\t\t{name : 'startdate'},\r\n");
      out.write("\t\t\t\t{name : 'enddate'},\r\n");
      out.write("\t\t\t\t{name : 'officephone'},\r\n");
      out.write("\t\t\t\t{name : 'email'},\r\n");
      out.write("\t\t\t\t{name : 'shortphone'},\r\n");
      out.write("\t\t\t\t{name : 'officeaddress'},\r\n");
      out.write("\t\t\t\t{name : 'studymonth'},\r\n");
      out.write("\t\t\t\t{name : 'officialdateplan'},\r\n");
      out.write("\t\t\t\t{name : 'officialdate'},\r\n");
      out.write("\t\t\t\t{name : 'officialmemo'},\r\n");
      out.write("\t\t\t\t{name : 'resignationdate'},\r\n");
      out.write("\t\t\t\t{name : 'resignationreason'},\r\n");
      out.write("\t\t\t\t{name : 'interfacecode'},\r\n");
      out.write("\t\t\t\t{name : 'contactphone'},\r\n");
      out.write("\t\t\t\t{name : 'contactrelationship'},\r\n");
      out.write("\t\t\t\t{name : 'contactname'},\r\n");
      out.write("\t\t\t\t{name : 'memo'},\r\n");
      out.write("\t\t\t\t{name : 'modiuser'},\r\n");
      out.write("\t\t\t\t{name : 'moditimestamp'},\r\n");
      out.write("\t\t\t\t{name : 'modimemo'},\r\n");
      out.write("\t\t\t\t{name : 'secrecyname'},\r\n");
      out.write("\t\t\t\t{name : 'sexname'},\r\n");
      out.write("\t\t\t\t{name : 'culturename'},\r\n");
      out.write("\t\t\t\t{name : 'nationname'},\r\n");
      out.write("\t\t\t\t{name : 'bloodtypename'},\r\n");
      out.write("\t\t\t\t{name : 'politicsname'},\r\n");
      out.write("\t\t\t\t{name : 'marriedname'},\r\n");
      out.write("\t\t\t\t{name : 'resignationreasonname'},\r\n");
      out.write("\t\t\t\t{name : 'classificationname'},\r\n");
      out.write("\t\t\t\t{name : 'employtypename'},\r\n");
      out.write("\t\t\t\t{name : 'contactrelationshipname'},\r\n");
      out.write("\t\t\t\t{name : 'state'},\r\n");
      out.write("\t\t\t\t{name : 'isstaff'},\r\n");
      out.write("\t\t\t\t{name : 'isstaffname'},\r\n");
      out.write("\t\t\t\t{name : 'domicilplacename'}\r\n");
      out.write("\t\t\t]\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar colsOption = [\r\n");
      out.write("\t\t\t{id: '选择' ,isCheckColumn : true, editable:false,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'isstaff' , header: \" \" , width :50 ,headAlign:'center',align:'center',hidden:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!position}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(",renderer:function(value ,record,colObj,grid,colNo,rowNo){\r\n");
      out.write("\t\t\t\tvar htm='';\r\n");
      out.write("\t\t\t\tif(value==1){\r\n");
      out.write("\t\t\t\t\tif(record.workstate!=-1){\r\n");
      out.write("\t\t\t\t\t\thtm+='<a href=\"javascript:onPluralism(\\''+record.employeeid+'\\');\" title=\"设置兼任\">';\r\n");
      out.write("\t\t\t\t\t\thtm+='兼任';\r\n");
      out.write("\t\t\t\t\t\thtm+='</a>';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}else if(value==-1){\r\n");
      out.write("\t\t\t\t\thtm+='<a href=\"javascript:convertView(\\'employee.do?page=tab&id='+record.employeeid+'&postionguid='+record.postionguid+'\\');\"  title=\"异动生效\">';\r\n");
      out.write("\t\t\t\t\thtm+='生效';\r\n");
      out.write("\t\t\t\t\thtm+='</a>';\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tif(record.workstate!=-1){\r\n");
      out.write("\t\t\t\t\t\thtm+='<a href=\"javascript:onCanclePluralism(\\''+record.postionguid+'\\');\" title=\"取消兼任\">';\r\n");
      out.write("\t\t\t\t\t\thtm+='取消';\r\n");
      out.write("\t\t\t\t\t\thtm+='</a>';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn htm;\r\n");
      out.write("\t\t\t}},\r\n");
      out.write("\t\t\t{id: 'isstaffname' , header: \"编制\" , width :60 ,headAlign:'center',align:'center',renderer:function(value ,record,colObj,grid,colNo,rowNo){\r\n");
      out.write("\t\t\t\tif(record.isstaff==0){\r\n");
      out.write("\t\t\t\t\treturn '<font color=\"#C8C8C8\">'+value+'</font>';\r\n");
      out.write("\t\t\t\t}else if(record.isstaff==1){\r\n");
      out.write("\t\t\t\t\treturn '<font color=\"green\">'+value+'</font>';\r\n");
      out.write("\t\t\t\t}else if(record.isstaff==-1){\r\n");
      out.write("\t\t\t\t\treturn '<font color=\"#ff0000\">'+value+'</font>';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn value;\r\n");
      out.write("\t\t\t}},\r\n");
      out.write("\t\t\t{id: 'secrecy' , header: \"保密\" , width :40,headAlign:'center',align:'center',renderer:function(value ,record,colObj,grid,colNo,rowNo){\r\n");
      out.write("\t\t\t\tvar htm=\"\";\r\n");
      out.write("\t\t\t\tif(value==2)\r\n");
      out.write("\t\t\t\t\thtm+='<img src=\"skins/images/lock.gif\"/>';\r\n");
      out.write("\t\t\t\treturn htm;\r\n");
      out.write("\t\t\t}},\r\n");
      out.write("\t\t\t{id: 'workstatename' , header: \"状态\" , width :60 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'companyname' , header: \"公司名称\" , width :200 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'deptname' , header: \"部门名称\" , width :150 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'postname' , header: \"岗位名称\" , width :120 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t{id: 'dorder' , header: \"排序号\" , width :80 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'jobnumber' , header: \"工号\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'name' , header: \"姓名\" , width :80 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'email' , header: \"公司邮箱\" , width :150 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'shortphone' , header: \"手机内网号码\" , width :120 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'classificationname' , header: \"员工类别\" , width :80 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'employtypename' , header: \"用工性质\" , width :80 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'jobname' , header: \"职务\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'rankname' , header: \"职级\" , width :100 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'quotaname' , header: \"编制类别\" , width :120 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'cardnumber', header: \"身份证号码\", width :180 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'birthday' , header: \"出生日期\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'sexname' , header: \"性别\" , width :60 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'birthdayname' , header: \"年龄\" , width :50 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'culturename' , header: \"学历情况\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'nationname' , header: \"民族\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'mobile' , header: \"手机\" , width :120 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'addressmobile' , header: \"通讯录手机\" , width :120 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'domicilplacename' , header: \"户籍类型\" , width :200 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'nativeplace' , header: \"籍贯\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'politicsname' , header: \"政治面貌\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'marriedname' , header: \"婚姻状况\" , width :100 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'bloodtypename' , header: \"血型\" , width :100 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'joinworkdate' , header: \"参加工作时间\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'joingroupdate' , header: \"加入集团时间\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'secrecyname' , header: \"员工信息保密\" , width :100 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'checknumber' , header: \"考勤号\" , width :80 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'joindate' , header: \"加入公司时间\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'startdate' , header: \"聘任开始时间\" , width :120 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'enddate' , header: \"聘任结束时间\" , width :120 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'officephone' , header: \"办公电话\" , width :80 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'officeaddress' , header: \"办公地址\" , width :200 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'residenceplace' , header: \"身份证地址\" , width :200 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'homeplace' , header: \"家庭住址\" , width :200 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'homephone' , header: \"家庭电话\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'privateemail' , header: \"私人邮箱\" , width :150 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'social' , header: \"社保归属地\" , width :150 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'contactname' , header: \"紧急联系人\" , width :80 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'contactrelationshipname' , header: \"与紧急联系关系\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'contactphone' , header: \"紧急联系人电话\" , width :150 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'studymonth' , header: \"试用期（月）\" , width :80 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'officialdateplan' , header: \"计划转正时间\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'officialdate' , header: \"转正时间\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'officialmemo' , header: \"转正备注\" , width :200 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'resignationdate' , header: \"离职时间\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'resignationreasonname' , header: \"离职原因\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t\t\t{id: 'modimemo' , header: \"备注\" , width :200 ,headAlign:'center',headAlign:'left',align:'left'}\r\n");
      out.write("\t\t];\r\n");
      out.write("\tvar gridOption={\r\n");
      out.write("\t\tid : grid_demo_id,\r\n");
      out.write("\t\tsaveURL :'employee/saveEmployeeGrid.do',\r\n");
      out.write("\t\tloadURL :'employee/searchEmployee.do',\r\n");
      out.write("\t\tbeforeLoad:function(reqParam){\r\n");
      out.write("\t\t\tinitPagePam();\r\n");
      out.write("\t\t\treqParam['parameters']=pam;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texportURL : 'employee/searchEmployee.do?export=true',\r\n");
      out.write("\t\tbeforeExport:function(){\r\n");
      out.write("\t\t\tinitPagePam();\r\n");
      out.write("\t\t\tpam.expAll=$('input[name=\"xls\"]:checked').val();\r\n");
      out.write("\t\t\tmygrid.parameters=pam;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texportFileName : '员工信息表.xls',\r\n");
      out.write("\t\twidth: \"99.8%\",//\"100%\", // 700,\r\n");
      out.write("\t\theight: \"100%\",  //\"100%\", // 330,\r\n");
      out.write("\t\tcontainer : 'gridbox', \r\n");
      out.write("\t\tpageSizeList : [size,size*2,size*4,size*6,size*8,size*10],\r\n");
      out.write("\t\tstripeRows: false,\r\n");
      out.write("\t\tremoteFilter:true,\r\n");
      out.write("\t\tshowIndexColumn:true,\r\n");
      out.write("\t\tselectRowByCheck:true,\r\n");
      out.write("\t\treplaceContainer : true,\r\n");
      out.write("\t\tshowGridMenu : true,\r\n");
      out.write("\t\tallowFreeze\t: true ,\r\n");
      out.write("\t\tallowHide\t: true ,\r\n");
      out.write("\t\tallowGroup\t: true ,\r\n");
      out.write("\t\tdataset : dsOption ,\r\n");
      out.write("\t\tcolumns : colsOption,\r\n");
      out.write("\t\ttoolbarContent : 'nav | pagesize | reload  state',\r\n");
      out.write("\t\tpageSize:size,\r\n");
      out.write("\t\tskin:getGridSkin(),\r\n");
      out.write("\t\tcustomRowAttribute : function(record,rn,grid){\r\n");
      out.write("\t\t\t//生效状态\r\n");
      out.write("\t\t\tif(record.isstaff==-1){\r\n");
      out.write("\t\t\t\treturn 'style=\"background:#edf4fe;\"';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(record.workstate==-1){\r\n");
      out.write("\t\t\t\treturn 'style=\"background:#fff6f6;\"';\r\n");
      out.write("\t\t\t}else if(record.workstate==0){\r\n");
      out.write("\t\t\t\treturn 'style=\"background:#ffffec;\"';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tonDblClickCell:function(value, record , cell, row, colNO, rowNO,columnObj,grid){\r\n");
      out.write("\t\t\tif(colNO!=0){\r\n");
      out.write("\t\t\t\tconvertView('employee.do?page=tab&id='+record.employeeid+\"&postionguid=\"+record.postionguid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tmygrid=new Sigma.Grid( gridOption );\r\n");
      out.write("\tSigma.Util.onLoad( Sigma.Grid.render(mygrid) );\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sort\">\r\n");
      out.write("\t<div class=\"sort-title\">\r\n");
      out.write("\t\t<h3>员工管理</h3>\r\n");
      out.write("\t\t<div class=\"title-ctrl\">\r\n");
      out.write("\t\t\t<a class=\"btn-ctrl\" href=\"javascript:chevronUpDown('.sort-cont',false);\"><i class=\"icon icon-chevron-up\"></i></a>\r\n");
      out.write("\t\t\t<a class=\"btn-ctrl\" href=\"javascript:chevronUpDown('.sort-cont',true);\"><i class=\"icon icon-chevron-down\"></i></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"sort-cont sort-table\">\r\n");
      out.write("\t\t<div class=\"table\">\r\n");
      out.write("\t\t\t<div class=\"table-bar\">\r\n");
      out.write("\t\t\t\t<div class=\"table-title\">\r\n");
      out.write("\t\t\t\t\t表格名称\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-ctrl\">\r\n");
      out.write("\t\t\t\t\t<a class=\"btn\" href=\"javascript:searchGrid();\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${search?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-search\"></i><span>搜索</span></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn\" href=\"javascript:convertView('employee.do?page=import');\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imp?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-qrcode\"></i><span>导入</span></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn\" href=\"javascript:expGrid();\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exp?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-list-alt\"></i><span>导出</span></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn\" href=\"javascript:convertView('employee.do?page=tab');\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${add?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-plus\"></i><span>入职</span></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn\" href=\"javascript:convertView('employee.do?page=list_yidong');\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-indent-left\"></i><span>异动</span></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn\" href=\"javascript:remove();\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${del?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-remove\"></i><span>删除</span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"table-wrapper\">\r\n");
      out.write("\t\t\t\t<div id=\"myTable\" style=\"height:550px;margin:5px auto;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"gridbox\" ></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<iframe id=\"detail\" name=\"detail\" width=\"100%\" height=\"100%\" frameborder=\"0\" src=\"\" scrolling=\"no\" style=\"display:none;\"></iframe>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 搜索 -->\r\n");
      out.write("<div id=\"search\" title=\"搜索条件设置\" style=\"display:none;\">\r\n");
      out.write("\t<form action=\"\" id=\"searchForm\" class=\"form\">\r\n");
      out.write("\t\t<ul id=\"myCompany\">\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("                <span>公司名称：</span>\r\n");
      out.write("                <input id=\"companyid\" name=\"companyid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"companyname\" name=\"companyname\" class=\"inputselectstyle\" onclick=\"chooseMyHasCompanyTree('#companyid','#companyname',callBackCompany);\"/>\r\n");
      out.write("\t\t\t    <div class=\"search-trigger\" onclick=\"chooseMyHasCompanyTree('#companyid','#companyname',callBackCompany);\"/>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t    <span>部门名称：</span>\r\n");
      out.write("\t\t\t    <input id=\"deptid\" name=\"deptid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"deptname\" name=\"deptname\" class=\"inputselectstyle\" onclick=\"chooseOneCompanyDeptTree('#deptid','#deptname',$('#companyid').val(),callbackDept);\"/>\r\n");
      out.write("\t\t\t    <div class=\"search-trigger\" onclick=\"chooseOneCompanyDeptTree('#deptid','#deptname',$('#companyid').val(),callbackDept);\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t    <span>岗位名称：</span>\r\n");
      out.write("\t\t\t    <input id=\"postid\" name=\"postid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"postname\" name=\"postname\" class=\"inputselectstyle\" onclick=\"choosePostTree('#postid','#postname',$('#deptid').val());\"/>\r\n");
      out.write("\t\t\t    <div class=\"search-trigger\" onclick=\"choosePostTree('#postid','#postname',$('#deptid').val());\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("         \t<li>\r\n");
      out.write("\t\t\t    <span>聘任时间：</span>\r\n");
      out.write("\t\t\t    <input id=\"startdate\" name=\"startdate\" class=\"{dateISO:true} inputselectstyle datepicker\"/>\r\n");
      out.write("\t\t\t    <div class=\"date-trigger\" onclick=\"$('#startdate').focus();\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span>员工状态：</span>\r\n");
      out.write("                <input id=\"workstate\" name=\"workstate\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"workstatename\" name=\"workstatename\" class=\"inputselectstyle\" onclick=\"chooseOptionTree('#workstate','#workstatename','WORKSTATE');\"/>\r\n");
      out.write("\t\t\t    <div class=\"select-trigger\" onclick=\"chooseOptionTree('#workstate','#workstatename','WORKSTATE');\"/>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("\t       <li>\r\n");
      out.write("\t\t\t    <span>编制：</span>\r\n");
      out.write("\t\t\t    <input id=\"isstaff\" name=\"isstaff\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"isstaffname\" name=\"isstaffname\" class=\"inputselectstyle\" onclick=\"chooseOptionTree('#isstaff','#isstaffname','ISSTAFF');\"/>\r\n");
      out.write("\t\t\t    <div class=\"select-trigger\" onclick=\"chooseOptionTree('#isstaff','#isstaffname','ISSTAFF');\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("       </ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("                <span>姓名：</span>\r\n");
      out.write("                <input id=\"name\" name=\"name\" class=\"inputstyle\"/>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("                <span>员工工号：</span>\r\n");
      out.write("                <input id=\"jobnumber\" name=\"jobnumber\" class=\"inputstyle\"/>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t    <span>性别：</span>\r\n");
      out.write("\t\t\t    <input id=\"sex\" name=\"sex\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"sexname\" name=\"sexname\" class=\"inputselectstyle\" onclick=\"chooseOptionTree('#sex','#sexname','SEX');\"/>\r\n");
      out.write("\t\t\t    <div class=\"select-trigger\" onclick=\"chooseOptionTree('#sex','#sexname','SEX');\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("         \t<li>\r\n");
      out.write("\t\t\t    <span>年龄从：</span>\r\n");
      out.write("\t\t\t    <input id=\"birthday_e\" name=\"birthday_e\" class=\"{digits:true} inputstyle\" style=\"width:97px;\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("            <li>\r\n");
      out.write("\t\t\t    <span style=\"width:16px;\">至&nbsp;</span>\r\n");
      out.write("\t\t\t    <input id=\"birthday_s\" name=\"birthday_s\" class=\"{digits:true} inputstyle\" style=\"width:97px;\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("         \t<li style=\"display:inline;\">\r\n");
      out.write("\t\t\t    <span>入职时间从：</span>\r\n");
      out.write("\t\t\t    <input id=\"joindate_s\" name=\"joindate_s\" class=\"{dateISO:true} inputselectstyle datepicker\" style=\"width:80px;\"/>\r\n");
      out.write("\t\t\t    <div class=\"date-trigger\" onclick=\"$('#joindate_s').focus();\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("            <li style=\"display:inline;\">\r\n");
      out.write("\t\t\t    <span style=\"width:16px;\">至&nbsp;</span>\r\n");
      out.write("\t\t\t     <input id=\"joindate_e\" name=\"joindate_e\" class=\"{dateISO:true} inputselectstyle datepicker\" style=\"width:80px;\"/>\r\n");
      out.write("\t\t\t    <div class=\"date-trigger\" onclick=\"$('#joindate_e').focus();\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span>员工信息保密：</span>\r\n");
      out.write("\t\t\t    <input id=\"secrecy\" name=\"secrecy\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"secrecyname\" name=\"secrecyname\" class=\"inputselectstyle\" onclick=\"chooseOptionTree('#secrecy','#secrecyname','SECRETLEVEL');\"/>\r\n");
      out.write("\t\t\t    <div class=\"select-trigger\" onclick=\"chooseOptionTree('#secrecy','#secrecyname','SECRETLEVEL');\"/>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\t   <ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t    <span>用工性质：</span>\r\n");
      out.write("\t\t\t    <input id=\"employtype\" name=\"employtype\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"employtypename\" name=\"employtypename\" class=\"inputselectstyle\" onclick=\"chooseOptionTree('#employtype','#employtypename','EMPLOYTYPE');\"/>\r\n");
      out.write("\t\t\t    <div class=\"select-trigger\" onclick=\"chooseOptionTree('#employtype','#employtypename','EMPLOYTYPE');\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 导出 -->\r\n");
      out.write("<div id=\"dialog_exp\" style=\"display:none;\" title=\"数据导出\" >\r\n");
      out.write("\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t  \t&nbsp;\r\n");
      out.write("\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t  \t&nbsp;\r\n");
      out.write("\t\t\t\t<label for=\"xls1\">\r\n");
      out.write("\t\t\t\t\t<input id=\"xls1\" type=\"radio\" name=\"xls\" value=\"0\" checked=\"true\" class=\"checkboxstyle\"/>导出本页\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t  \t&nbsp;\r\n");
      out.write("\t\t\t  \t&nbsp;\r\n");
      out.write("\t\t\t  \t<label for=\"xls2\">\r\n");
      out.write("\t\t\t  \t\t<input id=\"xls2\" type=\"radio\" name=\"xls\" value=\"1\" class=\"checkboxstyle\"/>全部导出\r\n");
      out.write("\t\t\t  \t</label>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 兼任-->\r\n");
      out.write("<div id=\"pluralism\" title=\"员工兼任信息\" style=\"display:none;overflow:hidden;\">\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 取消兼任-->\r\n");
      out.write("<div id=\"canclePluralism\" title=\"取消兼任\" style=\"display:none;overflow:hidden;\">\r\n");
      out.write("\t<form action=\"\" id=\"canclePluralismForm\" class=\"form\">\r\n");
      out.write("        <ul>\r\n");
      out.write("         \t<li>\r\n");
      out.write("\t\t\t    <span><em class=\"red\">* </em>结束时间：</span>\r\n");
      out.write("\t\t\t    <input id=\"enddate\" name=\"enddate\" class=\"{required:true,dateISO:true} inputselectstyle datepicker\"/>\r\n");
      out.write("\t\t\t    <div class=\"date-trigger\" onclick=\"$('#enddate').focus();\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
