package org.apache.jsp.pages.quota;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>编制管理</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\"/>    \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/style.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/form.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/jquery-ui-1.8.15.custom.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeStyle.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeIcons.css\"/>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/public.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.json-2.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-ui-1.8.5.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/tree/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/lib/jquery.metadata.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"pages/tree.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"pages/bpmn/workflow.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var tid='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.id}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("var taskid='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.taskid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\r\n");
      out.write("var pageState=false;\r\n");
      out.write("var myvalidform=null;\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    //加载表单验证\r\n");
      out.write("    myvalidform=$(\"#myForm\").validate({submitHandler:function(form) {\r\n");
      out.write("\t    \t$(form).ajaxSubmit(function(data) {\r\n");
      out.write("\t    \t\talert(\"保存成功\");\r\n");
      out.write("\t    \t\ttid=data.quotaid;\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\tloadData();\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\tpageState=true;\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t        \t//页面保存过\r\n");
      out.write("\t        \twindow.parent.callbackPageState(true);\r\n");
      out.write("\t        });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \t//加載數據\r\n");
      out.write("    //loadData();\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    //日期\r\n");
      out.write("    $(\".datepicker\").datepicker({\r\n");
      out.write("        dateFormat: 'yy-mm-dd',\r\n");
      out.write("       \tbeforeShow: function(input, inst) {\r\n");
      out.write("   \t\t\tif($(input).attr(\"readonly\"))\r\n");
      out.write("   \t\t\t\tinst.inline=true;\r\n");
      out.write("   \t\t}\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//加载数据\r\n");
      out.write("function loadData(){\r\n");
      out.write("\tif(tid!=null&&tid!=''&&tid!='null'){\r\n");
      out.write("\t\t$.getJSON(\"quota/getQuotaById.do\", {id:tid,taskid:taskid}, function(data) {\r\n");
      out.write("\t\t\tif(data!=null){\r\n");
      out.write("\t\t\t\tfor (var key in data) {\r\n");
      out.write("\t\t\t        var el = $('#myForm #' + key);\r\n");
      out.write("\t\t\t        if(el) \r\n");
      out.write("\t\t\t            el.val(data[key]);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//按钮状态\r\n");
      out.write("\t\t\t\tbutState(data);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//回调\r\n");
      out.write("\t\t\t\tif(window.parent.callbackQuota)\r\n");
      out.write("\t\t\t\t\twindow.parent.callbackQuota(tid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tbutState(null);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//按钮\r\n");
      out.write("function butState(obj){\r\n");
      out.write("\t//判断是否可以保存\r\n");
      out.write("\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.edit!=true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("){\r\n");
      out.write("\t\tformDisabled(true,'#myForm');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(obj==null){\r\n");
      out.write("\t\t$(\"#save\").show();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//是否审核中\r\n");
      out.write("\tif(obj.state==1){\r\n");
      out.write("\t\tformDisabled(false,'#myForm');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#save\").show();\r\n");
      out.write("\t\t$(\"#audit\").hide();\r\n");
      out.write("\t}else if(obj.state==2&&obj.assignee=='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("'){//当前用户是审核用户\r\n");
      out.write("\t\t$(\"#taskid\").val(taskid);\r\n");
      out.write("\t\tformDisabled(true,'#myForm');\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\"#save\").hide();\r\n");
      out.write("  \t\t$(\"#audit\").show();\r\n");
      out.write("\t}else if(obj.state==2&&obj.assignee!='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("'){\r\n");
      out.write("\t\tformDisabled(true,'#myForm');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#save\").hide();\r\n");
      out.write("\t\t$(\"#audit\").hide();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tformDisabled(false,'#myForm');\r\n");
      out.write("\t\t$(\"#save\").show();\r\n");
      out.write("\t\t$(\"#audit\").hide();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//审核信息\r\n");
      out.write("\tif(obj.audithistorys!=null){\r\n");
      out.write("\t\trenderProcessInfo(obj.audithistorys);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//保存\r\n");
      out.write("function save(){\r\n");
      out.write("\tvar postid=$(\"#postid\").val();\r\n");
      out.write("\tvar quotaid=$(\"#quotaid\").val();\r\n");
      out.write("\tvar state=$(\"#state\").val();\r\n");
      out.write("\tvar budgettype=$(\"#budgettype\").val();\r\n");
      out.write("\t$.post(\"quota/checkQuotaByPostIdAndBudgettype.do\",{quotaid:quotaid,postid:postid,budgettype:budgettype,state:state}, function(data) {\r\n");
      out.write("\t\tif(data!=null&&data!=\"\"){\r\n");
      out.write("\t\t\talert(data);\r\n");
      out.write("\t\t\t$(\"#budgettype\").val(null);\r\n");
      out.write("\t\t\t$(\"#budgettypename\").val(null);\r\n");
      out.write("\t\t\t$(\"#postid\").val(null);\r\n");
      out.write("\t\t\t$(\"#postname\").val(null);\r\n");
      out.write("\t\t}else\r\n");
      out.write("\t\t\t$(\"#runprocess\").val(true);\r\n");
      out.write("\t\t\t$('#myForm').submit();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//返回\r\n");
      out.write("function back(){\r\n");
      out.write("\twindow.parent.convertView(pageState?null:'');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//公司回调\r\n");
      out.write("function callBackCompany(){\r\n");
      out.write("\t$(\"#deptid\").val(null);\r\n");
      out.write("\t$(\"#deptname\").val(null);\r\n");
      out.write("\t\r\n");
      out.write("\t//部门选择回调\r\n");
      out.write("\tcallbackDept();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//部门选择回调\r\n");
      out.write("function callbackDept(){\r\n");
      out.write("\t$(\"#postid\").val(null);\r\n");
      out.write("\t$(\"#postname\").val(null);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//岗位回调\r\n");
      out.write("function callbackpost(){\r\n");
      out.write("\tvar postid=$(\"#postid\").val();\r\n");
      out.write("\tvar quotaid=$(\"#quotaid\").val();\r\n");
      out.write("\tvar state=$(\"#state\").val();\r\n");
      out.write("\tvar budgettype=$(\"#budgettype\").val();\r\n");
      out.write("\t$.post(\"quota/checkQuotaByPostIdAndBudgettype.do\",{quotaid:quotaid,postid:postid,budgettype:budgettype,state:state}, function(data) {\r\n");
      out.write("\t\tif(data!=null&&data!=\"\"){\r\n");
      out.write("\t\t\talert(data);\r\n");
      out.write("\t\t\t$(\"#postid\").val(null);\r\n");
      out.write("\t\t\t$(\"#postname\").val(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//验证此岗位下编制是否被占\r\n");
      out.write("function callbackBudgettype(){\r\n");
      out.write("\tvar postid=$(\"#postid\").val();\r\n");
      out.write("\tvar quotaid=$(\"#quotaid\").val();\r\n");
      out.write("\tvar state=$(\"#state\").val();\r\n");
      out.write("\tvar budgettype=$(\"#budgettype\").val();\r\n");
      out.write("\t$.post(\"quota/checkQuotaByPostIdAndBudgettype.do\",{quotaid:quotaid,postid:postid,budgettype:budgettype,state:state}, function(data) {\r\n");
      out.write("\t\tif(data!=null&&data!=\"\"){\r\n");
      out.write("\t\t\talert(data);\r\n");
      out.write("\t\t\t$(\"#budgettype\").val(null);\r\n");
      out.write("\t\t\t$(\"#budgettypename\").val(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//流程处理\r\n");
      out.write("function audit(){\r\n");
      out.write("\tif(myvalidform.form()){\r\n");
      out.write("\t\t$(\"#auditDialog\").dialog({\r\n");
      out.write("\t        autoOpen: true,\r\n");
      out.write("\t        modal: true,\r\n");
      out.write("\t        model:true,\r\n");
      out.write("\t        resizable:false,\r\n");
      out.write("\t        width:500,\r\n");
      out.write("\t        buttons: {\r\n");
      out.write("\t            \"确定\": function() {\r\n");
      out.write("\t            \t$(\"#auditForm\").submit();\r\n");
      out.write("\t            },\r\n");
      out.write("\t            \"取消\": function() {\r\n");
      out.write("\t                $(this).dialog(\"close\");\r\n");
      out.write("\t            }\r\n");
      out.write("\t        },\r\n");
      out.write("\t        open:function(){\r\n");
      out.write("\t        \tif(auditForm){\r\n");
      out.write("\t        \t\t$(\"#auditForm\").validate({submitHandler:function(form) {\r\n");
      out.write("\t\t        \t    \t$(form).ajaxSubmit(function(data) {\r\n");
      out.write("\t\t        \t    \t\t alert(\"审核成功\");\r\n");
      out.write("\t\t        \t    \t\t pageState=true;\r\n");
      out.write("\t\t        \t    \t\t loadData();\r\n");
      out.write("\t\t        \t    \t\t \r\n");
      out.write("\t\t        \t    \t\t //页面保存过\r\n");
      out.write("\t        \t\t        \t window.parent.callbackPageState(pageState);\r\n");
      out.write("\t\t        \t    \t\t $(\"#auditDialog\").dialog(\"close\");\r\n");
      out.write("\t\t        \t        });\r\n");
      out.write("\t\t        \t\t}\r\n");
      out.write("\t\t        \t});\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"table\">\r\n");
      out.write("\t<div class=\"table-bar\">\r\n");
      out.write("\t\t<div class=\"table-title\">\r\n");
      out.write("\t\t\t编制基本信息\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"table-ctrl\">\r\n");
      out.write("\t\t\t<a class=\"btn\" id=\"audit\" href=\"javascript:audit();\" style=\"display:none;><i class=\"icon icon-random\"></i><span>会签审核</span></a>\t\r\n");
      out.write("\t\t\t<a class=\"btn save\" href=\"javascript:save();\" id=\"save\" ><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t<a class=\"btn\" href=\"javascript:back();\"><i class=\"icon icon-share-alt\"></i><span>返回列表</span></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"table-wrapper\">\r\n");
      out.write("\t\t<form action=\"quota/saveOrUpdateQuota.do\" method=\"post\" id=\"myForm\" class=\"form\">\r\n");
      out.write("\t\t\t<input id=\"quotaid\" name=\"quotaid\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t\t<input id=\"quotacode\" name=\"quotacode\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t\t<input id=\"state\" name=\"state\" type=\"hidden\" value=\"1\" />\r\n");
      out.write("\t\t\t<input id=\"modiuser\" name=\"modiuser\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t\t<input id=\"modimemo\" name=\"modimemo\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t\t<input id=\"moditimestamp\" name=\"moditimestamp\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"runprocess\" name=\"runprocess\" value=\"true\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 流程信息 -->\r\n");
      out.write("\t\t\t<input id=\"variables_commit\" name=\"variables['rate']\" type=\"hidden\" value=\"2\" />\r\n");
      out.write("\t\t\t<input id=\"variables_commitNum\" name=\"variables['commitNum']\" type=\"hidden\" value=\"1\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<legend>基本信息</legend>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t                <span><em class=\"red\">* </em>公司名称：</span>\r\n");
      out.write("\t\t                <input id=\"companyid\" name=\"companyid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t    <input id=\"companyname\" name=\"companyname\" class=\"{required:true} inputselectstyle\" onclick=\"chooseMyHasCompanyTree('#companyid','#companyname',callBackCompany);\"/>\r\n");
      out.write("\t\t\t\t\t    <div class=\"search-trigger\" onclick=\"chooseMyHasCompanyTree('#companyid','#companyname',callBackCompany);\"/>\r\n");
      out.write("\t\t            </li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t    <span><em class=\"red\">* </em>部门名称：</span>\r\n");
      out.write("\t\t\t\t\t    <input id=\"deptid\" name=\"deptid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t    <input id=\"deptname\" name=\"deptname\" class=\"{required:true} inputselectstyle\" onclick=\"chooseOneCompanyDeptTree('#deptid','#deptname',$('#companyid').val(),callbackDept);\"/>\r\n");
      out.write("\t\t\t\t\t    <div class=\"search-trigger\" onclick=\"chooseOneCompanyDeptTree('#deptid','#deptname',$('#companyid').val(),callbackDept);\"/>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t    <span>岗位名称：</span>\r\n");
      out.write("\t\t\t\t\t    <input id=\"postid\" name=\"postid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t    <input id=\"postname\" name=\"postname\" class=\"inputselectstyle\" onclick=\"choosePostTree('#postid','#postname',$('#deptid').val(),callbackpost);\"/>\r\n");
      out.write("\t\t\t\t\t    <div class=\"select-trigger\" onclick=\"choosePostTree('#postid','#postname',$('#deptid').val());\" />\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span><em class=\"red\">* </em>编制类别：</span>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"budgettype\" name=\"budgettype\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"budgettypename\" name=\"budgettypename\" class=\"{required:true} inputselectstyle\" onclick=\"chooseBudgettypeTree('#budgettype','#budgettypename',$('#companyid').val(),callbackBudgettype);\"/>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"search-trigger\" onclick=\"chooseBudgettypeTree('#budgettype','#budgettypename',$('#companyid').val(),callbackBudgettype);\"/>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span><em class=\"red\">* </em>编制人数：</span>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"budgetnumber\" name=\"budgetnumber\" class=\"{required:true,number:true,maxlength:40} inputstyle\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span><em class=\"red\">* </em>生效日期：</span>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"budgetdate\" name=\"budgetdate\" class=\"{required:true,dateISO:true} inputselectstyle datepicker\"/>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"date-trigger\" onclick=\"$('#budgetdate').focus();\"/>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t            <ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t    <span><em class=\"red\">* </em>变更原因：</span>\r\n");
      out.write("\t\t\t\t\t    <textarea id=\"memo\" name=\"memo\" rows=\"5\" style=\"width:575px;\" class=\"{required:true,maxlength:500} areastyle\" ></textarea>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("      \t\t</form>\r\n");
      out.write("      \t\t<div class=\"form\" id=\"myProcess\">\r\n");
      out.write("    \t\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("      \t\t<br>\r\n");
      out.write("      \t\t<br>\r\n");
      out.write("      \t\t<br>\r\n");
      out.write("      \t\t<br>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 审核信息 -->\r\n");
      out.write("<div id=\"auditDialog\" title=\"审核信息\" style=\"display:none;\">\r\n");
      out.write("    <form action=\"quota/completeTask.do\" id=\"auditForm\" class=\"form\" method=\"post\">\r\n");
      out.write("    \t<input type=\"hidden\" id=\"taskid\" name=\"taskid\" value=\"\"/>\r\n");
      out.write("        <ul>\r\n");
      out.write("        \t<li>\r\n");
      out.write("        \t\t<span>&nbsp;</span>\r\n");
      out.write("        \t\t<label>\r\n");
      out.write("        \t\t\t<input type=\"radio\" name=\"commit\" class=\"checkboxstyle\" value=\"1\" checked=\"true\"/>同意\r\n");
      out.write("        \t\t</label>\r\n");
      out.write("        \t\t<label>\r\n");
      out.write("        \t\t\t<input type=\"radio\" name=\"commit\" class=\"checkboxstyle\" value=\"0\"/>不同意\r\n");
      out.write("        \t\t</label>\r\n");
      out.write("        \t</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>审核意见：</span>\r\n");
      out.write("\t\t\t\t<textarea name=\"result\" rows=\"8\" style=\"width:280px;\" class=\"{required:true,maxlength:500} areastyle\"></textarea>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
