package org.apache.jsp.pages.recruitprogram;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>招聘计划管理</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\" />\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\" />\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"skins/css/style.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"skins/css/form.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/jquery-ui-1.8.15.custom.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeStyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeIcons.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/gt_grid.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/default/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/green/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/mac/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/china/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/vista/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/calendar/calendar-blue.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/public.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-ui-1.8.5.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/tree/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/lib/jquery.metadata.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-en.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-setup.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_grid_all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_msg_cn.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"pages/tree.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var tid='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.id}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t//列表加载\r\n");
      out.write("    loadGrid();\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("  //日期\r\n");
      out.write("    $(\".datepicker\").datepicker({\r\n");
      out.write("        dateFormat: 'yy-mm-dd',\r\n");
      out.write("       \tbeforeShow: function(input, inst) {\r\n");
      out.write("   \t\t\tif($(input).attr(\"readonly\"))\r\n");
      out.write("   \t\t\t\tinst.inline=true;\r\n");
      out.write("   \t\t}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("  \t//关闭等待层\r\n");
      out.write("    if(window.parent.hidenLoading)\r\n");
      out.write("    \twindow.parent.hidenLoading();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//搜索\r\n");
      out.write("var searchForm=null;\r\n");
      out.write("function searchGrid(){\r\n");
      out.write("\t$(\"#search\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:470,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\":function(){\r\n");
      out.write("\t\t\t\tif(searchForm.form()){\r\n");
      out.write("\t\t\t\t\tmygrid.reload();\r\n");
      out.write("\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"重置\":function(){\r\n");
      out.write("\t\t\t\t$(\"#searchForm\").clearForm();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"关闭\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\topen:function(){\r\n");
      out.write("\t\t\t//校验\r\n");
      out.write("\t\t\tif(searchForm==null)\r\n");
      out.write("\t\t\t\tsearchForm=$(\"#searchForm\").validate();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//参数设置\r\n");
      out.write("var pam=null;\r\n");
      out.write("function initPagePam(){\r\n");
      out.write("\tpam={};\r\n");
      out.write("\tpam.expAll=0;\r\n");
      out.write("\tpam.companyid=$(\"#companyid\").val();\r\n");
      out.write("\tpam.deptid=$(\"#deptid\").val();\r\n");
      out.write("\tpam.postname=$(\"#postname\").val();\r\n");
      out.write("\tpam.quotaid=tid;\r\n");
      out.write("\tpam.rankid=$(\"#rankid\").val();\r\n");
      out.write("\tpam.myvalid=$(\"#myvalid\").attr(\"checked\")?1:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//导出\r\n");
      out.write("function expGrid(){\r\n");
      out.write("\t$(\"#dialog_exp\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tmodel:true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:400,\r\n");
      out.write("\t\theight:130,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\tmygrid.exportGrid('xls');\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tclose: function() {\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//一级部门选择回调\r\n");
      out.write("function callbackDept1(){\r\n");
      out.write("\t$(\"#t_postid\").val(null);\r\n");
      out.write("\t$(\"#t_postname\").val(null);\r\n");
      out.write("\t\r\n");
      out.write("\tcallbackDept2();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//二级部门选择回调\r\n");
      out.write("function callbackDept2(){\r\n");
      out.write("\t$(\"#t_postid\").val(null);\r\n");
      out.write("\t$(\"#t_postname\").val(null);\r\n");
      out.write("\t\r\n");
      out.write("\tcallbackPost();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//岗位回写\r\n");
      out.write("function callbackPost(){\r\n");
      out.write("\t$(\"#t_quotaid\").val(null);\r\n");
      out.write("\t$(\"#t_quotaname\").val(null);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function callbackDept(){\r\n");
      out.write("\t$(\"#postid\").val(null);\r\n");
      out.write("\t$(\"#postname\").val(null);\r\n");
      out.write("\t$(\"#quotaid\").val(null);\r\n");
      out.write("\t$(\"#quotaname\").val(null);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//公司回调\r\n");
      out.write("function callBackCompany(){\r\n");
      out.write("\t$(\"#deptid\").val(null);\r\n");
      out.write("\t$(\"#deptname\").val(null);\r\n");
      out.write("\t\r\n");
      out.write("\t//部门选择回调\r\n");
      out.write("\tcallbackDept();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//删除\r\n");
      out.write("function remove(){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tvar cords=mygrid.getSelectedRecords();\r\n");
      out.write("\tfor(var i=0;i<cords.length;i++){\r\n");
      out.write("\t\tarray.push(cords[i].recruitprogramguid);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(array.length<=0){\r\n");
      out.write("\t\talert('请选择要删除的数据！');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!confirm('确认要删除选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.post(\"recruitprogram/delRecruitprogramById.do\",{ids:array.toString()}, function() {\r\n");
      out.write("\t\tmygrid.reload();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//审核生效\r\n");
      out.write("function auditValid(state){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tvar cords=mygrid.getSelectedRecords();\r\n");
      out.write("\tfor(var i=0;i<cords.length;i++){\r\n");
      out.write("\t\tvar obj=cords[i];\r\n");
      out.write("\t\tif(obj.state=-1&&obj.state!=0&&obj.state!=2&&(obj.interfacecode==null||obj.interfacecode==''))\r\n");
      out.write("\t\t\tarray.push(obj.recruitprogramguid);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(array.length<=0){\r\n");
      out.write("\t\talert('请选择要生效且不用细分的数据！');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.post(\"recruitprogram/updateRecruitprogramStateById.do\",{ids:array.toString(),state:state}, function() {\r\n");
      out.write("\t\tmygrid.reload();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//细分操作\r\n");
      out.write("var auditForm=null;\r\n");
      out.write("function audit(id){\r\n");
      out.write("\t$(\"#auditWindow\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:470,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\":function(){\r\n");
      out.write("\t\t\t\tif(auditForm.form()){\r\n");
      out.write("\t\t\t\t\t$(\"#t_runprocess\").val(true);\r\n");
      out.write("\t\t\t\t\tsave();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\topen:function(){\r\n");
      out.write("\t\t\t//重置表单\r\n");
      out.write("\t\t\t$(\"#auditForm\").clearForm();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tloadData(id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t //加载表单验证\r\n");
      out.write("\t\t\tif(auditForm==null)\r\n");
      out.write("\t\t\t\tauditForm=$(\"#auditForm\").validate({submitHandler:function(form) {\r\n");
      out.write("\t\t\t    \t$(form).ajaxSubmit(function(data) {\r\n");
      out.write("\t\t\t    \t\talert(\"操作成功!\");\r\n");
      out.write("\t\t\t    \t\tmygrid.reload();\r\n");
      out.write("\t\t\t    \t\t$(\"#auditWindow\").dialog(\"close\");\r\n");
      out.write("\t\t\t        });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//保存\r\n");
      out.write("function save(){\r\n");
      out.write("\tvar id=$(\"#t_recruitprogramguid\").val();\r\n");
      out.write("\tvar remainnum=$(\"#remainnum\").val();\r\n");
      out.write("\t\r\n");
      out.write("\tif(remainnum!=null&&remainnum!=''){\r\n");
      out.write("\t\t$.getJSON(\"recruitprogram/getRecruitprogramById.do\", {id:id,taskid:null}, function(data) {\r\n");
      out.write("\t\t\tif(data!=null){\r\n");
      out.write("\t\t\t\tif(remainnum>data.postnum||remainnum<=0){\r\n");
      out.write("\t\t\t\t\talert(\"细分人数输入有误,请重新输入!\");\r\n");
      out.write("\t\t\t\t\t$(\"#remainnum\").val(null);\r\n");
      out.write("\t\t\t\t\t$(\"#remainnum\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}else\r\n");
      out.write("\t\t\t\t\t$('#auditForm').submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//取数据\r\n");
      out.write("function loadData(id) {\r\n");
      out.write("\tif(id!=null&&id!=''&&id!='null')\r\n");
      out.write("\t\t$.getJSON(\"recruitprogram/getRecruitprogramById.do\", {id:id}, function(data) {\r\n");
      out.write("\t\t\tif(data!=null){\r\n");
      out.write("\t\t\t\tfor(var key in data){\r\n");
      out.write("\t\t\t\t\tif($('#auditForm #t_'+key)){\r\n");
      out.write("\t\t\t\t\t\t$('#auditForm #t_'+key).val(data[key]);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//切换视图\r\n");
      out.write("function convertView(url){\r\n");
      out.write("\tif ($(\".sort\").css(\"display\")!=\"none\") {\r\n");
      out.write("\t\t$(\".sort\").hide();\r\n");
      out.write("\t\t$(\"#detail\").show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#detail\").attr(\"src\",url);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$(\"#detail\").height(0);\r\n");
      out.write("\t\t$(\"#detail\").removeAttr(\"src\");\r\n");
      out.write("\t\t$(\".sort\").show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//计算高度\r\n");
      out.write("\t\t_autoHeight();\r\n");
      out.write("\t\tif(url==null)\r\n");
      out.write("\t\t\tmygrid.reload();\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//校验所输入的数字要小于招聘人数\r\n");
      out.write("function checkRemainNum(){\r\n");
      out.write("\tvar id=$(\"#t_recruitprogramguid\").val();\r\n");
      out.write("\tvar remainnum=$(\"#remainnum\").val();\r\n");
      out.write("\t\r\n");
      out.write("\tif(remainnum!=null&&remainnum!=''){\r\n");
      out.write("\t\t$.getJSON(\"recruitprogram/getRecruitprogramById.do\", {id:id,taskid:null}, function(data) {\r\n");
      out.write("\t\t\tif(data!=null){\r\n");
      out.write("\t\t\t\tif(remainnum>data.postnum||remainnum<=0){\r\n");
      out.write("\t\t\t\t\talert(\"细分人数输入有误,请重新输入!\");\r\n");
      out.write("\t\t\t\t\t$(\"#remainnum\").val(null);\r\n");
      out.write("\t\t\t\t\t$(\"#remainnum\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//取消\r\n");
      out.write("function goout(id,interfacecode){\r\n");
      out.write("\tif(!confirm('确认要取消细分数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.getJSON(\"recruitprogram/cancelRecruitprogramByIdAndInterfacecode.do\", {id:id,interfacecode:interfacecode}, function() {\r\n");
      out.write("\t\talert(\"操作成功!\");\r\n");
      out.write("\t\tmygrid.reload();\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\t\r\n");
      out.write("var mygrid=null;\r\n");
      out.write("function loadGrid(){\r\n");
      out.write("\tvar size=getGridSize();\r\n");
      out.write("\tvar grid_demo_id = \"myGrid1\";\r\n");
      out.write("\tvar dsOption= {\r\n");
      out.write("\t\t\tfields :[\r\n");
      out.write("\t\t\t\t{name : 'recruitprogramguid'},\r\n");
      out.write("\t\t\t\t{name : 'recruitprogramcode'},\r\n");
      out.write("\t\t\t\t{name : 'quotaid'},\r\n");
      out.write("\t\t\t\t{name : 'companyid'},\r\n");
      out.write("\t\t\t\t{name : 'deptid'},\r\n");
      out.write("\t\t\t\t{name : 'postid'},\r\n");
      out.write("\t\t\t\t{name : 'rankid'},\r\n");
      out.write("\t\t\t\t{name : 'applydate'},\r\n");
      out.write("\t\t\t\t{name : 'hillockdate'},\r\n");
      out.write("\t\t\t\t{name : 'postnum'},\r\n");
      out.write("\t\t\t\t{name : 'state'},\r\n");
      out.write("\t\t\t\t{name : 'processinstanceid'},\r\n");
      out.write("\t\t\t\t{name : 'memo'},\r\n");
      out.write("\t\t\t\t{name : 'modiuser'},\r\n");
      out.write("\t\t\t\t{name : 'moditimestamp'},\r\n");
      out.write("\t\t\t\t{name : 'modimemo'}\r\n");
      out.write("\t\t\t]\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar colsOption = [\r\n");
      out.write("\t\t\t{id: '选择' ,isCheckColumn : true, editable:false,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'taskid' , header: \"操作\" , width :80 ,headAlign:'center',align:'center',renderer:function(value ,record,colObj,grid,colNo,rowNo){\r\n");
      out.write("\t\t\t\tvar htm='&nbsp;';\r\n");
      out.write("\t\t\t\tif(record.state==2&&record.assignee=='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("'){\r\n");
      out.write("\t\t\t\t\thtm+='<a href=\"javascript:convertView(\\'recruitprogram.do?page=tab&id='+record.recruitprogramguid+'&taskid='+record.taskid+'\\')\">审核</a>';\r\n");
      out.write("\t\t\t\t\thtm+='&nbsp;';\r\n");
      out.write("\t\t\t\t\thtm+='&nbsp;';\r\n");
      out.write("\t\t\t\t\t//return '<a href=\"javascript:convertView(\\'recruitprogram.do?page=tab&id='+record.recruitprogramguid+'&taskid='+record.taskid+'\\')\">审核</a>';\r\n");
      out.write("\t\t\t\t}else if(record.state==-1&&record.interfacecode!=null&&record.interfacecode!=''){\r\n");
      out.write("\t\t\t\t\thtm+='<a href=\"javascript:audit(\\''+record.recruitprogramguid+'\\')\">';\r\n");
      out.write("\t\t\t\t\thtm+='细分';\r\n");
      out.write("\t\t\t\t\thtm+='</a>';\r\n");
      out.write("\t\t\t\t\thtm+='&nbsp;';\r\n");
      out.write("\t\t\t\t\thtm+='&nbsp;';\r\n");
      out.write("\t\t\t\t}else if(record.state==1&&record.interfacecode!=null&&record.interfacecode!=''&&record.interfacecode.length!=32&&record.modiuser!=null&&record.modiuser!=''){\r\n");
      out.write("\t\t\t\t\thtm+='<a href=\"javascript:goout(\\''+record.recruitprogramguid+'\\',\\''+record.interfacecode+'\\')\">';\r\n");
      out.write("\t\t\t\t\thtm+='取消';\r\n");
      out.write("\t\t\t\t\thtm+='</a>';\r\n");
      out.write("\t\t\t\t\thtm+='&nbsp;';\r\n");
      out.write("\t\t\t\t\thtm+='&nbsp;';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn htm;\r\n");
      out.write("\t\t\t}},\r\n");
      out.write("\t\t\t{id: 'statename' , header: \"状态\" , width :60 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'recruitprogramcode' , header: \"计划编号\" , width :120,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'companyname' , header: \"公司名称\" , width :180,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'deptname' , header: \"部门名称\" , width :150,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'postname' , header: \"岗位名称\" , width :120,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'rankname' , header: \"职级\" , width :100,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'applydate' , header: \"申请时间\" , width :120,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'quotaname' , header: \"编制类型\" , width :120,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'quotacode' , header: \"编制编号\" , width :120,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'employednumber' , header: \"占编人数\" , width :60,headAlign:'center',align:'left',number:true},\r\n");
      out.write("\t\t\t{id: 'quotanumber' , header: \"编制人数\" , width :60,headAlign:'center',align:'left',number:true},\r\n");
      out.write("\t\t\t{id: 'interviewnumber' , header: \"面试通过人数\" , width :100,headAlign:'center',align:'left',number:true},\r\n");
      out.write("\t\t\t{id: 'vacancynumber' , header: \"缺编人数\" , width :60,headAlign:'center',align:'left',number:true},\r\n");
      out.write("\t\t\t{id: 'postnum' , header: \"招聘人数/可细分人数\" , width :150,headAlign:'center',align:'left',number:true},\r\n");
      out.write("\t\t\t{id: 'hillockdate' , header: \"计划到岗时间\" , width :120,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'memo' , header: \"备注\" , width :250 ,headAlign:'center',align:'left'}\r\n");
      out.write("\t\t];\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar gridOption={\r\n");
      out.write("\t\tid : grid_demo_id,\r\n");
      out.write("\t\tloadURL :'recruitprogram/searchRecruitprogram.do',\r\n");
      out.write("\t\tbeforeLoad:function(reqParam){\r\n");
      out.write("\t\t\tinitPagePam();\r\n");
      out.write("\t\t\treqParam['parameters']=pam;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texportURL : 'recruitprogram/searchRecruitprogram.do?export=true',\r\n");
      out.write("\t\tbeforeExport:function(){\r\n");
      out.write("\t\t\tinitPagePam();\r\n");
      out.write("\t\t\tpam.expAll=1;\r\n");
      out.write("\t\t\tmygrid.parameters=pam;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texportFileName : '招聘计划管理.xls',\r\n");
      out.write("\t\twidth: \"99.8%\",//\"100%\", // 700,\r\n");
      out.write("\t\theight: \"100%\",  //\"100%\", // 330,\r\n");
      out.write("\t\tcontainer : 'gridbox', \r\n");
      out.write("\t\tpageSizeList : [size,size*2,size*4,size*6,size*8,size*10],\r\n");
      out.write("\t\tstripeRows: false,\r\n");
      out.write("\t\tremoteFilter:true,\r\n");
      out.write("\t\tshowIndexColumn:true,\r\n");
      out.write("\t\tselectRowByCheck:true,\r\n");
      out.write("\t\treplaceContainer : true,\r\n");
      out.write("\t\tdataset : dsOption ,\r\n");
      out.write("\t\tcolumns : colsOption,\r\n");
      out.write("\t\ttoolbarContent : 'nav | pagesize  state',\r\n");
      out.write("\t\tpageSize:size,\r\n");
      out.write("\t\tskin:getGridSkin(),\r\n");
      out.write("\t\tloadResponseHandler:function(response,requestParameter){\r\n");
      out.write("\t\t\tvar obj = jQuery.parseJSON(response.text);\r\n");
      out.write("\t\t\tvar page=obj.pageInfo;\r\n");
      out.write("\t\t\tvar hg=(page.pageSize+1)*33+50;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tmygrid.setSize('99.9%',hg);\r\n");
      out.write("\t\t\tpageResize(hg);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tcustomRowAttribute : function(record,rn,grid){\r\n");
      out.write("\t\t\t//if(record.state==1&&record.interfacecode!=null&&record.interfacecode!=''&&record.interfacecode.length!=32&&record.modiuser!=null&&record.modiuser!=''){\r\n");
      out.write("\t\t\t\t//return 'style=\"font-weight:bold;background:#FFFACD;\"';\r\n");
      out.write("\t\t\t//}\r\n");
      out.write("\t\t\tif(record.employednumber>(record.quotanumber+record.interviewnumber)){\r\n");
      out.write("\t\t\t\t//return 'style=\"font-weight:bold;background:#F08080;\"';\r\n");
      out.write("\t\t\t\treturn 'style=\"font-weight:bold;background:#FFFACD;\"';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tonDblClickCell:function(value, record , cell, row, colNO, rowNO,columnObj,grid){\r\n");
      out.write("\t\t\tif(colNO!=0){\r\n");
      out.write("\t\t\t\tconvertView('recruitprogram.do?page=tab&id='+record.recruitprogramguid+'&taskid='+record.taskid+'&interfacecode='+record.interfacecode);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tmygrid=new Sigma.Grid( gridOption );\r\n");
      out.write("\tSigma.Util.onLoad( Sigma.Grid.render(mygrid) );\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function pageResize(height){\r\n");
      out.write("\t$(\"#myTable\").height(height);\r\n");
      out.write("\t//计算高度\r\n");
      out.write("\t_autoHeight();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sort\">\r\n");
      out.write("\t<div class=\"sort-title\">\r\n");
      out.write("\t\t<h3>招聘计划管理</h3>\r\n");
      out.write("\t\t<div class=\"title-ctrl\">\r\n");
      out.write("\t\t\t<a class=\"btn-ctrl\" href=\"javascript:chevronUpDown('.sort-cont',false);\"><i class=\"icon icon-chevron-up\"></i></a>\r\n");
      out.write("\t\t\t<a class=\"btn-ctrl\" href=\"javascript:chevronUpDown('.sort-cont',true);\"><i class=\"icon icon-chevron-down\"></i></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"sort-cont sort-table\">\r\n");
      out.write("\t\t<div class=\"table\">\r\n");
      out.write("\t\t\t<div class=\"table-bar\">\r\n");
      out.write("\t\t\t\t<div class=\"table-title\">\r\n");
      out.write("\t\t\t\t\t表格名称\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-ctrl\">\r\n");
      out.write("\t\t\t\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"myvalid\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"myvalid\" type=\"checkbox\" class=\"checkboxstyle\" onclick=\"mygrid.reload();\" checked=\"true\"/> 不显示失效的信息\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn\" href=\"javascript:searchGrid();\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${search?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-search\"></i><span>搜索</span></a>\r\n");
      out.write("\t\t\t   \t\t<a class=\"btn\" href=\"javascript:convertView('recruitprogram.do?page=import');\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imp?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-qrcode\"></i><span>导入</span></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn\" href=\"javascript:expGrid();\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exp?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-download\"></i><span>导出</span></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn\"  href=\"javascript:auditValid(3);\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${valid?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-stop\"></i><span>生效</span></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn\" href=\"javascript:convertView('recruitprogram.do?page=tab');\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${add?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-plus\"></i><span>新增</span></a>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn\" href=\"javascript:remove();\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${del?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-remove\"></i><span>删除</span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"table-wrapper\">\r\n");
      out.write("\t\t\t\t<div id=\"myTable\" style=\"height:550px;margin:5px auto;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"gridbox\" ></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t<iframe id=\"detail\" name=\"detail\" width=\"100%\" height=\"100%\"frameborder=\"0\" src=\"\" scrolling=\"no\" style=\"display: none;\"></iframe>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 搜索 -->\r\n");
      out.write("<div id=\"search\" title=\"搜索条件设置\" style=\"display: none;\">\r\n");
      out.write("\t<form action=\"\" id=\"searchForm\" class=\"form\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("                <span>公司名称：</span>\r\n");
      out.write("                <input id=\"companyid\" name=\"companyid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"companyname\" name=\"companyname\" class=\"inputselectstyle\" onclick=\"chooseMyHasCompanyTree('#companyid','#companyname',callBackCompany);\"/>\r\n");
      out.write("\t\t\t    <div class=\"search-trigger\" onclick=\"chooseMyHasCompanyTree('#companyid','#companyname',callBackCompany);\"/>\r\n");
      out.write("            </li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t    <span>部门名称：</span>\r\n");
      out.write("\t\t\t    <input id=\"deptid\" name=\"deptid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"deptname\" name=\"deptname\" class=\"inputselectstyle\" onclick=\"chooseOneCompanyMultipleDeptTree('#deptid','#deptname',$('#companyid').val());\"/>\r\n");
      out.write("\t\t\t    <div class=\"search-trigger\" onclick=\"chooseOneCompanyMultipleDeptTree('#deptid','#deptname',$('#companyid').val());\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span>岗位名称：</span>\r\n");
      out.write("\t\t\t\t<input id=\"postname\" name=\"postname\" class=\"inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t    <span>职级：</span>\r\n");
      out.write("\t\t\t     <input id=\"rankid\" name=\"position.rankid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"rankname\" name=\"position.rankname\" class=\"inputselectstyle\" onclick=\"chooseRankTree('#rankid','#rankname',$('#companyid').val());\"/>\r\n");
      out.write("\t\t\t    <div class=\"select-trigger\" onclick=\"chooseRankTree('#rankid','#rankname',$('#companyid').val());\" />\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 导出 -->\r\n");
      out.write("<div id=\"dialog_exp\" style=\"display: none;\" title=\"数据导出\">\r\n");
      out.write("\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\"\r\n");
      out.write("\t\tcellspacing=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>&nbsp; &nbsp; &nbsp; &nbsp; <label for=\"xls1\"> \r\n");
      out.write("\t\t\t\t<input id=\"xls1\" type=\"radio\" name=\"xls\" value=\"0\" checked=\"true\" class=\"checkboxstyle\" />导出本页\r\n");
      out.write("\t\t\t</label> &nbsp; &nbsp; \r\n");
      out.write("\t\t\t<label for=\"xls2\"> \r\n");
      out.write("\t\t\t\t<input id=\"xls2\" type=\"radio\" name=\"xls\" value=\"1\" class=\"checkboxstyle\" />全部导出\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 审核 -->\r\n");
      out.write("<div id=\"auditWindow\"  title=\"OA审核\" style=\"display:none;\">\r\n");
      out.write("\t<form action=\"recruitprogram/UpdateRecruitProgram.do\" id=\"auditForm\"  class=\"form\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"t_recruitprogramguid\" name=\"recruitprogramguid\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"t_interfacecode\" name=\"interfacecode\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"t_recruitprogramcode\" name=\"recruitprogramcode\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"t_applydate\" name=\"applydate\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"t_state\" name=\"state\" value=\"\" />\r\n");
      out.write("\t\t<input id=\"t_modiuser\" name=\"modiuser\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("\t\t<input id=\"t_moditimestamp\" name=\"moditimestamp\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"t_runprocess\" name=\"runprocess\" value=\"true\" />\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"t_processinstanceid\" name=\"processinstanceid\" value=\"\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 流程信息 -->\r\n");
      out.write("\t\t<input id=\"t_variables_commit\" name=\"variables['rate']\" type=\"hidden\" value=\"2\" />\r\n");
      out.write("\t\t<input id=\"t_variables_commitNum\" name=\"variables['commitNum']\" type=\"hidden\" value=1 />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("                <span><em class=\"red\">* </em>公司名称：</span>\r\n");
      out.write("                <input id=\"t_companyid\" name=\"companyid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"t_companyname\" name=\"companyname\" class=\"{required:true} inputstyle disabled\" readonly=\"true\" />\r\n");
      out.write("            </li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t    <span><em class=\"red\">* </em>一级部门名称：</span>\r\n");
      out.write("\t\t\t    <input id=\"t_deptid\" name=\"deptid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"t_deptname\" name=\"deptname\" class=\"{required:true} inputselectstyle \"  onclick=\"chooseOneCompanyDeptTree('#t_deptid','#t_deptname',$('#t_companyid').val(),callbackDept1);\"/>\r\n");
      out.write("\t\t\t    <div class=\"search-trigger\" onclick=\"chooseOneCompanyDeptTree('#t_deptid','#t_deptname',$('#t_companyid').val(),callbackDept1);\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t    <span>二级部门名称：</span>\r\n");
      out.write("\t\t\t    <input id=\"t_pdeptid\" name=\"pdeptid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"t_pdeptname\" name=\"pdeptname\" class=\"inputselectstyle\" onclick=\"choosePDeptTree('#t_pdeptid','#t_pdeptname',$('#t_deptid').val(),callbackDept2);\"/>\r\n");
      out.write("\t\t\t    <div class=\"search-trigger\" onclick=\"choosePDeptTree('#t_pdeptid','#t_pdeptname',$('#t_deptid').val(),callbackDept2);\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>岗位：</span>\r\n");
      out.write("\t\t\t\t<input id=\"t_postid\" name=\"postid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t    <input id=\"t_postname\" name=\"postname\" class=\"{required:true} inputselectstyle\" onclick=\"choosePostTree('#t_postid','#t_postname',$('#t_pdeptid').val()==''?$('#t_deptid').val():$('#t_pdeptid').val(),callbackPost);\"/>\r\n");
      out.write("\t\t\t    <div class=\"select-trigger\" onclick=\"choosePostTree('#t_postid','#t_postname',$('#t_pdeptid').val()==''?$('#t_deptid').val():$('#t_pdeptid').val(),callbackPost);\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>编制类型：</span>\r\n");
      out.write("\t\t\t\t<input id=\"t_quotaid\" name=\"quotaid\" type=\"hidden\"/>\r\n");
      out.write("\t\t\t\t<input id=\"t_quotaname\" name=\"quotaname\" class=\"{required:true} inputselectstyle\"  <div class=\"search-trigger\" onclick=\"chooseQuotaTree('#t_quotaid','#t_quotaname',$('#t_postid').val());\"/>\r\n");
      out.write("\t\t    \t<div class=\"search-trigger\" onclick=\"chooseQuotaTree('#t_quotaid','#t_quotaname',$('#t_postid').val());\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>职级：</span>\r\n");
      out.write("\t\t\t\t<input id=\"t_rankid\" name=\"rankid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t<input id=\"t_rankname\" name=\"rankname\" class=\"{required:true} inputselectstyle\"  onclick=\"chooseRankTree('#t_rankid','#t_rankname',$('#t_companyid').val());\"/>\r\n");
      out.write("\t\t\t\t<div class=\"search-trigger\" onclick=\"chooseRankTree('#t_rankid','#t_rankname',$('#t_companyid').val());\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>计划到岗时间：</span>\r\n");
      out.write("\t\t\t\t<input id=\"t_hillockdate\" name=\"hillockdate\" class=\"{required:true,dateISO:true}  inputselectstyle datepicker\"/>\r\n");
      out.write("\t\t    \t<div class=\"date-trigger\" onclick=\"$('#t_hillockdate').focus();\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>细分人数：</span>\r\n");
      out.write("\t\t\t\t<input id=\"remainnum\" name=\"remainnum\" class=\"{required:true,number:true,maxlength:38}  inputstyle\"  onblur=\"checkRemainNum();\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
