package org.apache.jsp.pages.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class function_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>菜单管理</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\"/>    \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/style.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/form.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/jquery-ui-1.8.15.custom.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeStyle.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeIcons.css\"/>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.json-2.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/public.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.layout.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-ui-1.8.5.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/tree/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/lib/jquery.metadata.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t//tab页\r\n");
      out.write("\tloadTab();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//加载布局\r\n");
      out.write("\t$('#myContent').layout({\r\n");
      out.write("        west: {size:\"300\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("  \t//加载树\r\n");
      out.write("    buildFunctionTree();\r\n");
      out.write("    \r\n");
      out.write("  //加载表单验证\r\n");
      out.write("    $(\"#myForm\").validate();\r\n");
      out.write("    $('#myForm').ajaxForm(function(data) {\r\n");
      out.write("        //节点处理\r\n");
      out.write("    \tvar nameValue=data.labelname;\r\n");
      out.write("    \t\r\n");
      out.write("    \tif(add){//新增\r\n");
      out.write("    \t\tvar newNode = {id:data.funid, name:nameValue,iconSkin:'fun'};\r\n");
      out.write("       \t\tzTree.addNodes(selectNode, newNode);\r\n");
      out.write("        }else{\r\n");
      out.write("        \tselectNode.name = nameValue;\r\n");
      out.write("        \tselectNode.iconSkin='fun';\r\n");
      out.write("   \t\t\tzTree.updateNode(selectNode);\r\n");
      out.write("   \t\t\tzTree.selectNode(selectNode);\r\n");
      out.write("        }\r\n");
      out.write("    \tadd=false;\r\n");
      out.write("    \t//不可编辑\r\n");
      out.write("    \tformDisabled(true);\r\n");
      out.write("    \t//取消状态\r\n");
      out.write("    \tonCancel();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("  //把表单置为不可编辑\r\n");
      out.write("    formDisabled(true);\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  //关闭等待层\r\n");
      out.write("    if(window.parent.hidenLoading)\r\n");
      out.write("    \twindow.parent.hidenLoading();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//tab页\r\n");
      out.write("var tabIndex=0;\r\n");
      out.write("function loadTab(){\r\n");
      out.write("\t$(\"#mytab\").tabs({\r\n");
      out.write("    \tselect: function(event, ui) {\r\n");
      out.write("    \t\ttabIndex=ui.index;\r\n");
      out.write("    \t\t$(\".gruop_hidden\").hide();\r\n");
      out.write("    \t\t$(\"#group\"+tabIndex).show();\r\n");
      out.write("    \t\t$(\"#tab\"+tabIndex).show();\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t//崗位樹\r\n");
      out.write("\t\t\tif(tabIndex==1){\r\n");
      out.write("\t\t\t\tbuildRoleTree();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//树\r\n");
      out.write("var zTree;\r\n");
      out.write("//选中节点\r\n");
      out.write("var selectNode=null;\r\n");
      out.write("function buildFunctionTree(){\r\n");
      out.write("\t//配置\r\n");
      out.write("\tvar setting = {callback:{beforeClick: function(treeId, treeNode) {\r\n");
      out.write("\t\t\tselectNode=treeNode;\r\n");
      out.write("    \t\tformDisabled(true);\r\n");
      out.write("    \t\t//出现按钮组一\r\n");
      out.write("    \t\t$('#b1').show();\r\n");
      out.write("    \t\t$('#b2').hide();\r\n");
      out.write("    \t\t//控制新增编辑\r\n");
      out.write("    \t\tif(treeNode.id==null){\r\n");
      out.write("    \t\t\t$('#new').show();\r\n");
      out.write("    \t\t\t$('#edit').hide();\r\n");
      out.write("    \t\t\t$('#del').hide();\r\n");
      out.write("    \t\t}else{\r\n");
      out.write("    \t\t\t$('#edit').show();\r\n");
      out.write("    \t\t\t$('#new').show();\r\n");
      out.write("    \t\t\t$('#del').show();\r\n");
      out.write("\r\n");
      out.write("    \t\t\t//加载数据\r\n");
      out.write("    \t\t\tloadData(treeNode.id);\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("  \t}};\r\n");
      out.write("\t\r\n");
      out.write("    $.getJSON(\"system/buildFunctionTree.do\", function(tdata) {\r\n");
      out.write("    \tzTree = $.fn.zTree.init($(\"#tree\"),setting, tdata);\r\n");
      out.write("    \t\r\n");
      out.write("    \t$('#b1').hide();\r\n");
      out.write("    \t$('#b2').hide();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//加载数据\r\n");
      out.write("function loadData(tid){\r\n");
      out.write("\t$(\"#myForm\").clearForm();\r\n");
      out.write("\tif(tid!=null&&tid!=''&&tid!='null')\r\n");
      out.write("\t\t$.getJSON(\"system/getFunctionById.do\", {id:tid}, function(data) {\r\n");
      out.write("\t\t\tif(data!=null){\r\n");
      out.write("\t\t\t\tfor (var key in data) {\r\n");
      out.write("\t\t\t        var el = $('#' + key);\r\n");
      out.write("\t\t\t        if(key=='funtype')\r\n");
      out.write("\t\t\t        \t$('#' + key+data[key]).attr(\"checked\",true);\r\n");
      out.write("\t\t\t        if(el) \r\n");
      out.write("\t\t\t            el.val(data[key]);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//崗位樹\r\n");
      out.write("\t\t\t\tif(tabIndex==1)\r\n");
      out.write("\t    \t\t\tbuildRoleTree();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//新增\r\n");
      out.write("var add=false;\r\n");
      out.write("function addNode(){\r\n");
      out.write("\t$('#b1').hide();\r\n");
      out.write("\t$('#b2').show();\r\n");
      out.write("\t$(\"#myForm\").clearForm();\r\n");
      out.write("\tformDisabled(false);\r\n");
      out.write("\tadd=true;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//设置上级\r\n");
      out.write("\tif(selectNode!=null){\r\n");
      out.write("\t\tvar funpid=selectNode.id;\r\n");
      out.write("\t\tif(funpid!=null&&funpid!=''){\r\n");
      out.write("\t\t\t$('#funpid').val(funpid);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#funtype1\").attr(\"checked\",true);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//编辑\r\n");
      out.write("function editNode(){\r\n");
      out.write("\t$('#b1').hide();\r\n");
      out.write("\t$('#b2').show();\r\n");
      out.write("\tformDisabled(false);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//保存\r\n");
      out.write("function save(){\r\n");
      out.write("\t$('#myForm').submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//取消\r\n");
      out.write("function onCancel(){\r\n");
      out.write("\t//取数据\r\n");
      out.write("\tif(selectNode!=null)\r\n");
      out.write("\t\tloadData(selectNode.id);\r\n");
      out.write("\t\r\n");
      out.write("\tformDisabled(true);\r\n");
      out.write("\t$('#b1').show();\r\n");
      out.write("\t$('#b2').hide();\r\n");
      out.write("\t\r\n");
      out.write("\t$('#del').show();\r\n");
      out.write("\t$('#edit').show();\r\n");
      out.write("\t$('#new').show();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//删除\r\n");
      out.write("function delNode(){\r\n");
      out.write("\tif(!confirm('确认要删除吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.post(\"system/delFunctionById.do\",{id:selectNode.id}, function() {\r\n");
      out.write("\t\tzTree.removeNode(selectNode);\r\n");
      out.write("\t\t$(\"#myForm\").clearForm();\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t$('#b1').show();\r\n");
      out.write("\t\t$('#b2').hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#del').hide();\r\n");
      out.write("\t\t$('#edit').hide();\r\n");
      out.write("\t\t$('#new').hide();\r\n");
      out.write(" \t\tformDisabled(true);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//崗位树\r\n");
      out.write("var roleTree;\r\n");
      out.write("function buildRoleTree(){\r\n");
      out.write("\tvar funid= $(\"#funid\").val();\r\n");
      out.write("\tif(funid==null||funid=='')\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#roleTree\").html(null);\r\n");
      out.write("    $.getJSON(\"system/buildFuntionRoleCheckTree.do\",{funid:funid}, function(tdata) {\r\n");
      out.write("    \t//配置项\r\n");
      out.write("    \tvar setting = {check: {\r\n");
      out.write("\t\t\tenable: true\r\n");
      out.write("\t\t}};\r\n");
      out.write("    \troleTree = $.fn.zTree.init($(\"#roleTree\"),setting, tdata);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//保存关系\r\n");
      out.write("function saveFunctionRole(){\r\n");
      out.write("\tvar funid= $(\"#funid\").val();\r\n");
      out.write("\tif(funid==null||funid=='')\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\tvar nodes=roleTree.getCheckedNodes(true);\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tfor(var i=0;i<nodes.length;i++){\r\n");
      out.write("\t\tvar node=nodes[i];\r\n");
      out.write("\t\tif(node.id!=null&&node.id!=''){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar obj={};\r\n");
      out.write("\t\t\tobj.roleid=node.id\r\n");
      out.write("\t\t\tobj.funid=funid;\r\n");
      out.write("\t\t\tarray.push(obj);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//参数\r\n");
      out.write("\tvar data={funid:funid,list:array};\r\n");
      out.write("\t$.ajax({  \r\n");
      out.write("        url: \"system/saveFunctionRole.do\",  \r\n");
      out.write("        contentType: \"application/json; charset=utf-8\",  \r\n");
      out.write("        type: \"POST\",  \r\n");
      out.write("        dataType: \"json\",  \r\n");
      out.write("        data: JSON.stringify(data),\r\n");
      out.write("        success: function(result) { \r\n");
      out.write("        \talert('授权成功！');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sort\">\r\n");
      out.write("\t<div class=\"sort-title\">\r\n");
      out.write("\t\t<h3>菜单管理</h3>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("    <div class=\"sort-cont sort-table\">\r\n");
      out.write("\t\t<div class=\"table\">\r\n");
      out.write("\t      \t\t<div class=\"table-bar\">\r\n");
      out.write("\t      \t\t\t<div class=\"table-title\">\r\n");
      out.write("\t\t\t\t\t\t表格名称\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t      \t\t\t<div class=\"table-ctrl\">\r\n");
      out.write("\t      \t\t\t\r\n");
      out.write("\t\t\t        \t<span id=\"group0\" class=\"gruop_hidden\">\r\n");
      out.write("\t\t\t\t\t        <span id=\"b1\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t        \t<a id=\"new\" class=\"btn\" href=\"javascript:addNode();\" style=\"display:none;\"><i class=\"icon icon-plus\"></i><span>新增</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"edit\" class=\"btn\" href=\"javascript:editNode()\" style=\"display:none;\"><i class=\"icon icon-pencil\"></i><span>修改</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a id=\"del\"  class=\"btn\" href=\"javascript:delNode()\"  style=\"display:none;\"><i class=\"icon icon-remove\"></i><span>删除</span></a>\r\n");
      out.write("\t\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t\t    \t<span id=\"b2\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t     \t\t<a class=\"btn\"  href=\"javascript:save();\"><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"btn\"  href=\"javascript:onCancel();\"><i class=\"icon icon-share\"></i><span>取消</span></a>\r\n");
      out.write("\t\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t   \t\t\r\n");
      out.write("\t\t\t\t   \t\t<span id=\"group1\" class=\"gruop_hidden\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t   \t\t\t<a class=\"btn\"  href=\"javascript:saveFunctionRole();\"><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-wrapper\" id=\"myContent\" style=\"height:550px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ui-layout-west\" style=\"overflow:auto;\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"tree\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"ui-layout-center\" style=\"overflow:hidden;\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"mytab\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#tab0\">基本信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#tab1\">角色赋权</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t <div id=\"tab0\">\r\n");
      out.write("\t\t\t\t\t\t        <form action=\"system/saveOrUpdateFunction.do\" method=\"post\" id=\"myForm\" class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"funid\" name=\"funid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"funpid\" name=\"funpid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<legend>基本信息</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t            \t<li>\r\n");
      out.write("\t\t\t\t\t\t                        <span>菜单类型：</span>\r\n");
      out.write("\t\t\t\t\t\t                        <label>\r\n");
      out.write("\t\t\t\t\t\t                        \t<input type=\"radio\" id=\"funtype0\" name=\"funtype\" value=\"0\" class=\"checkboxstyle\" checked />菜单\r\n");
      out.write("\t\t\t\t\t\t                        </label>\r\n");
      out.write("\t\t\t\t\t\t                        <label>\r\n");
      out.write("\t\t\t\t\t\t                        \t<input type=\"radio\" id=\"funtype1\" name=\"funtype\" value=\"1\" class=\"checkboxstyle\" />按钮\r\n");
      out.write("\t\t\t\t\t\t                        </label>\r\n");
      out.write("\t\t\t\t\t\t                    </li>\r\n");
      out.write("\t\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    <span><em class=\"red\">* </em>排序号：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    <input id=\"orderid\" name=\"orderid\" class=\"{required:true,number:true} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t </ul>\r\n");
      out.write("\t\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    <span><em class=\"red\">* </em>名称：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    <input id=\"labelname\" name=\"labelname\" class=\"{required:true,maxlength:20} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    <span>事件：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    <input id=\"javaevent\" name=\"javaevent\" class=\"{maxlength:100} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    <span>备注：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t     <textarea id=\"rmk\" name=\"rmk\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\" ></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t       \t</form>\r\n");
      out.write("\t\t\t\t\t    \t </div> \r\n");
      out.write("\t\t\t      \t\t \t<div id=\"tab1\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"roleTree\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t\t     \t</div>\r\n");
      out.write("\t\t\t\t  \t\t</div>\r\n");
      out.write("\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
