package org.apache.jsp.pages.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class option_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>选项管理</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\"/>    \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"skins/css/style.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"skins/css/form.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/jquery-ui-1.8.15.custom.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeStyle.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeIcons.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/gt_grid.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/default/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/green/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/mac/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/china/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/vista/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/calendar/calendar-blue.css\"  />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.json-2.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/public.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.layout.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-ui-1.8.5.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/tree/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/lib/jquery.metadata.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-en.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-setup.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_grid_all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_msg_cn.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("    \r\n");
      out.write("\t//tab页\r\n");
      out.write("\tloadTab();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//加载布局\r\n");
      out.write("\t$('#myContent').layout({\r\n");
      out.write("        west: {size:\"300\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("    //类型树\r\n");
      out.write("    buildOptionTypeTree();\r\n");
      out.write("    \r\n");
      out.write("    //选项的列表加载\r\n");
      out.write("    loadGrid();\r\n");
      out.write("    \r\n");
      out.write(" \t//把表单置为不可编辑\r\n");
      out.write("    formDisabled(true,\"#OptionTypeForm\");\r\n");
      out.write(" \t\r\n");
      out.write("   $(\"#OptionTypeForm\").validate({submitHandler: function(form) {\r\n");
      out.write("    \t$(form).ajaxSubmit(function(data) {\r\n");
      out.write("    \t\t formDisabled(true,\"#OptionTypeForm\");\r\n");
      out.write("    \t\t $(\"#b2\").hide();\r\n");
      out.write("    \t\t $(\"#b1\").show();\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("\t});\r\n");
      out.write("    \r\n");
      out.write("    //关闭等待层\r\n");
      out.write("    if(window.parent.hidenLoading)\r\n");
      out.write("    \twindow.parent.hidenLoading();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//选项类型树\r\n");
      out.write("var typeid=null;\r\n");
      out.write("function buildOptionTypeTree(){\r\n");
      out.write("\tvar setting = {callback:{beforeClick: function (treeId, treeNode){\r\n");
      out.write("\t\t\tif(treeNode.id!=null){\r\n");
      out.write("\t\t\t\tformDisabled(true,\"#OptionTypeForm\");//设置为只读\r\n");
      out.write("\t\t\t\ttypeid=treeNode.id;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#b0\").show();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("    \t\t\t//选项列表\r\n");
      out.write("\t    \t\tmygrid.reload();\r\n");
      out.write("\t\t\t\t//加载选项类型信息\r\n");
      out.write("\t\t\t\tloadOptionType(typeid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\tloadTab(treeNode);\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t  \t}\r\n");
      out.write("\t};\r\n");
      out.write("    $.getJSON(\"system/buildOptionTypesTree.do\", function(data) {\r\n");
      out.write("    \tvar zTree = $.fn.zTree.init($(\"#tree\"),setting, data);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//通过id加载选项类型的数据\r\n");
      out.write("var optionTypeid;\r\n");
      out.write("function loadOptionType(optionTypeid){\r\n");
      out.write("\t$.getJSON(\"system/getOptionTypeById.do\",{id:optionTypeid},function(data){\r\n");
      out.write("\t\trefreshForm(data);\t\t    \t\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//刷新Form\r\n");
      out.write("function refreshForm(data){\r\n");
      out.write("\t$(\"#OptionTypeForm\").clearForm();\r\n");
      out.write("\tfor(var key in data){\r\n");
      out.write("\t\tvar el = $(\"#\"+key);\r\n");
      out.write("\t\tif(el)\r\n");
      out.write("\t\t\tel.attr('value',data[key]);\r\n");
      out.write("\t\tif(key=='reserved'){\r\n");
      out.write("\t\t\tdata[key]==1?$(\"#reserved\").attr('checked',true):false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(tabIndex==0){\r\n");
      out.write("\t\t$(\"#tab1\").show();\r\n");
      out.write("\t\t$(\"#b0\").show();\r\n");
      out.write("\t}else if(tabIndex==1){\r\n");
      out.write("\t\t$(\"#tab1\").show();\r\n");
      out.write("\t\t$(\"#b1\").show();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//tab页\r\n");
      out.write("var tabIndex=0;\r\n");
      out.write("var rootNode;\r\n");
      out.write("function loadTab(rootNode){\r\n");
      out.write("\t$(\"#mytab\").tabs({\r\n");
      out.write("    \tselect: function(event, ui) {\r\n");
      out.write("    \t\ttabIndex=ui.index;\r\n");
      out.write("    \t\t$(\".gruop_hidden\").hide();\r\n");
      out.write("    \t\t$(\"#group\"+tabIndex).show();\r\n");
      out.write("    \t\t$(\"#tab\"+tabIndex).show();\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t//刷新关系\r\n");
      out.write("    \t\tif(rootNode!=null){\r\n");
      out.write("    \t\t\tif(tabIndex==0){\r\n");
      out.write("    \t\t\t\t$(\"#tab1\").show();\r\n");
      out.write("    \t\t\t\t$(\"#b0\").show();\r\n");
      out.write("    \t\t\t}else if(tabIndex==1){\r\n");
      out.write("    \t\t\t\t$(\"#tab1\").show();\r\n");
      out.write("    \t\t\t\t$(\"#b1\").show();\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t}else{\r\n");
      out.write("    \t\t\tif(tabIndex==0){\r\n");
      out.write("    \t\t\t\t$(\"#tab1\").show();\r\n");
      out.write("    \t\t\t\t$(\"#b0\").hide();\r\n");
      out.write("    \t\t\t}else if(tabIndex==1){\r\n");
      out.write("    \t\t\t\t$(\"#tab1\").show();\r\n");
      out.write("    \t\t\t\t$(\"#b1\").hide();\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//修改选项类型的数据\r\n");
      out.write("function updateNode(){\r\n");
      out.write("\t$('#b1').hide();\r\n");
      out.write("\t$('#b2').show();\r\n");
      out.write("\tformDisabled(false,\"#OptionTypeForm\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//保存选项类型的数据\r\n");
      out.write("function saveOptionType(){\r\n");
      out.write("\tvar reservedId=null;\r\n");
      out.write("\tif($(\"#OptionTypeForm #reserved\").attr(\"checked\")){\r\n");
      out.write("\t\treservedId=1;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\treservedId=2;\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#OptionTypeForm #reserved\").val(reservedId);\r\n");
      out.write("\t$(\"#OptionTypeForm\").submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//取消修改选项类型的数据\r\n");
      out.write("function cancelOptionType(){\r\n");
      out.write("\t$('#b2').hide();\r\n");
      out.write("\t$('#b1').show();\r\n");
      out.write("\tformDisabled(true,\"#OptionTypeForm\");\r\n");
      out.write("\tloadOptionType(treeNode.id);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//是否默认选项 ----optionlist\r\n");
      out.write("function checkOptionListmrxx(el){\r\n");
      out.write("\tvar checked=$(el).attr(\"checked\");\r\n");
      out.write("\t$(el).val(checked?1:0);\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//是否系统保留----optionlist\r\n");
      out.write("function checkkOptionListxtbl(el){\r\n");
      out.write("\tvar checked=$(el).attr(\"checked\");\r\n");
      out.write("\t$(el).val(checked?1:0);\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//新增选项列表的数据\r\n");
      out.write("var add=false;\r\n");
      out.write("var OptionListguid;\r\n");
      out.write("var optionListForm=null\r\n");
      out.write("function addOrUpdateOptionList(state,OptionListguid){\r\n");
      out.write("\tadd=state;\r\n");
      out.write("\t$(\"#addOptionListWindow\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:500,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\t$(\"#optionListForm input[id=optiontypeguid]\").val(typeid);\r\n");
      out.write("\t\t\t\t\tsaveOptionList();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},open:function(){\r\n");
      out.write("\t\t\t$(\"#optionListForm\").clearForm();\r\n");
      out.write("\t\t\tif(!add){\r\n");
      out.write("\t\t\t\tloadOptionList(OptionListguid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\toptionListForm=$(\"#optionListForm\").validate({submitHandler: function(form) {\r\n");
      out.write("\t\t    \t$(form).ajaxSubmit(function(data) {\r\n");
      out.write("\t\t    \t\tmygrid.reload();\r\n");
      out.write("\t\t    \t\t$(\"#addOptionListWindow\").dialog(\"close\");\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//代码不能重复\r\n");
      out.write("function saveOptionList(){\r\n");
      out.write("\tvar optionid=$(\"#optionListForm input[id=optionid]\").val();\r\n");
      out.write("\tvar optiontypeguid=$(\"#optionListForm input[id=optiontypeguid]\").val();\r\n");
      out.write("\tvar code=$(\"#optionListForm input[id=code]\").val();\r\n");
      out.write("\t$.post(\"system/checkOptionList.do\",{optionid:optionid,optiontypeguid:optiontypeguid,code:code},function(msg){\r\n");
      out.write("\t\tif(msg){\r\n");
      out.write("\t\t\talert(\"代码重复！\");\r\n");
      out.write("\t\t\t$(\"#optionListForm input[id=code]\").val(null);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#optionListForm\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//通过选项列表的id加载数据\r\n");
      out.write("function loadOptionList(OptionListguid){\r\n");
      out.write("\t$.getJSON(\"system/getOptionListByListId.do\",{id:OptionListguid},function(data){\r\n");
      out.write("\t\tfor(var key in data){\r\n");
      out.write("\t\t\tif($('#optionListForm input[id='+key+']')){\r\n");
      out.write("\t\t\t\t$('#optionListForm input[id='+key+']').val(data[key]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif($('#optionListForm textarea[id='+key+']')){\r\n");
      out.write("\t\t\t\t$('#optionListForm textarea[id='+key+']').val(data[key]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#optionListForm input[id=isdefault]\").attr(\"checked\",data.isdefault==1);\r\n");
      out.write("\t\t\t$(\"#optionListForm input[id=reserved]\").attr(\"checked\",data.reserved==1);\r\n");
      out.write("\t\t}    \t\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//删除选项列表数据\r\n");
      out.write("function delOptionList(){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tvar cords=mygrid.getSelectedRecords();\r\n");
      out.write("\tfor(var i=0;i<cords.length;i++){\r\n");
      out.write("\t\tvar obj=cords[i];\r\n");
      out.write("\t\tarray.push(obj.optionid);\r\n");
      out.write("\t}\r\n");
      out.write("\tif(array.length<=0){\r\n");
      out.write("\t\talert('请选择要删除的数据！');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(!confirm('确认要删除选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("   \t$.post(\"system/delOptionListById.do\",{ids:array.toString()}, function() {\r\n");
      out.write("\t\tmygrid.reload();\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//选项列表\r\n");
      out.write("var mygrid=null;\r\n");
      out.write("function loadGrid(){\r\n");
      out.write("\tvar size=getGridSize();\r\n");
      out.write("\tvar wh=$(document.body).outerWidth()-360;\r\n");
      out.write("\t$(\"#myTable\").css({width:wh,height:495});\r\n");
      out.write("\t\r\n");
      out.write("\tvar grid_demo_id = \"myGrid1\";\r\n");
      out.write("\tvar dsOption= {\r\n");
      out.write("\t\t\tfields :[\r\n");
      out.write("\t\t\t\t{name : 'optionid'},\r\n");
      out.write("\t\t\t\t{name : 'optiontypeguid'},\r\n");
      out.write("\t\t\t\t{name : 'code'},\r\n");
      out.write("\t\t\t\t{name : 'name'},\r\n");
      out.write("\t\t\t\t{name : 'isdefault'},\r\n");
      out.write("\t\t\t\t{name : 'dorder'},\r\n");
      out.write("\t\t\t\t{name : 'reserved'},\r\n");
      out.write("\t\t\t\t{name : 'rmk'}\r\n");
      out.write("\t\t\t]\r\n");
      out.write("\t\t};\r\n");
      out.write("\tvar colsOption = [\r\n");
      out.write("\t\t\t\t\t{id: '选择' ,isCheckColumn : true, editable:false,headAlign:'center',align:'center',filterable:false},\r\n");
      out.write("\t              \t{id: 'dorder' , header: \"排序号\" ,headAlign:'center',align:'center', width :50},\r\n");
      out.write("\t          \t   \t{id: 'code' , header: \"代码\",headAlign:'center',align:'center', width :80},\r\n");
      out.write("\t          \t   \t{id: 'name' , header: \"名称\",headAlign:'center', width :250},\r\n");
      out.write("\t          \t   \t{id: 'isdefault' , header: \"是默认选项\" ,headAlign:'center', align:'center', width :80},\r\n");
      out.write("\t          \t   \t{id: 'reserved' , header: \"是否系统保留\" ,headAlign:'center', align:'center', width :80},\r\n");
      out.write("\t          \t   \t{id: 'rmk' , header: \"备注\" ,headAlign:'left', width :200}\r\n");
      out.write("\t          \t];\r\n");
      out.write("\tvar gridOption={\r\n");
      out.write("\t\tid : grid_demo_id,\r\n");
      out.write("\t\tloadURL : 'system/getOptionListByOptionTypeId.do',\r\n");
      out.write("\t\tbeforeLoad:function(reqParam){\r\n");
      out.write("\t\t\treqParam['parameters']={'id':typeid};\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsaveURL :'system/saveOrUpdateOptionList.do',\r\n");
      out.write("\t\twidth:'100%',\r\n");
      out.write("\t\theight:\"100%\",  //\"100%\", // 330,\r\n");
      out.write("\t\tcontainer : 'gridbox',\r\n");
      out.write("\t\tautoLoad:false,\r\n");
      out.write("\t\tstripeRows: false,\r\n");
      out.write("\t\tshowIndexColumn:true,\r\n");
      out.write("\t\tselectRowByCheck:true,\r\n");
      out.write("\t\treplaceContainer : true,\r\n");
      out.write("\t\tdataset : dsOption ,\r\n");
      out.write("\t\tcolumns : colsOption,\r\n");
      out.write("\t\ttoolbarContent : 'nav | pagesize  state',\r\n");
      out.write("\t\tpageSizeList : [size,size*2,size*4,size*6,size*8,size*10],\r\n");
      out.write("\t\tpageSize:size,\r\n");
      out.write("\t\tskin:getGridSkin(),\r\n");
      out.write("\t\tonDblClickCell:function(value, record , cell, row, colNO, rowNO,columnObj,grid){\r\n");
      out.write("\t\t\tif(colNO!=0){\r\n");
      out.write("\t\t\t\taddOrUpdateOptionList(false,record.optionid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tmygrid=new Sigma.Grid( gridOption );\r\n");
      out.write("\tSigma.Util.onLoad( Sigma.Grid.render(mygrid) );\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sort\">\r\n");
      out.write("\t<div class=\"sort-title\">\r\n");
      out.write("\t\t<h3>选项管理</h3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"sort-cont sort-table\">\r\n");
      out.write("\t\t<div class=\"table\">\r\n");
      out.write("\t\t\t<div class=\"table-bar\">\r\n");
      out.write("\t\t\t\t<div class=\"table-title\">\r\n");
      out.write("\t\t\t\t\t表格名称\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-ctrl\">\r\n");
      out.write("\t\t\t\t\t<span id=\"group0\" class=\"gruop_hidden\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"b0\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a  class=\"btn\" href=\"javascript:addOrUpdateOptionList(true);\"><i class=\"icon icon-plus\"></i><span>新增</span></a>\r\n");
      out.write("\t\t\t\t   \t\t\t<a  class=\"btn\" href=\"javascript:delOptionList();\"><i class=\"icon icon-trash\"></i><span>删除</span></a>\r\n");
      out.write("\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<span id=\"group1\" class=\"gruop_hidden\">\r\n");
      out.write("\t\t\t\t\t   \t<span id=\"b1\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"update\" class=\"btn\" href=\"javascript:updateNode();\"><i class=\"icon icon-pencil\"></i><span>修改</span></a>\r\n");
      out.write("\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t   \t\t<span id=\"b2\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:saveOptionType();\"><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn\" href=\"javascript:cancelOptionType();\"><i class=\"icon icon-share\"></i><span>取消</span></a>\r\n");
      out.write("\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"table-wrapper\" id=\"myContent\" style=\"height:550px;\">\r\n");
      out.write("\t\t\t\t<div class=\"ui-layout-west\" style=\"overflow:auto;\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"tree\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"ui-layout-center\">\r\n");
      out.write("\t\t\t\t\t<div id=\"mytab\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#tab0\">选项列表</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#tab1\">选项类型</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tab0\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"padding-top:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"myTable\" style=\"margin:0px auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"gridbox\" ></div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tab1\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"system/saveOrUpdateOptionType.do\" method=\"post\" id=\"OptionTypeForm\" class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"optiontypeguid\" name=\"optiontypeguid\" type=\"hidden\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t<legend>基本信息</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>&nbsp;</span>\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t<input type=\"checkbox\" id=\"reserved\" name=\"reserved\" class=\"{required:true,maxlength:38}\" value=\"\" class=\"checkboxstyle\" />是否系统保留\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><em class=\"red\">* </em>排序号：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"dorder\" name=\"dorder\" class=\"{required:true,maxlength:38,number:true} inputstyle\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t   \t \t\t\t\t<span><em class=\"red\">* </em>代码：</span>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<input id=\"code\" name=\"code\" class=\"{required:true,maxlength:60} inputstyle\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t                 \t\t\t\t\t<span><em class=\"red\">* </em>名称：</span>\r\n");
      out.write("\t                 \t\t\t\t\t<input id=\"name\" name=\"name\" class=\"{required:true,maxlength:60} inputstyle\"/>\r\n");
      out.write("\t           \t\t\t\t\t\t</li>\r\n");
      out.write("\t        \t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>备注：</span>\r\n");
      out.write("\t\t\t\t    \t\t\t\t\t<textarea id=\"rmk\" name=\"rmk\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t       \t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t       \t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 添加窗口 -->\r\n");
      out.write("<div id=\"addOptionListWindow\" title=\"添加选项列表\" style=\"display:none\">\r\n");
      out.write("\t<form action=\"system/saveOrUpdateOptionList.do\" id=\"optionListForm\"  method=\"post\" class=\"form\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"optionid\" name=\"optionid\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"optiontypeguid\" name=\"optiontypeguid\" value=\"\"/>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span>&nbsp;</span>\r\n");
      out.write("\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"isdefault\" name=\"isdefault\"  value=\"0\" class=\"checkboxstyle\" onclick=\"checkOptionListmrxx(this)\"/>是默认选项\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" id=\"reserved\" name=\"reserved\"  value=\"0\" class=\"checkboxstyle\" onclick=\"checkkOptionListxtbl(this)\"/>是否系统保留\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>代码：</span>\r\n");
      out.write("\t\t\t\t<input  id=\"code\" name=\"code\" value=\"\" class=\"{required:true,maxlength:4} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>名称：</span>\r\n");
      out.write("\t\t\t\t<input id=\"name\" name=\"name\" value=\"\" class=\"{required:true,maxlength:30} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>排序号：</span>\r\n");
      out.write("\t\t\t\t<input  id=\"dorder\" name=\"dorder\" value=\"\" class=\"{required:true,maxlength:19} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span>备注：</span>\r\n");
      out.write("\t\t\t\t<textarea id=\"rmk\" name=\"rmk\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\"></textarea>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
