package org.apache.jsp.pages.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005ftree_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>用户管理</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\"/>    \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/style.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/form.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/jquery-ui-1.8.15.custom.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeStyle.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeIcons.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/gt_grid.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/default/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/green/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/mac/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/china/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/vista/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/calendar/calendar-blue.css\"  />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.json-2.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/public.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.layout.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-ui-1.8.5.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/tree/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/lib/jquery.metadata.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-en.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-setup.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_grid_all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_msg_cn.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t//tab页\r\n");
      out.write("\tloadTab();\r\n");
      out.write("\t\r\n");
      out.write("\t//加载布局\r\n");
      out.write("\t$('#myContent').layout({\r\n");
      out.write("        west: {size:\"300\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t$('#myWest').layout({\r\n");
      out.write("        north: {size:\"28\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\t//列表加载\r\n");
      out.write("    loadGrid();\r\n");
      out.write("\t\r\n");
      out.write("  \t//加载树\r\n");
      out.write("    buildMyUserTree();\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("    //加载表单验证\r\n");
      out.write("    $(\"#myForm\").validate();\r\n");
      out.write("    $('#myForm').ajaxForm(function(data) {\r\n");
      out.write("        //节点处理\r\n");
      out.write("    \tvar nameValue=data.username;\r\n");
      out.write("    \t\r\n");
      out.write("    \tif(add){//新增\r\n");
      out.write("    \t\tif(selectNode!=null&&selectNode.code==\"user\")\r\n");
      out.write("    \t\t\tselectNode=selectNode.getParentNode();\r\n");
      out.write("    \t\tvar newNode = {id:data.userguid, name:nameValue,iconSkin:\"user\",code:\"user\",ename:1};\r\n");
      out.write("       \t\tzTree.addNodes(selectNode, newNode);\r\n");
      out.write("        }else{\r\n");
      out.write("        \tselectNode.name = nameValue;\r\n");
      out.write("   \t\t\tzTree.updateNode(selectNode);\r\n");
      out.write("   \t\t\tzTree.selectNode(selectNode);\r\n");
      out.write("        }\r\n");
      out.write("    \tadd=false;\r\n");
      out.write("    \t//不可编辑\r\n");
      out.write("    \tformDisabled(true);\r\n");
      out.write("    \t\r\n");
      out.write("    \t//取消\r\n");
      out.write("    \tonCancel();\r\n");
      out.write("    \t\r\n");
      out.write("    });\r\n");
      out.write(" \t//把表单置为不可编辑\r\n");
      out.write("    formDisabled(true);\r\n");
      out.write("  \t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//tab页\r\n");
      out.write("var tabIndex=0;\r\n");
      out.write("function loadTab(){\r\n");
      out.write("\t$(\"#mytab\").tabs({\r\n");
      out.write("    \tselect: function(event, ui) {\r\n");
      out.write("    \t\ttabIndex=ui.index;\r\n");
      out.write("    \t\t$(\".gruop_hidden\").hide();\r\n");
      out.write("    \t\t$(\"#group\"+tabIndex).show();\r\n");
      out.write("    \t\t$(\"#tab\"+tabIndex).show();\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t//崗位樹\r\n");
      out.write("\t\t\tif(tabIndex==1)\r\n");
      out.write("    \t\t\tbuildRoleTree();\r\n");
      out.write("\t\t\telse if(tabIndex==2){\r\n");
      out.write("\t\t\t\tbuildCompanyTree();\r\n");
      out.write("\t\t\t}else if(tabIndex == 4){\r\n");
      out.write("\t\t\t\tbuildadepartmentTree();\r\n");
      out.write("\t\t\t}else if(tabIndex == 3) {\r\n");
      out.write("\t\t\t\tbuildaddressTree();\r\n");
      out.write("\t\t\t}else if(tabIndex==5){\r\n");
      out.write("\t\t\t\tmygrid.reload();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//树\r\n");
      out.write("var zTree;\r\n");
      out.write("//选中节点\r\n");
      out.write("var selectNode=null;\r\n");
      out.write("var userid=null;\r\n");
      out.write("function buildMyUserTree(){\r\n");
      out.write("\tvar setting = {\r\n");
      out.write("\t\tasync: {\r\n");
      out.write("\t\t\tenable: true,\r\n");
      out.write("\t\t\turl: getUrl\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tcallback:{\r\n");
      out.write("\t\t\tbeforeClick: function(treeId, treeNode){\r\n");
      out.write("\t\t\t\t$(\"#myForm\").clearForm();\r\n");
      out.write("\t\t\t\tselectNode=treeNode;\r\n");
      out.write("\t\t\t\tformDisabled(true);\r\n");
      out.write("\t\t\t\t//出现按钮组一\r\n");
      out.write("\t\t\t\t$('#b1').show();\r\n");
      out.write("\t\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\tuserid=treeNode.id;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//只能新增\r\n");
      out.write("\t\t\t\tif(treeNode.code!='user'){\r\n");
      out.write("\t\t\t\t\t//$('#new').show();\r\n");
      out.write("\t\t\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t\t\t\t$(\".save\").hide();\r\n");
      out.write("\t\t\t\t}else if(treeNode.code=='user'){\r\n");
      out.write("\t\t\t\t\t//有效的\r\n");
      out.write("\t\t\t\t\tif(treeNode.ename==1){\r\n");
      out.write("\t\t\t\t\t\t$('#edit').show();\r\n");
      out.write("\t\t\t\t\t\t//$('#new').show();\r\n");
      out.write("\t\t\t\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t\t\t\t//$('#new').hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#recover\").show();\r\n");
      out.write("\t\t\t\t\t\t$(\"#remove\").show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\".save\").show();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tmygrid.reload();\r\n");
      out.write("\t\t\t\t\t//取数据\r\n");
      out.write("\t\t\t\t\tloadData(treeNode.id);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t\t\t//$('#new').hide();\r\n");
      out.write("\t\t\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tonAsyncSuccess: onAsyncSuccess,\r\n");
      out.write("\t\tonAsyncError: onAsyncError,\r\n");
      out.write("\t\tview: {\r\n");
      out.write("\t\t\tfontCss: getDeptFontCss\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\t$.getJSON(\"system/buildMyDepartmentTree.do\",function(tdata) {\r\n");
      out.write("\t\tzTree = $.fn.zTree.init($(\"#tree\"),setting, tdata);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//邦定定位事件\r\n");
      out.write("    \t$(\"#myMarker\").bind(\"keyup\",markTreeNode);\r\n");
      out.write("    \t$(\"#myMarker\").bind(\"blur\",markSelectTreeNode);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//异步数据\r\n");
      out.write("function getUrl(treeId, treeNode) {\r\n");
      out.write("\treturn \"system/asyncUserTree.do?deptid=\" + treeNode.id;\r\n");
      out.write("}\r\n");
      out.write("function onAsyncSuccess(event, treeId, treeNode, msg) {\r\n");
      out.write("\tif(!msg || msg.length == 0) {return;}\r\n");
      out.write("\tzTree.updateNode(treeNode);\r\n");
      out.write("}\r\n");
      out.write("function onAsyncError(event, treeId, treeNode, XMLHttpRequest, textStatus, errorThrown) {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//======================\r\n");
      out.write("//节点搜索定位\r\n");
      out.write("function markSelectTreeNode(){\r\n");
      out.write("\tvar value=\"\";\r\n");
      out.write("\tvalue = $.trim($(\"#myMarker\").val());\r\n");
      out.write("\tif (value != \"\"){\r\n");
      out.write("\t\tnodeList = zTree.getNodesByParamFuzzy(\"name\", value);\r\n");
      out.write("\t\tif(nodeList.length<=0)\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\tfor( var i=0, l=nodeList.length; i<l; i++) {\r\n");
      out.write("\t\t\tvar node=nodeList[i];\r\n");
      out.write("\t\t\tif(i==0){\r\n");
      out.write("\t\t\t\tzTree.selectNode(node);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//节点搜索变色\r\n");
      out.write("function markTreeNode(e) {\r\n");
      out.write("\tif(!nodeState){\r\n");
      out.write("\t\tnodeState=true;\r\n");
      out.write("\t\tvar value=\"\";\r\n");
      out.write("\t\tvalue = $.trim($(\"#myMarker\").val());\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tchangeNodesColor(false);\r\n");
      out.write("\t\tif (value === \"\"){\r\n");
      out.write("\t\t\tnodeState=false;\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tnodeList = zTree.getNodesByParamFuzzy(\"name\", value);\r\n");
      out.write("\t\tchangeNodesColor(true);\r\n");
      out.write("\t\tnodeState=false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function changeNodesColor(highlight) {\r\n");
      out.write("\tif(nodeList.length<=0)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tfor( var i=0, l=nodeList.length; i<l; i++) {\r\n");
      out.write("\t\tvar node=nodeList[i];\r\n");
      out.write("\t\tnode.highlight = highlight;\r\n");
      out.write("\t\tzTree.updateNode(nodeList[i]);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getDeptFontCss(treeId, treeNode) {\r\n");
      out.write("\treturn (!!treeNode.highlight) ? {color:\"#ff0000\", \"font-weight\":\"bold\"} : {color:\"#333\", \"font-weight\":\"normal\"};\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//==========================================\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//取数据\r\n");
      out.write("function loadData(tid) {\r\n");
      out.write("\t$(\"#myForm\").clearForm();\r\n");
      out.write("\tif(tid!=null&&tid!=''&&tid!='null')\r\n");
      out.write("\t\t$.getJSON(\"system/getUserById.do\", {id:tid}, function(data) {\r\n");
      out.write("\t\t\tif(data!=null){\r\n");
      out.write("\t\t\t\tfor (var key in data) {\r\n");
      out.write("\t\t\t        var el = $('#' + key);\r\n");
      out.write("\t\t\t        if(el) \r\n");
      out.write("\t\t\t            el.val(data[key]);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//崗位樹\r\n");
      out.write("\t\t\t\tif(tabIndex==1){\r\n");
      out.write("\t    \t\t\tbuildRoleTree();\r\n");
      out.write("\t\t\t\t}else if(tabIndex==2){\r\n");
      out.write("\t    \t\t\tbuildCompanyTree();\r\n");
      out.write("\t    \t\t}else if(tabIndex==4){\r\n");
      out.write("\t    \t\t\tbuildadepartmentTree();\r\n");
      out.write("\t    \t\t}else if(tabIndex==3){\r\n");
      out.write("\t    \t\t\tbuildaddressTree();\r\n");
      out.write("\t    \t\t}else if(tabIndex==5){\r\n");
      out.write("\t    \t\t\tmygrid.reload();\r\n");
      out.write("\t    \t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//新增\r\n");
      out.write("var add=false;\r\n");
      out.write("function addNode(){\r\n");
      out.write("\t$('#b1').hide();\r\n");
      out.write("\t$('#b2').show();\r\n");
      out.write("\t$(\"#myForm\").clearForm();\r\n");
      out.write("\tformDisabled(false);\r\n");
      out.write("\tadd=true;\r\n");
      out.write("\t\r\n");
      out.write("\t$('#isadmin').val(0);\r\n");
      out.write("\t$('#state').val(1);\r\n");
      out.write("\t\r\n");
      out.write("\t//所属组织\r\n");
      out.write("\tvar srcNode=selectNode;\r\n");
      out.write("\tif(srcNode!=null&&srcNode.code==\"user\")\r\n");
      out.write("\t\tsrcNode=srcNode.getParentNode();\r\n");
      out.write("\t$(\"#orgguid\").val(srcNode.id);\r\n");
      out.write("\t$(\"#orgname\").val(srcNode.name);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//编辑\r\n");
      out.write("function editNode(){\r\n");
      out.write("\t$('#b1').hide();\r\n");
      out.write("\t$('#b2').show();\r\n");
      out.write("\tformDisabled(false,'#myPassword');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//取消\r\n");
      out.write("function onCancel(){\r\n");
      out.write("\tformDisabled(true,'#myPassword');\r\n");
      out.write("\t\r\n");
      out.write("\t//取数据\r\n");
      out.write("\tif(selectNode!=null){\r\n");
      out.write("\t\tif(selectNode.code=='user'){\r\n");
      out.write("\t\t\tloadData(selectNode.id);\r\n");
      out.write("\t\t\t$('#b1').show();\r\n");
      out.write("\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#edit').show();\r\n");
      out.write("\t\t\t//$('#new').show();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#b1').show();\r\n");
      out.write("\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//$('#new').show();\r\n");
      out.write("\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//删除\r\n");
      out.write("function del(){\r\n");
      out.write("\tif(selectNode==null)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tif(!confirm('确认要删除选中的用户吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.post(\"system/delUserById.do\",{userguid:selectNode.id}, function() {\r\n");
      out.write("\t\tzTree.removeNode(selectNode);\r\n");
      out.write("\t\t$(\"#myForm\").clearForm();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#b1').hide();\r\n");
      out.write("\t\t$('#b2').hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tformDisabled(true);\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//保存\r\n");
      out.write("function save(){\r\n");
      out.write("\t$('#myForm').submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//检查登陆名\r\n");
      out.write("function checklogname(){\r\n");
      out.write("\tvar userguid=$(\"#userguid\").val();\r\n");
      out.write("\tvar loginname=$(\"#loginname\").val();\r\n");
      out.write("\tif(loginname!=null&&loginname!=''&&loginname!='null')\r\n");
      out.write("\t$.post(\"system/getUserByLoginName.do\",{name:loginname}, function(data) {\r\n");
      out.write("\t\tif(data==null||data=='')return;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif((userguid==null||userguid=='')||(userguid!=data.userguid)){\r\n");
      out.write("\t\t\talert(\"登陆名已经存在,请从新输入！\");\r\n");
      out.write("\t\t\t$(\"#loginname\").val(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//导出\r\n");
      out.write("function expGrid(){\r\n");
      out.write("\twindow.open(\"system/exportUser.do\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//崗位树\r\n");
      out.write("var roleTree;\r\n");
      out.write("function buildRoleTree(){\r\n");
      out.write("\tvar userguid= $(\"#userguid\").val();\r\n");
      out.write("\tif(userguid==null||userguid=='')\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#roleTree\").html(null);\r\n");
      out.write("    $.getJSON(\"system/buildRoleCheckTree.do\",{userguid:userguid}, function(tdata) {\r\n");
      out.write("    \t//配置项\r\n");
      out.write("    \tvar setting = {check: {\r\n");
      out.write("\t\t\tenable: true\r\n");
      out.write("\t\t}};\r\n");
      out.write("    \troleTree = $.fn.zTree.init($(\"#roleTree\"),setting, tdata);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//保存关系\r\n");
      out.write("function saveUserPost(){\r\n");
      out.write("\tvar userguid= $(\"#userguid\").val();\r\n");
      out.write("\tif(userguid==null||userguid=='')\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\tvar nodes=roleTree.getCheckedNodes(true);\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tfor(var i=0;i<nodes.length;i++){\r\n");
      out.write("\t\tvar node=nodes[i];\r\n");
      out.write("\t\tif(node.id!=null&&node.id!=''){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar obj={};\r\n");
      out.write("\t\t\tobj.roleid=node.id\r\n");
      out.write("\t\t\tobj.userguid=userguid;\r\n");
      out.write("\t\t\tarray.push(obj);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//参数\r\n");
      out.write("\tvar data={userguid:userguid,list:array};\r\n");
      out.write("\t$.ajax({  \r\n");
      out.write("        url: \"system/saveUserRole.do\",  \r\n");
      out.write("        contentType: \"application/json; charset=utf-8\",  \r\n");
      out.write("        type: \"POST\",  \r\n");
      out.write("        dataType: \"json\",  \r\n");
      out.write("        data: JSON.stringify(data),\r\n");
      out.write("        success: function(result) { \r\n");
      out.write("        \talert('授权成功！');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//公司树\r\n");
      out.write("var companyTree;\r\n");
      out.write("function buildCompanyTree(){\r\n");
      out.write("\tvar userguid= $(\"#userguid\").val();\r\n");
      out.write("\tif(userguid==null||userguid=='')\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#companyTree\").html(null);\r\n");
      out.write("    $.getJSON(\"system/buildCompanyCheckTree.do\",{userguid:userguid}, function(tdata) {\r\n");
      out.write("    \t//配置项\r\n");
      out.write("    \tvar setting = {check: {\r\n");
      out.write("\t\t\tenable: true,\r\n");
      out.write("\t\t\tchkboxType: { \"Y\": \"\", \"N\": \"\" }\r\n");
      out.write("\t\t}};\r\n");
      out.write("    \tcompanyTree = $.fn.zTree.init($(\"#companyTree\"),setting, tdata);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//保存关系\r\n");
      out.write("function saveUserCompany(){\r\n");
      out.write("\tvar userguid= $(\"#userguid\").val();\r\n");
      out.write("\tif(userguid==null||userguid=='')\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\tvar nodes=companyTree.getCheckedNodes(true);\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tfor(var i=0;i<nodes.length;i++){\r\n");
      out.write("\t\tvar node=nodes[i];\r\n");
      out.write("\t\tif(node.id!=null&&node.id!=''){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar obj={};\r\n");
      out.write("\t\t\tobj.userguid=userguid;\r\n");
      out.write("\t\t\tobj.companyid=node.id;\r\n");
      out.write("\t\t\tobj.isdefault=1;\r\n");
      out.write("\t\t\tarray.push(obj);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//参数\r\n");
      out.write("\tvar data={userguid:userguid,list:array};\r\n");
      out.write("\t$.ajax({  \r\n");
      out.write("        url: \"system/saveUserCompany.do\",  \r\n");
      out.write("        contentType: \"application/json; charset=utf-8\",  \r\n");
      out.write("        type: \"POST\",  \r\n");
      out.write("        dataType: \"json\",  \r\n");
      out.write("        data: JSON.stringify(data),\r\n");
      out.write("        success: function(result) { \r\n");
      out.write("        \talert('授权成功！');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//通讯录树\r\n");
      out.write("var addressTree;\r\n");
      out.write("function buildaddressTree(){\r\n");
      out.write("\tvar userguid= $(\"#userguid\").val();\r\n");
      out.write("\tif(userguid==null||userguid=='')\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#addressTree\").html(null);\r\n");
      out.write("    $.getJSON(\"system/buildAddressCompanyCheckTree.do\",{userguid:userguid}, function(tdata) {\r\n");
      out.write("    \t//配置项\r\n");
      out.write("    \tvar setting = {check: {\r\n");
      out.write("\t\t\tenable: true,\r\n");
      out.write("\t\t\tchkboxType: { \"Y\": \"s\", \"N\": \"\" }\r\n");
      out.write("\t\t}};\r\n");
      out.write("    \taddressTree = $.fn.zTree.init($(\"#addressTree\"),setting, tdata);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//保存关系\r\n");
      out.write("function saveUserAddressCompany(){\r\n");
      out.write("\tvar userguid= $(\"#userguid\").val();\r\n");
      out.write("\tif(userguid==null||userguid=='')\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tvar checknodes=addressTree.getCheckedNodes(true);\r\n");
      out.write("\tvar unchecknodes=addressTree.getCheckedNodes(false);\r\n");
      out.write("\t\r\n");
      out.write("\tif(unchecknodes.length==0){\r\n");
      out.write("\t\tvar obj={};\r\n");
      out.write("\t\tobj.userguid=userguid;\r\n");
      out.write("\t\tarray.push(obj);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tfor(var i=0;i<checknodes.length;i++){\r\n");
      out.write("\t\t\tvar node=checknodes[i];\r\n");
      out.write("\t\t\tif(node.id!=null&&node.id!=''){\r\n");
      out.write("\t\t\t\tvar obj={};\r\n");
      out.write("\t\t\t\tobj.userguid=userguid;\r\n");
      out.write("\t\t\t\tobj.companyid=node.id;\r\n");
      out.write("\t\t\t\tarray.push(obj);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//参数\r\n");
      out.write("\tvar data={userguid:userguid,list:array};\r\n");
      out.write("\t$.ajax({  \r\n");
      out.write("        url: \"system/saveUserAddressCompany.do\",  \r\n");
      out.write("        contentType: \"application/json; charset=utf-8\",  \r\n");
      out.write("        type: \"POST\",  \r\n");
      out.write("        dataType: \"json\",  \r\n");
      out.write("        data: JSON.stringify(data),\r\n");
      out.write("        success: function(result) { \r\n");
      out.write("        \talert('授权成功！');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//部门树\r\n");
      out.write("var departmentTree;\r\n");
      out.write("function buildadepartmentTree(){\r\n");
      out.write("\tvar userguid= $(\"#userguid\").val();\r\n");
      out.write("\tif(userguid==null||userguid=='')\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#departmentTree\").html(null);\r\n");
      out.write("    $.getJSON(\"system/buildUserDepartmentCheckTree.do\",{userguid:userguid}, function(tdata) {\r\n");
      out.write("    \t//配置项\r\n");
      out.write("    \tvar setting = {check: {\r\n");
      out.write("\t\t\tenable: true,\r\n");
      out.write("\t\t\tchkboxType: { \"Y\": \"s\", \"N\": \"\" }\r\n");
      out.write("\t\t}};\r\n");
      out.write("    \tdepartmentTree = $.fn.zTree.init($(\"#departmentTree\"),setting, tdata);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//保存关系\r\n");
      out.write("function saveUserdepartment(){\r\n");
      out.write("\tvar userguid= $(\"#userguid\").val();\r\n");
      out.write("\tif(userguid==null||userguid=='')\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tvar checknodes=departmentTree.getCheckedNodes(true);\r\n");
      out.write("\tvar unchecknodes=departmentTree.getCheckedNodes(false);\r\n");
      out.write("\t\r\n");
      out.write("\tif(unchecknodes.length==0){\r\n");
      out.write("\t\tvar obj={};\r\n");
      out.write("\t\tobj.userguid=userguid;\r\n");
      out.write("\t\tarray.push(obj);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tfor(var i=0;i<checknodes.length;i++){\r\n");
      out.write("\t\t\tvar node=checknodes[i];\r\n");
      out.write("\t\t\tif(node.id!=null&&node.id!=''){\r\n");
      out.write("\t\t\t\tvar obj={};\r\n");
      out.write("\t\t\t\tobj.userguid=userguid;\r\n");
      out.write("\t\t\t\tobj.deptguid=node.id;\r\n");
      out.write("\t\t\t\tarray.push(obj);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//参数\r\n");
      out.write("\tvar data={userguid:userguid,list:array};\r\n");
      out.write("\t$.ajax({  \r\n");
      out.write("        url: \"system/saveUserDepartment.do\",  \r\n");
      out.write("        contentType: \"application/json; charset=utf-8\",  \r\n");
      out.write("        type: \"POST\",  \r\n");
      out.write("        dataType: \"json\",  \r\n");
      out.write("        data: JSON.stringify(data),\r\n");
      out.write("        success: function(result) { \r\n");
      out.write("        \talert('授权成功！');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//新增筛选列表的数据\r\n");
      out.write("var add=false;\r\n");
      out.write("var filterguid;\r\n");
      out.write("var filterForm=null\r\n");
      out.write("function addOrUpdateFilter(state,filterguid){\r\n");
      out.write("\tadd=state;\r\n");
      out.write("\t$(\"#addFilterWindow\").dialog({\r\n");
      out.write("\t\tautoOpen: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\twidth:500,\r\n");
      out.write("\t\tbuttons: {\r\n");
      out.write("\t\t\t\"确定\": function() {\r\n");
      out.write("\t\t\t\t$(\"#filterForm input[id=filterguid]\").val(filterguid);\r\n");
      out.write("\t\t\t\tsaveFilter();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"取消\": function() {\r\n");
      out.write("\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\topen:function(){\r\n");
      out.write("\t\t\t$(\"#filterForm\").clearForm();\r\n");
      out.write("\t\t\tformDisabled(false,\"#filterForm\");\r\n");
      out.write("\t\t\tif(!add){\r\n");
      out.write("\t\t\t\tloadFilter(filterguid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfilterForm=$(\"#filterForm\").validate({submitHandler: function(form) {\r\n");
      out.write("\t\t    \t$(form).ajaxSubmit(function(data) {\r\n");
      out.write("\t\t    \t\tmygrid.reload();\r\n");
      out.write("\t\t    \t\t$(\"#addFilterWindow\").dialog(\"close\");\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//通过列表的id加载数据\r\n");
      out.write("function loadFilter(filterguid){\r\n");
      out.write("\t$.getJSON(\"system/getResumeFilterById.do\",{id:filterguid},function(data){\r\n");
      out.write("\t\tfor(var key in data){\r\n");
      out.write("\t\t\tif($('#filterForm input[id='+key+']')){\r\n");
      out.write("\t\t\t\t$('#filterForm input[id='+key+']').val(data[key]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}    \t\t\t\t\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//保存\r\n");
      out.write("function saveFilter(){\r\n");
      out.write("\t$(\"#filterForm\").submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//全选\r\n");
      out.write("function selectAll(el){\r\n");
      out.write("\tvar input=$(el);\r\n");
      out.write("\t$(\"input[name='mychecked']\").attr(\"checked\",input.attr(\"checked\"));\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//保存赋权(用户赋予筛选条件)\r\n");
      out.write("function saveUserFilter(){\r\n");
      out.write("\tvar userguid= $(\"#userguid\").val();\r\n");
      out.write("\tif(userguid==null||userguid=='')\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\t$(\"input[name='mychecked']:checked\").each(function(){\r\n");
      out.write("\t\tarray.push($(this).val());\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//参数\r\n");
      out.write("\tvar data={userguid:userguid,list:array};\r\n");
      out.write("\t$.ajax({  \r\n");
      out.write("        url: \"system/saveUserFilter.do\",  \r\n");
      out.write("        contentType: \"application/json; charset=utf-8\",  \r\n");
      out.write("        type: \"POST\",  \r\n");
      out.write("        dataType: \"json\",  \r\n");
      out.write("        data: JSON.stringify(data),\r\n");
      out.write("        success: function(result) { \r\n");
      out.write("        \talert('授权成功！');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//筛选列表\r\n");
      out.write("var mygrid=null;\r\n");
      out.write("function loadGrid(){\r\n");
      out.write("\tvar size=getGridSize();\r\n");
      out.write("\tvar grid_demo_id = \"myGrid1\";\r\n");
      out.write("\tvar dsOption= {\r\n");
      out.write("\t\t\tfields :[\r\n");
      out.write("\t\t\t\t{name : 'filterguid'},\r\n");
      out.write("\t\t\t\t{name : 'filterconditions'},\r\n");
      out.write("\t\t\t\t{name : 'code'},\r\n");
      out.write("\t\t\t\t{name : 'tablecolumnname'}\r\n");
      out.write("\t\t\t]\r\n");
      out.write("\t\t};\r\n");
      out.write("\tvar colsOption = [\r\n");
      out.write("\t\t\t{id: 'filterguid' ,headAlign:'center',align:'center',width :50,sortable:false,hdRenderer:function(header,colObj,grid){\r\n");
      out.write("\t\t\t\treturn '<input type=\"checkbox\" onclick=\"selectAll(this);\"/>';\r\n");
      out.write("\t\t\t},renderer:function(value,record,colObj,grid,colNo,rowNo){\r\n");
      out.write("\t\t\t\tvar htm='&nbsp;';\r\n");
      out.write("\t\t\t\thtm+='<label for=\"'+record.filterguid+'\">';\r\n");
      out.write("\t\t\t\tif(record.checked==true)\r\n");
      out.write("   \t\t\t  \t\thtm+='<input name=\"mychecked\" value=\"'+record.filterguid+'\" type=\"checkbox\" checked/>';\r\n");
      out.write("  \t\t\t  \telse\r\n");
      out.write("   \t\t\t  \t\thtm+='<input name=\"mychecked\" value=\"'+record.filterguid+'\" type=\"checkbox\"/>';\r\n");
      out.write("   \t\t\t  \thtm+='</label>';\r\n");
      out.write(" \t\t\t  \treturn htm;\r\n");
      out.write("\t\t\t}},\r\n");
      out.write("          \t{id: 'tablecolumnname' , header: \"列名\" ,headAlign:'center',align:'left', width :120},\r\n");
      out.write("      \t   \t{id: 'code' , header: \"符号\",headAlign:'center',align:'center', width :70},\r\n");
      out.write("      \t   \t{id: 'filterconditions' , header: \"筛选条件\",headAlign:'center', width :250},\r\n");
      out.write("      \t  \t{id: 'memo' , header: \"条件备注\",headAlign:'center', width :250}\r\n");
      out.write("      \t];\r\n");
      out.write("\tvar gridOption={\r\n");
      out.write("\t\tid : grid_demo_id,\r\n");
      out.write("\t\tloadURL : 'system/searchResumeFilter.do',\r\n");
      out.write("\t\tbeforeLoad:function(reqParam){\r\n");
      out.write("\t\t\treqParam['parameters']={'userid':userid};\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\twidth:'99.5%',\r\n");
      out.write("\t\theight:\"465\",  //\"100%\", // 330,\r\n");
      out.write("\t\tcontainer : 'gridbox',\r\n");
      out.write("\t\tautoLoad:false,\r\n");
      out.write("\t\tselectRowByCheck:true,\r\n");
      out.write("\t\treplaceContainer : true,\r\n");
      out.write("\t\tdataset : dsOption ,\r\n");
      out.write("\t\tcolumns : colsOption,\r\n");
      out.write("\t\ttoolbarContent : 'nav | pagesize  state',\r\n");
      out.write("\t\tpageSizeList : [size,size*2,size*4,size*6,size*8,size*10],\r\n");
      out.write("\t\tpageSize:size,\r\n");
      out.write("\t\tskin:getGridSkin(),\r\n");
      out.write("\t\tonDblClickCell:function(value, record , cell, row, colNO, rowNO,columnObj,grid){\r\n");
      out.write("\t\t\tif(colNO!=0){\r\n");
      out.write("\t\t\t\taddOrUpdateFilter(false,record.filterguid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tmygrid=new Sigma.Grid( gridOption );\r\n");
      out.write("\tSigma.Util.onLoad( Sigma.Grid.render(mygrid) );\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"table\">\r\n");
      out.write("\t\t\t<div class=\"table-bar\">\r\n");
      out.write("\t\t\t\t<div class=\"table-title\">\r\n");
      out.write("\t\t\t\t\t表格名称\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-ctrl\">\r\n");
      out.write("\t\t\t\t\t<!-- 基本信息-->\r\n");
      out.write("\t\t\t\t\t<span id=\"group0\" class=\"gruop_hidden\">\r\n");
      out.write("\t\t\t\t\t   \t<span id=\"b1\">\r\n");
      out.write("\t\t\t\t\t   \t\t<a class=\"btn\" href=\"javascript:expGrid();\"><i class=\"icon icon-download\"></i><span>导出</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"new\" class=\"btn\" href=\"javascript:addNode();\" style=\"display:none;\"><i class=\"icon icon-plus\"></i><span>新增</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"edit\" class=\"btn\" href=\"javascript:editNode();\" style=\"display:none;\"><i class=\"icon icon-pencil\"></i><span>修改</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"recover\" class=\"btn\" href=\"javascript:recoverUser(1);\"  style=\"display:none;\"><i class=\"icon icon-repeat\"></i><span>恢复</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"remove\"  class=\"btn\" href=\"javascript:del();\"  style=\"display:none;\"><i class=\"icon icon-remove\"></i><span>删除</span></a>\r\n");
      out.write("\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t   \t\t<span id=\"b2\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn\"  href=\"javascript:save();\"><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn\"  href=\"javascript:onCancel();\"><i class=\"icon icon-share\"></i><span>取消</span></a>\r\n");
      out.write("\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t   \t<!-- 角色赋权-->\r\n");
      out.write("\t\t\t\t   \t<span id=\"group1\" class=\"gruop_hidden\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t   \t\t<a class=\"btn save\"  href=\"javascript:saveUserPost();\"><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t   \t<!-- 公司赋权-->\r\n");
      out.write("\t\t\t\t   \t<span id=\"group2\" class=\"gruop_hidden\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn save\"  href=\"javascript:saveUserCompany();\"><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t   \t<!-- 通讯录赋权-->\r\n");
      out.write("\t\t\t\t   \t<span id=\"group3\" class=\"gruop_hidden\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn save\"  href=\"javascript:saveUserAddressCompany();\"><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t   \t \t<!-- 部门赋权-->\r\n");
      out.write("\t\t\t\t   \t<span id=\"group4\"class=\"gruop_hidden\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn save\"  href=\"javascript:saveUserdepartment();\"><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t   \t<!-- 筛选赋权-->\r\n");
      out.write("\t\t\t\t   \t<span id=\"group5\" class=\"gruop_hidden\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn save\" href=\"javascript:addOrUpdateFilter(true);\" ><i class=\"icon icon-plus\"></i><span>新增</span></a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"btn save\" href=\"javascript:saveUserFilter();\"><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"table-wrapper\" id=\"myContent\" style=\"height:550px;\">\r\n");
      out.write("\t\t\t\t<div class=\"ui-layout-west\" id=\"myWest\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ui-layout-north\">\r\n");
      out.write("\t\t\t\t\t\t<table width=\"100%\" height=\"100%\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"padding-left:1px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"myMarker\" id=\"myMarker\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"ui-layout-center\" style=\"border:0px;\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"tree\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"ui-layout-center\">\r\n");
      out.write("\t\t\t\t\t<div id=\"mytab\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#tab0\">基本信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#tab1\">角色赋权</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#tab2\">公司赋权</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#tab3\">通讯录赋权</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#tab4\">部门赋权</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#tab5\">筛选赋权</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tab0\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"system/saveOrUpdateUser.do\" method=\"post\" id=\"myForm\" class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"userguid\" name=\"userguid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"state\" name=\"state\" type=\"hidden\" value=\"1\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"isadmin\" name=\"isadmin\" type=\"hidden\" value=\"0\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<legend>基本信息</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span><em class=\"red\">* </em>用户名：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"employeeid\" name=\"employeeid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"username\" name=\"username\" class=\"inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span><em class=\"red\">* </em>登录名：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"loginname\" name=\"loginname\" class=\"{required:true,maxlength:20} inputstyle\" onblur=\"checklogname();\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul id=\"myPassword\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span><em class=\"red\">* </em>密码：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"password\" name=\"password\" type=\"password\" class=\"{required:true,maxlength:5} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span>备注：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <textarea id=\"memo\" name=\"memo\"  rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t       </form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tab1\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"roleTree\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tab2\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"companyTree\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tab3\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"addressTree\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tab4\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"departmentTree\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tab5\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"padding-top:5px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"myTable\" style=\"margin:0px auto;height:500px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"gridbox\" ></div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- 添加窗口 -->\r\n");
      out.write("<div id=\"addFilterWindow\" title=\"添加筛选列表\" style=\"display:none\">\r\n");
      out.write("\t<form action=\"system/saveOrUpdateFilter.do\" id=\"filterForm\"  method=\"post\" class=\"form\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"filterguid\" name=\"filterguid\" value=\"\"/>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>列名：</span>\r\n");
      out.write("\t\t\t\t<input id=\"tablecolumnname\" name=\"tablecolumnname\" class=\"{required:true,maxlength:100} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>符号：</span>\r\n");
      out.write("\t\t\t\t<input id=\"code\" name=\"code\" class=\"{required:true,maxlength:25} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<span><em class=\"red\">* </em>筛选条件：</span>\r\n");
      out.write("\t\t\t\t<input  id=\"filterconditions\" name=\"filterconditions\" class=\"{required:true,maxlength:100} inputstyle\"/>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
