package org.apache.jsp.pages.department;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_005fpost1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>岗位管理</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\"/>    \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/style.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/form.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/jquery-ui-1.8.15.custom.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeStyle.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeIcons.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/gt_grid.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/default/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/green/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/mac/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/china/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/vista/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/calendar/calendar-blue.css\"  />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/public.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.layout.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-ui-1.8.5.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/tree/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/lib/jquery.metadata.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-en.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-setup.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_grid_all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_msg_cn.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"pages/department/post.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"pages/tree.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"pages/treedrag.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t//tab页\r\n");
      out.write("\tloadTab();\r\n");
      out.write("\t\r\n");
      out.write("\t//加载布局\r\n");
      out.write("\t$('#myContent').layout({\r\n");
      out.write("        west: {size:\"300\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\t$('#myWest').layout({\r\n");
      out.write("        north: {size:\"28\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\t//树的展示\r\n");
      out.write("\tbuildDepartmentQuotaTree();\r\n");
      out.write("\t\r\n");
      out.write("\t//加载数据\r\n");
      out.write("\tloadGrid();\r\n");
      out.write("\t\r\n");
      out.write("\t//编制\r\n");
      out.write("\t//loadQuotaGrid();\r\n");
      out.write("\t\r\n");
      out.write("\t  //加载表单验证\r\n");
      out.write("    $(\"#myForm\").validate();\r\n");
      out.write("    $('#myForm').ajaxForm(function(data) {\r\n");
      out.write("    \talert(\"保存成功！\");\r\n");
      out.write("    \t\r\n");
      out.write("        //节点处理\r\n");
      out.write("    \tvar nameValue=data.postname;\r\n");
      out.write("    \tif(add){//新增\r\n");
      out.write("    \t\tvar newNode = {id:data.postid, name:nameValue,iconSkin:\"post\",code:\"post\",state:1,ename:data.companyid};\r\n");
      out.write("       \t\tzTree.addNodes(selectNode, newNode);\r\n");
      out.write("        }else{\r\n");
      out.write("        \tselectNode.name = nameValue;\r\n");
      out.write("   \t\t\tzTree.updateNode(selectNode);\r\n");
      out.write("   \t\t\tzTree.selectNode(selectNode);\r\n");
      out.write("        }\r\n");
      out.write("    \tadd=false;\r\n");
      out.write("    \t//不可编辑\r\n");
      out.write("    \tformDisabled(true);\r\n");
      out.write("    \t\r\n");
      out.write("    \t//取消状态\r\n");
      out.write("    \tonCancel();\r\n");
      out.write("    });\r\n");
      out.write("\t//把表单置为不可编辑\r\n");
      out.write("    formDisabled(true);\r\n");
      out.write("\t\r\n");
      out.write("    //日期\r\n");
      out.write("    $(\".datepicker\").datepicker({\r\n");
      out.write("        dateFormat: 'yy-mm-dd',\r\n");
      out.write("       \tbeforeShow: function(input, inst) {\r\n");
      out.write("   \t\t\tif($(input).attr(\"readonly\"))\r\n");
      out.write("   \t\t\t\tinst.inline=true;\r\n");
      out.write("   \t\t}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("    //关闭等待层\r\n");
      out.write("    if(window.parent.hidenLoading)\r\n");
      out.write("    \twindow.parent.hidenLoading();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//树\r\n");
      out.write("var zTree;\r\n");
      out.write("//选中节点\r\n");
      out.write("var selectNode=null;\r\n");
      out.write("function buildDepartmentQuotaTree(){\r\n");
      out.write("\t//配置\r\n");
      out.write("\tvar setting = {\r\n");
      out.write("\t\t\tedit: {\r\n");
      out.write("\t\t\t\tdrag: {\r\n");
      out.write("\t\t\t\t\tautoExpandTrigger: true,\r\n");
      out.write("\t\t\t\t\tprev: dropPrev,\r\n");
      out.write("\t\t\t\t\tinner: dropInner,\r\n");
      out.write("\t\t\t\t\tnext: dropNext\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tenable: true,\r\n");
      out.write("\t\t\t\tshowRemoveBtn: false,\r\n");
      out.write("\t\t\t\tshowRenameBtn: false\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcallback:{\r\n");
      out.write("\t\t\t\tbeforeDrag: beforeDrag,\r\n");
      out.write("\t\t\t\tbeforeDrop: beforeDrop,\r\n");
      out.write("\t\t\t\tbeforeDragOpen: beforeDragOpen,\r\n");
      out.write("\t\t\t\tonDrag: onDrag,\r\n");
      out.write("\t\t\t\tonDrop: onDrop,\r\n");
      out.write("\t\t\t\tbeforeClick: function(treeId, treeNode) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#myForm\").clearForm();\r\n");
      out.write("\t\t\t\t\t\tselectNode=treeNode;\r\n");
      out.write("\t\t\t\t\t\tformDisabled(true);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t//出现按钮组一\r\n");
      out.write("\t\t\t\t\t\t$('#b1').show();\r\n");
      out.write("\t\t\t\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\t\t\tif(selectNode.code=='dept'){\r\n");
      out.write("\t\t\t\t\t\t\t$('#new').show();\r\n");
      out.write("\t\t\t\t\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t\t\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#deptid\").val(selectNode.id);\r\n");
      out.write("\t\t\t\t\t\t}else if(selectNode.code=='post'){\r\n");
      out.write("\t\t\t\t\t\t\tif(selectNode.state==1){\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#edit').show();\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#del').show();\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#new').hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t}else if(selectNode.state==0){\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#new').hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#recover\").show();\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#remove\").show();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#postid\").val(selectNode.id);\r\n");
      out.write("\t\t\t\t\t\t\tloadPostById(selectNode.id);\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t\t\t\t\t$('#new').hide();\r\n");
      out.write("\t\t\t\t\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#companyid\").val(selectNode.id);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t//myQuotagrid.reload();\r\n");
      out.write("\t\t\t\t\t\t//loadQuotaGrid();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tview: {\r\n");
      out.write("\t\t\t\t\tfontCss: getDeptFontCss\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\r\n");
      out.write("\tvar myvalid=$(\"#myrankvalid\").attr(\"checked\")?1:0;\r\n");
      out.write("    $.getJSON(\"department/buildMyPostTree.do\",{valid:myvalid}, function(tdata) {\r\n");
      out.write("    \tzTree = $.fn.zTree.init($(\"#tree\"),setting, tdata);\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("\t//邦定定位事件\r\n");
      out.write("\t$(\"#myMarker\").bind(\"keyup\",markTreeNode);\r\n");
      out.write("\t$(\"#myMarker\").bind(\"blur\",markSelectTreeNode);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//节点搜索定位\r\n");
      out.write("function markSelectTreeNode(){\r\n");
      out.write("\tvar value=\"\";\r\n");
      out.write("\tvalue = $.trim($(\"#myMarker\").val());\r\n");
      out.write("\tif (value != \"\"){\r\n");
      out.write("\t\tnodeList = zTree.getNodesByParamFuzzy(\"name\", value);\r\n");
      out.write("\t\tif(nodeList.length<=0)\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\tfor( var i=0, l=nodeList.length; i<l; i++) {\r\n");
      out.write("\t\t\tvar node=nodeList[i];\r\n");
      out.write("\t\t\tif(i==0){\r\n");
      out.write("\t\t\t\tzTree.selectNode(node);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("//节点搜索变色\r\n");
      out.write("function markTreeNode(e) {\r\n");
      out.write("\tif(!nodeState){\r\n");
      out.write("\t\tnodeState=true;\r\n");
      out.write("\t\tvar value=\"\";\r\n");
      out.write("\t\tvalue = $.trim($(\"#myMarker\").val());\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tchangeNodesColor(false);\r\n");
      out.write("\t\tif (value === \"\"){\r\n");
      out.write("\t\t\tnodeState=false;\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tnodeList = zTree.getNodesByParamFuzzy(\"name\", value);\r\n");
      out.write("\t\tchangeNodesColor(true);\r\n");
      out.write("\t\tnodeState=false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function changeNodesColor(highlight) {\r\n");
      out.write("\tif(nodeList.length<=0)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tfor( var i=0, l=nodeList.length; i<l; i++) {\r\n");
      out.write("\t\tvar node=nodeList[i];\r\n");
      out.write("\t\tnode.highlight = highlight;\r\n");
      out.write("\t\tzTree.updateNode(nodeList[i]);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function getDeptFontCss(treeId, treeNode) {\r\n");
      out.write("\treturn (!!treeNode.highlight) ? {color:\"#ff0000\", \"font-weight\":\"bold\"} : {color:\"#333\", \"font-weight\":\"normal\"};\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//节点排序\r\n");
      out.write("function onDrop(event, treeId, treeNodes, targetNode, moveType, isCopy) {\r\n");
      out.write("\tif(treeNodes.lenght>0){\r\n");
      out.write("\t\talert(\"请选择1个节点进行排序！\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(targetNode==null\t)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tselectNode=treeNodes[0];\r\n");
      out.write("\t$.post(\"department/orderPost.do\",{id:selectNode.id,targetid:targetNode.id,moveType:moveType}, function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("//========================================\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("//tab页\r\n");
      out.write("var tabIndex=0;\r\n");
      out.write("function loadTab(){\r\n");
      out.write("\t$(\"#mytab\").tabs({\r\n");
      out.write("    \tselect: function(event, ui) {\r\n");
      out.write("    \t\ttabIndex=ui.index;\r\n");
      out.write("    \t\t$(\".gruop_hidden\").hide();\r\n");
      out.write("    \t\t$(\"#tab\"+tabIndex).show();\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t//控制tab\r\n");
      out.write("    \t\t\r\n");
      out.write("\t\t\tif(selectNode!=null){\r\n");
      out.write("\t\t\t\t$(\"#group\"+tabIndex).show();\r\n");
      out.write("\t\t\t\tif(tabIndex==1){\r\n");
      out.write("\t\t\t\t\tmygrid.reload();\r\n");
      out.write("\t\t\t\t}else if(tabIndex==2){\r\n");
      out.write("\t\t\t\t\tmyQuotagrid.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#group\"+tabIndex).hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("    \t}\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//post的保存\r\n");
      out.write("var add=false;\r\n");
      out.write("function addPost(){\r\n");
      out.write("\t$('#b1').hide();\r\n");
      out.write("\t$('#b2').show();\r\n");
      out.write("\t$(\"#bzlb1\").show();\r\n");
      out.write("\t$(\"#bzrs1\").show();\r\n");
      out.write("\t$(\"#bzlb2\").show();\r\n");
      out.write("\t$(\"#bzrs2\").show();\r\n");
      out.write("\t$(\"#myForm\").clearForm();\r\n");
      out.write("\tadd=true;\r\n");
      out.write("\tformDisabled(false);\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#deptid\").val(selectNode.id);\r\n");
      out.write("\t$(\"#companyid\").val(selectNode.ename);\r\n");
      out.write("\t$(\"#state\").val(1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//保存岗位\r\n");
      out.write("function save(){\r\n");
      out.write("\tverificationPostname();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//修改岗位\r\n");
      out.write("function editPost(){\r\n");
      out.write("\t$(\"#b1\").hide();\r\n");
      out.write("\t$(\"#b2\").show();\r\n");
      out.write("\t$(\"#bzlb1\").hide();\r\n");
      out.write("\t$(\"#bzrs1\").hide();\r\n");
      out.write("\t$(\"#bzlb2\").hide();\r\n");
      out.write("\t$(\"#bzrs2\").hide();\r\n");
      out.write("\tformDisabled(false);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//取消\r\n");
      out.write("function onCancel(){\r\n");
      out.write("\tif(selectNode!=null){\r\n");
      out.write("\t\tif(selectNode.code=='dept'){\r\n");
      out.write("\t\t\t$('#b1').show();\r\n");
      out.write("\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#new').show();\r\n");
      out.write("\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t}else if(selectNode.code=='post'){\r\n");
      out.write("\t\t\tloadPostById(selectNode.id)\r\n");
      out.write("\t\t\t$('#b1').show();\r\n");
      out.write("\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#del').show();\r\n");
      out.write("\t\t\t$('#edit').show();\r\n");
      out.write("\t\t\t$('#new').hide();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tformDisabled(true);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//验证保存的岗位名是否重复\r\n");
      out.write("function verificationPostname(){\r\n");
      out.write("\tvar postid=$(\"#postid\").val();\r\n");
      out.write("\tvar postname=$(\"#postname\").val();\r\n");
      out.write("\t$.post(\"department/verificationPostname.do\",{postid:postid,deptid:selectNode.id,postname:postname},function(msg){\r\n");
      out.write("\t\tif(msg!=''&&msg!=null){\r\n");
      out.write("\t\t\talert(msg);\r\n");
      out.write("\t\t\t$(\"#postname\").val(null);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar budgettype2=$(\"#budgettype2\").val();\r\n");
      out.write("\t\t\tvar budgettype1=$(\"#budgettype1\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//判断不同的编制类别\r\n");
      out.write("\t\t\tif(budgettype1!=null&&budgettype1!=''&&budgettype2!=null&&budgettype2!=''){\r\n");
      out.write("\t\t\t\tif(budgettype1==budgettype2){\r\n");
      out.write("\t\t\t\t\talert(\"请选择不同的编制类别!\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#myForm\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//输入input的时候也要校验\r\n");
      out.write("function checkPostname(){\r\n");
      out.write("\tvar postid=$(\"#postid\").val();\r\n");
      out.write("\tvar postname=$(\"#postname\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t$.post(\"department/verificationPostname.do\",{postid:postid,deptid:selectNode.id,postname:postname},function(msg){\r\n");
      out.write("\t\tif(msg!=''&&msg!=null){\r\n");
      out.write("\t\t\talert(msg);\r\n");
      out.write("\t\t\t$(\"#postname\").val(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//通过岗位id加载岗位信息\r\n");
      out.write("function loadPostById(postguid){\r\n");
      out.write("\t$(\"#myForm\").clearForm();\r\n");
      out.write("\t$.getJSON(\"department/getPostByPostId.do\",{id:postguid},function(data){\r\n");
      out.write("\t\tif(data!=null){\r\n");
      out.write("\t\t\tfor (var key in data) {\r\n");
      out.write("\t\t        var el = $('#' + key);\r\n");
      out.write("\t\t        if(el) \r\n");
      out.write("\t\t            el.val(data[key]);\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//控制tab\r\n");
      out.write("\t\t\tif(selectNode!=null){\r\n");
      out.write("\t\t\t\t$(\"#group\"+tabIndex).show();\r\n");
      out.write("\t\t\t\tif(tabIndex==1){\r\n");
      out.write("\t\t\t\t\tmygrid.reload();\r\n");
      out.write("\t\t\t\t}else if(tabIndex==2){\r\n");
      out.write("\t\t\t\t\tmyQuotagrid.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#group\"+tabIndex).hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//删除岗位列表的数据\r\n");
      out.write("function delPostById(){\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tarray.push(selectNode.id);\r\n");
      out.write("\tif(!confirm('确认要删除选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write(" \t$.post(\"department/delPostById.do\",{ids:array.toString()}, function() {\r\n");
      out.write(" \t\tzTree.removeNode(selectNode);\r\n");
      out.write(" \t\t$(\"#myForm\").clearForm();\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t$('#b1').show();\r\n");
      out.write("\t\t$('#b2').hide();\r\n");
      out.write(" \t\t\r\n");
      out.write("\t\t$('#del').hide();\r\n");
      out.write("\t\t$('#edit').hide();\r\n");
      out.write("\t\t$('#new').hide();\r\n");
      out.write(" \t\tformDisabled(true);\r\n");
      out.write("  \t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//岗位信息的单个的失效或者还原生效\r\n");
      out.write("function invalidOrReductionPostById(valid){\r\n");
      out.write("\tif(selectNode==null)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tvar array=new Array();\r\n");
      out.write("\tarray.push(selectNode.id);\r\n");
      out.write("\tif(!confirm('确认要'+(valid==0?'失效':'恢复')+'选中数据吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.post(\"department/invalidOrReductionPostById.do\",{ids:array.toString(),state:valid}, function() {\r\n");
      out.write("\t\tif(valid==0){\r\n");
      out.write("\t\t\tselectNode.iconSkin = \"remove\";\r\n");
      out.write("\t\t\tselectNode.state=0;\r\n");
      out.write("\t\t\tzTree.updateNode(selectNode);\r\n");
      out.write("\t\t\t$('#b1').show();\r\n");
      out.write("\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t$('#new').hide();\r\n");
      out.write("\t\t\t$(\"#recover\").show();\r\n");
      out.write("\t\t\t$(\"#remove\").show();\r\n");
      out.write("\t\t\tformDisabled(true);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tselectNode.iconSkin = \"post\";\r\n");
      out.write("\t\t\tselectNode.state=1;\r\n");
      out.write("\t\t\tzTree.updateNode(selectNode);\r\n");
      out.write("\t\t\t$('#b1').show();\r\n");
      out.write("\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#del').show();\r\n");
      out.write("\t\t\t$('#edit').show();\r\n");
      out.write("\t\t\t$('#new').hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\tformDisabled(true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//参数设置\r\n");
      out.write("var pam=null;\r\n");
      out.write("function initPagePam(){\r\n");
      out.write("\tpam={};\r\n");
      out.write("\tpam.expAll=0;\r\n");
      out.write("\tif(selectNode!=null){\r\n");
      out.write("\t\tpam.postid=selectNode.id;\r\n");
      out.write("\t\tpam.isstaff=1;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//导出部门岗位\r\n");
      out.write("function expPostTree(){\r\n");
      out.write("\twindow.open(\"department/exportPost.do\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//人员信息\r\n");
      out.write("var mygrid=null;\r\n");
      out.write("function loadGrid(){\r\n");
      out.write("\tvar size=20;\r\n");
      out.write("\tvar wh=$(document.body).outerWidth()-360;\r\n");
      out.write("\t$(\"#myTable\").css({width:wh,height:460});\r\n");
      out.write("\t\r\n");
      out.write("\tvar grid_demo_id = \"myGrid1\";\r\n");
      out.write("\tvar dsOption = {\r\n");
      out.write("\t\tfields :[\r\n");
      out.write("\t\t\t\t{name : 'employeeid'},\r\n");
      out.write("\t\t\t\t{name : 'name'},\r\n");
      out.write("\t\t\t\t{name : 'sex'},\r\n");
      out.write("\t\t\t\t{name : 'birthday'},\r\n");
      out.write("\t\t\t\t{name : 'cardnumber'},\r\n");
      out.write("\t\t\t\t{name : 'culture'},\r\n");
      out.write("\t\t\t\t{name : 'nation'},\r\n");
      out.write("\t\t\t\t{name : 'mobile'},\r\n");
      out.write("\t\t\t\t{name : 'residenceplace'},\r\n");
      out.write("\t\t\t\t{name : 'homephone'},\r\n");
      out.write("\t\t\t\t{name : 'homeplace'},\r\n");
      out.write("\t\t\t\t{name : 'bloodtype'},\r\n");
      out.write("\t\t\t\t{name : 'domicilplace'},\r\n");
      out.write("\t\t\t\t{name : 'nativeplace'},\r\n");
      out.write("\t\t\t\t{name : 'politics'},\r\n");
      out.write("\t\t\t\t{name : 'married'},\r\n");
      out.write("\t\t\t\t{name : 'privateemail'},\r\n");
      out.write("\t\t\t\t{name : 'photo'},\r\n");
      out.write("\t\t\t\t{name : 'joinworkdate'},\r\n");
      out.write("\t\t\t\t{name : 'joingroupdate'},\r\n");
      out.write("\t\t\t\t{name : 'workstate'},\r\n");
      out.write("\t\t\t\t{name : 'jobnumber'},\r\n");
      out.write("\t\t\t\t{name : 'secrecy'},\r\n");
      out.write("\t\t\t\t{name : 'dorder'},\r\n");
      out.write("\t\t\t\t{name : 'classification'},\r\n");
      out.write("\t\t\t\t{name : 'employtype'},\r\n");
      out.write("\t\t\t\t{name : 'checknumber'},\r\n");
      out.write("\t\t\t\t{name : 'joindate'},\r\n");
      out.write("\t\t\t\t{name : 'startdate'},\r\n");
      out.write("\t\t\t\t{name : 'enddate'},\r\n");
      out.write("\t\t\t\t{name : 'officephone'},\r\n");
      out.write("\t\t\t\t{name : 'email'},\r\n");
      out.write("\t\t\t\t{name : 'shortphone'},\r\n");
      out.write("\t\t\t\t{name : 'officeaddress'},\r\n");
      out.write("\t\t\t\t{name : 'studymonth'},\r\n");
      out.write("\t\t\t\t{name : 'officialdateplan'},\r\n");
      out.write("\t\t\t\t{name : 'officialdate'},\r\n");
      out.write("\t\t\t\t{name : 'officialmemo'},\r\n");
      out.write("\t\t\t\t{name : 'resignationdate'},\r\n");
      out.write("\t\t\t\t{name : 'resignationreason'},\r\n");
      out.write("\t\t\t\t{name : 'interfacecode'},\r\n");
      out.write("\t\t\t\t{name : 'contactphone'},\r\n");
      out.write("\t\t\t\t{name : 'contactrelationship'},\r\n");
      out.write("\t\t\t\t{name : 'contactname'},\r\n");
      out.write("\t\t\t\t{name : 'memo'},\r\n");
      out.write("\t\t\t\t{name : 'modiuser'},\r\n");
      out.write("\t\t\t\t{name : 'moditimestamp'},\r\n");
      out.write("\t\t\t\t{name : 'modimemo'},\r\n");
      out.write("\t\t\t\t{name : 'secrecyname'},\r\n");
      out.write("\t\t\t\t{name : 'sexname'},\r\n");
      out.write("\t\t\t\t{name : 'culturename'},\r\n");
      out.write("\t\t\t\t{name : 'nationname'},\r\n");
      out.write("\t\t\t\t{name : 'bloodtypename'},\r\n");
      out.write("\t\t\t\t{name : 'politicsname'},\r\n");
      out.write("\t\t\t\t{name : 'marriedname'},\r\n");
      out.write("\t\t\t\t{name : 'resignationreasonname'},\r\n");
      out.write("\t\t\t\t{name : 'classificationname'},\r\n");
      out.write("\t\t\t\t{name : 'employtypename'},\r\n");
      out.write("\t\t\t\t{name : 'contactrelationshipname'},\r\n");
      out.write("\t\t\t\t{name : 'state'},\r\n");
      out.write("\t\t\t\t{name : 'isstaff'},\r\n");
      out.write("\t\t\t\t{name : 'isstaffname'},\r\n");
      out.write("\t\t\t\t{name : 'domicilplacename'}\r\n");
      out.write("\t\t\t]\r\n");
      out.write("\t    };\r\n");
      out.write("\t\tvar colsOption = [\r\n");
      out.write("\t    \t\t\t{id: '选择' ,isCheckColumn : true, editable:false,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'workstatename' , header: \"状态\" , width :60 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'companyname' , header: \"公司名称\" , width :200 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t    \t\t\t{id: 'deptname' , header: \"部门名称\" , width :150 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t    \t\t\t{id: 'postname' , header: \"岗位名称\" , width :120 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t    \t\t\t{id: 'dorder' , header: \"排序号\" , width :80 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t    \t\t\t{id: 'jobnumber' , header: \"工号\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'name' , header: \"姓名\" , width :80 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t    \t\t\t{id: 'email' , header: \"公司邮箱\" , width :150 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'shortphone' , header: \"手机内网号码\" , width :120 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'classificationname' , header: \"员工类别\" , width :80 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'employtypename' , header: \"用工性质\" , width :80 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'jobname' , header: \"职务\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'rankname' , header: \"职级\" , width :100 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t    \t\t\t{id: 'quotaname' , header: \"编制类别\" , width :120 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'cardnumber', header: \"身份证号码\", width :180 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'birthday' , header: \"出生日期\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'sexname' , header: \"性别\" , width :60 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'birthdayname' , header: \"年龄\" , width :50 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'culturename' , header: \"学历情况\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'nationname' , header: \"民族\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'mobile' , header: \"手机\" , width :120 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'addressmobile' , header: \"通讯录手机\" , width :120 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'domicilplacename' , header: \"户籍类型\" , width :200 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t    \t\t\t{id: 'nativeplace' , header: \"籍贯\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'politicsname' , header: \"政治面貌\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'marriedname' , header: \"婚姻状况\" , width :100 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'bloodtypename' , header: \"血型\" , width :100 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'joinworkdate' , header: \"参加工作时间\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'joingroupdate' , header: \"加入集团时间\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'secrecyname' , header: \"员工信息保密\" , width :100 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'checknumber' , header: \"考勤号\" , width :80 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'joindate' , header: \"加入公司时间\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'startdate' , header: \"聘任开始时间\" , width :120 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'enddate' , header: \"聘任结束时间\" , width :120 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'officephone' , header: \"办公电话\" , width :80 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'officeaddress' , header: \"办公地址\" , width :200 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'residenceplace' , header: \"身份证地址\" , width :200 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'homeplace' , header: \"家庭住址\" , width :200 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'homephone' , header: \"家庭电话\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'privateemail' , header: \"私人邮箱\" , width :150 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'contactname' , header: \"紧急联系人\" , width :80 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'contactrelationshipname' , header: \"与紧急联系关系\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'contactphone' , header: \"紧急联系人电话\" , width :150 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'studymonth' , header: \"试用期（月）\" , width :80 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'officialdateplan' , header: \"计划转正时间\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'officialdate' , header: \"转正时间\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'officialmemo' , header: \"转正备注\" , width :200 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'resignationdate' , header: \"离职时间\" , width :90 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'resignationreasonname' , header: \"离职原因\" , width :100 ,headAlign:'center'},\r\n");
      out.write("\t    \t\t\t{id: 'modimemo' , header: \"备注\" , width :200 ,headAlign:'center',headAlign:'left',align:'left'}\r\n");
      out.write("\t    \t\t];\r\n");
      out.write("    \tvar gridOption={\r\n");
      out.write("    \t\tid : grid_demo_id,\r\n");
      out.write("    \t\tloadURL :'employee/searchEmployee.do',\r\n");
      out.write("    \t\tbeforeLoad:function(reqParam){\r\n");
      out.write("    \t\t\tinitPagePam();\r\n");
      out.write("    \t\t\treqParam['parameters']=pam;\r\n");
      out.write("    \t\t},\r\n");
      out.write("    \t\twidth:'100%',\r\n");
      out.write("    \t\theight:\"460\", //\"100%\", // 330\r\n");
      out.write("    \t\tcontainer : 'gridbox',\r\n");
      out.write("    \t\tautoLoad:false,\r\n");
      out.write("    \t\tstripeRows: false,\r\n");
      out.write("    \t\tremoteFilter:true,\r\n");
      out.write("    \t\tshowIndexColumn:false,\r\n");
      out.write("    \t\tselectRowByCheck:true,\r\n");
      out.write("    \t\treplaceContainer : true,\r\n");
      out.write("    \t\tdataset : dsOption ,\r\n");
      out.write("    \t\tcolumns : colsOption,\r\n");
      out.write("    \t\ttoolbarContent : 'nav | pagesize  state',\r\n");
      out.write("    \t\tpageSizeList : [size,size*2,size*4,size*6,size*8,size*10],\r\n");
      out.write("    \t\tpageSize:size,\r\n");
      out.write("    \t\tskin:getGridSkin()\r\n");
      out.write("    \t};\r\n");
      out.write("    \tmygrid=new Sigma.Grid( gridOption );\r\n");
      out.write("    \tSigma.Util.onLoad( Sigma.Grid.render(mygrid) );\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//编制\r\n");
      out.write("//公司回调\r\n");
      out.write("function callBackCompany(){\r\n");
      out.write("\t$(\"#quotadeptid\").val(null);\r\n");
      out.write("\t$(\"#quotadeptname\").val(null);\r\n");
      out.write("\t\r\n");
      out.write("\t//部门选择回调\r\n");
      out.write("\tcallbackDept();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//部门选择回调\r\n");
      out.write("function callbackDept(){\r\n");
      out.write("\t/* $(\"#postid\").val(null);\r\n");
      out.write("\t$(\"#postname\").val(null); */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//岗位回调\r\n");
      out.write("function callbackpost(){\r\n");
      out.write("\tvar postid=$(\"#postid\").val();\r\n");
      out.write("\tvar quotaid=$(\"#quotaquotaid\").val();\r\n");
      out.write("\tvar state=$(\"#quotastate\").val();\r\n");
      out.write("\tvar budgettype=$(\"#quotabudgettype\").val();\r\n");
      out.write("\t$.post(\"quota/checkQuotaByPostIdAndBudgettype.do\",{quotaid:quotaid,postid:postid,budgettype:budgettype,state:state}, function(data) {\r\n");
      out.write("\t\tif(data!=null&&data!=\"\"){\r\n");
      out.write("\t\t\talert(data);\r\n");
      out.write("\t\t\t$(\"#postid\").val(null);\r\n");
      out.write("\t\t\t$(\"#postname\").val(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//验证此岗位下编制是否被占\r\n");
      out.write("function callbackBudgettype(){\r\n");
      out.write("\tvar postid=$(\"#postid\").val();\r\n");
      out.write("\tvar quotaid=$(\"#quotaquotaid\").val();\r\n");
      out.write("\tvar state=$(\"#quotastate\").val();\r\n");
      out.write("\tvar budgettype=$(\"#quotabudgettype\").val();\r\n");
      out.write("\t$.post(\"quota/checkQuotaByPostIdAndBudgettype.do\",{quotaid:quotaid,postid:postid,budgettype:budgettype,state:state}, function(data) {\r\n");
      out.write("\t\tif(data!=null&&data!=\"\"){\r\n");
      out.write("\t\t\talert(data);\r\n");
      out.write("\t\t\t$(\"#quotabudgettype\").val(null);\r\n");
      out.write("\t\t\t$(\"#quotabudgettypename\").val(null);\r\n");
      out.write("\t\t}\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//编制\r\n");
      out.write("var myQuotagrid=null;\r\n");
      out.write("function loadQuotaGrid(){\r\n");
      out.write("\tvar size=20;\r\n");
      out.write("\tvar wh=$(document.body).outerWidth()-360;\r\n");
      out.write("\t$(\"#gridQuotabox\").css({width:wh,height:460});\r\n");
      out.write("\t\r\n");
      out.write("\tvar grid_demo_id = \"myGrid2\";\r\n");
      out.write("\tvar dsOption= {\r\n");
      out.write("\t\t\tfields :[\r\n");
      out.write("\t\t\t\t{name : 'quotacode'},\r\n");
      out.write("\t\t\t\t{name : 'companyname'},\r\n");
      out.write("\t\t\t\t{name : 'deptname'},\r\n");
      out.write("\t\t\t\t{name : 'postname'},\r\n");
      out.write("\t\t\t\t{name : 'budgettypename'},\r\n");
      out.write("\t\t\t\t{name : 'budgetnumber'},\r\n");
      out.write("\t\t\t\t{name : 'employednumber'},\r\n");
      out.write("\t\t\t\t{name : 'email'},\r\n");
      out.write("\t\t\t\t{name : 'officeaddress'},\r\n");
      out.write("\t\t\t\t{name : 'refreshtimestamp'},\r\n");
      out.write("\t\t\t\t{name : 'memo'},\r\n");
      out.write("\t\t\t\t{name : 'modiuser'},\r\n");
      out.write("\t\t\t\t{name : 'moditimestamp'},\r\n");
      out.write("\t\t\t\t{name : 'modimemo'}\r\n");
      out.write("\t\t\t]\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar colsOption = [\r\n");
      out.write("\t\t\t{id: '选择' ,isCheckColumn : true, editable:false,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'quotaid' , header: \"操作\" , width :60 ,headAlign:'center',align:'center',renderer:function(value ,record,colObj,grid,colNo,rowNo){\r\n");
      out.write("\t\t\t\tvar htm='';\r\n");
      out.write("\t        \t\thtm+='<a href=\"javascript:lockQuota(\\''+record.quotaid+'\\',\\''+record.vacancynumber+'\\');\" title=\"锁定\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lock?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\">';\r\n");
      out.write("\t        \t\thtm+='锁定';\r\n");
      out.write("\t        \t\thtm+='</a>';\r\n");
      out.write("        \t\treturn htm;\r\n");
      out.write("\t\t\t}},\r\n");
      out.write("\t\t\t{id: 'quotacode' , header: \"编号\", width :100 ,headAlign:'center',align:'center'},\r\n");
      out.write("\t\t\t{id: 'companyname' , header: \"公司名称\" , width :250 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'deptname' , header: \"部门名称\", width :300 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'postname' , header: \"岗位名称\", width :140 ,headAlign:'center',align:'left'},\r\n");
      out.write("\t\t\t{id: 'budgettypename' , header: \"编制类别\" ,headAlign:'center',align:'center', width :100},\r\n");
      out.write("      \t\t{id: 'budgetnumber' , header: \"编制人数\",headAlign:'center',align:'center', width :80,number:true},\r\n");
      out.write("      \t\t{id: 'employednumber' , header: \"在岗人数\",headAlign:'center',align:'center', width :80,number:true},\r\n");
      out.write("      \t\t{id: 'vacancynumber' , header: \"缺编人数\",headAlign:'center',align:'center', width :80,number:true},\r\n");
      out.write("      \t\t{id: 'operatenum' , header: \"锁定人数\",headAlign:'center',align:'center', width :80,number:true},\r\n");
      out.write("      \t\t{id: 'postnumber' , header: \"计划招聘人数\",headAlign:'center',align:'center', width :80,number:true},\r\n");
      out.write("      \t\t{id: 'budgetdate' , header: \"编制时间\" ,headAlign:'center', align:'center', width :100},\r\n");
      out.write("\t\t\t{id: 'memo' , header: \"备注\", width :300 ,headAlign:'center',align:'left'}\r\n");
      out.write("\t\t];\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar gridOption={\r\n");
      out.write("\t\tid : grid_demo_id,\r\n");
      out.write("\t\tloadURL :'quota/searchQuota.do',\r\n");
      out.write("\t\tbeforeLoad:function(reqParam){\r\n");
      out.write("\t\t\tinitQuotaPagePam();\r\n");
      out.write("\t\t\treqParam['parameters']=pam;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texportURL : 'quota/searchQuota.do?export=true',\r\n");
      out.write("\t\tbeforeExport:function(){\r\n");
      out.write("\t\t\tinitQuotaPagePam();\r\n");
      out.write("\t\t\tpam.expAll=$('input[name=\"xls\"]:checked').val();\r\n");
      out.write("\t\t\tmyQuotagrid.parameters=pam;\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\texportFileName : '编制信息表.xls',\r\n");
      out.write("\t\twidth:'99.8%',\r\n");
      out.write("\t\theight:\"460\",\r\n");
      out.write("\t\tminHeight:\"300\",  //\"100%\", // 330,\r\n");
      out.write("\t\tcontainer : 'gridQuotabox', \r\n");
      out.write("\t\tpageSizeList : [size,size*2,size*4,size*6,size*8,size*10],\r\n");
      out.write("\t\tautoLoad:true,\r\n");
      out.write("\t\tstripeRows: false,\r\n");
      out.write("\t\tremoteFilter:true,\r\n");
      out.write("\t\tshowIndexColumn:true,\r\n");
      out.write("\t\tselectRowByCheck:true,\r\n");
      out.write("\t\treplaceContainer : true,\r\n");
      out.write("\t\tdataset : dsOption ,\r\n");
      out.write("\t\tcolumns : colsOption,\r\n");
      out.write("\t\ttoolbarContent : 'nav | pagesize  state',\r\n");
      out.write("\t\tpageSize:size,\r\n");
      out.write("\t\tskin:getGridSkin(),\r\n");
      out.write("\t\tonDblClickCell:function(value, record , cell, row, colNO, rowNO,columnObj,grid){\r\n");
      out.write("\t\t\tif(colNO!=0){\r\n");
      out.write("\t\t\t\tconvertView('quota.do?page=tab&id='+record.quotaid);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\tmyQuotagrid=new Sigma.Grid( gridOption );\r\n");
      out.write("\tSigma.Util.onLoad( Sigma.Grid.render(myQuotagrid) );\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//参数设置\r\n");
      out.write("var pam=null;\r\n");
      out.write("function initQuotaPagePam(){\r\n");
      out.write("\tpam={};\r\n");
      out.write("\tpam.expAll=0;\r\n");
      out.write("\tpam.companyid=$(\"#companyid\").val();\r\n");
      out.write("\tpam.deptid=$(\"#deptid\").val();\r\n");
      out.write("\tpam.postname=$(\"#postname\").val();\r\n");
      out.write("\tpam.postidofquota=$(\"#postid\").val();\r\n");
      out.write("\tif(selectNode!=null){\r\n");
      out.write("\t\tif(selectNode.code=='dept'){\r\n");
      out.write("\t\t\tpam.deptcode=selectNode.deptcode;\r\n");
      out.write("\t\t}else if(selectNode.code='company'){\r\n");
      out.write("\t\t\tpam.companycode=selectNode.companycode;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"sort\">\r\n");
      out.write("\t<div class=\"sort-title\">\r\n");
      out.write("\t\t<h3>岗位管理</h3>\r\n");
      out.write("\t\t<div class=\"title-ctrl\">\r\n");
      out.write("\t\t\t<a class=\"btn-ctrl\" href=\"javascript:chevronUpDown('.sort-cont',false);\"><i class=\"icon icon-chevron-up\"></i></a>\r\n");
      out.write("\t\t\t<a class=\"btn-ctrl\" href=\"javascript:chevronUpDown('.sort-cont',true);\"><i class=\"icon icon-chevron-down\"></i></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"sort-cont sort-table\">\r\n");
      out.write("\t\t<div class=\"table\">\r\n");
      out.write("\t\t\t<div class=\"table-bar\">\r\n");
      out.write("\t\t\t\t<div class=\"table-title\">\r\n");
      out.write("\t\t\t\t\t表格名称 \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-ctrl\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"group0\" class=\"gruop_hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"myrankvalid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"myrankvalid\" type=\"checkbox\" class=\"checkboxstyle\" onclick=\"buildDepartmentQuotaTree();\" checked=\"true\"/> 只显示有效的岗位\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn\" id=\"exp\" href=\"javascript:expPostTree();\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exp?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-download\"></i><span>导出</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"b1\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t   \t\t<a class=\"btn\" id=\"new\" href=\"javascript:addPost();\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${add?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-plus\"></i><span>新增</span></a>\r\n");
      out.write("\t\t\t\t\t\t   \t\t<a class=\"btn\" id=\"edit\" href=\"javascript:editPost();\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${edit?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-repeat\"></i><span>修改</span></a>\r\n");
      out.write("\t\t\t\t\t\t   \t\t<a class=\"btn\" id=\"del\" href=\"javascript:invalidOrReductionPostById(0);\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${valid?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-trash\"></i><span>失效</span></a>\r\n");
      out.write("\t\t\t\t\t\t   \t\t<a class=\"btn\" id=\"recover\" href=\"javascript:invalidOrReductionPostById(1);\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${revert?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-repeat\"></i><span>还原</span></a>\r\n");
      out.write("\t\t\t\t\t   \t\t\t<a class=\"btn\" id=\"remove\"  href=\"javascript:delPostById();\"><i class=\"icon icon-remove\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${del?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"></i><span>删除</span></a>\r\n");
      out.write("\t\t\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t\t\t   \t<span id=\"b2\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t   \t\t<a class=\"btn\"  href=\"javascript:save();\" ><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"btn\"  href=\"javascript:onCancel();\"><i class=\"icon icon-share\"></i><span>取消</span></a>\r\n");
      out.write("\t\t\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t   \t\t\t</span>\r\n");
      out.write("\t\t\t   \t\t\r\n");
      out.write("\t\t   \t\t\t\t<span id=\"group1\" class=\"gruop_hidden\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t   \t\t\t\r\n");
      out.write("\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div class=\"table-wrapper\" id=\"myContent\" style=\"height:750px;\">\r\n");
      out.write("\t\t\t\t<div class=\"ui-layout-west\" id=\"myWest\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ui-layout-north\">\r\n");
      out.write("\t\t\t\t\t\t<table width=\"100%\" height=\"100%\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"padding-left:1px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"myMarker\" id=\"myMarker\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"ui-layout-center\" style=\"border:0px;\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"tree\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"ui-layout-center\" style=\"overflow:hidden;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"mytab\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li ><a href=\"#tab0\">基本信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li ><a href=\"#tab1\">在岗员工</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--  <li ><a href=\"#tab2\">编制信息</a></li>-->\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tab0\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"department/saveOrUpdatePost.do\" method=\"post\" id=\"myForm\" class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<legend>岗位基本信息</legend>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"postid\" name=\"postid\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"companyid\" name=\"companyid\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"deptid\" name=\"deptid\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"state\" name=\"state\" value=\"1\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"modiuser\" name=\"modiuser\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"modimemo\" name=\"modimemo\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"moditimestamp\" name=\"moditimestamp\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<!--  <input type=\"hidden\" id=\"interfacecode\" name=\"interfacecode\" value=\"\"/>-->\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"postcode\" name=\"postcode\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span><em class=\"red\">* </em>岗位名称：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"postname\" name=\"postname\" class=\"{required:true,maxlength:30} inputstyle\"   onblur=\"checkPostname();\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"bzlb1\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>编制类别(正式)：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"budgettype1\" name=\"budgettype1\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"budgettypename1\" name=\"budgettypename1\" class=\"inputselectstyle\" onclick=\"chooseBudgettypeTree('#budgettype1','#budgettypename1',$('#companyid').val(),callbackBudgettype);\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"search-trigger\" onclick=\"chooseBudgettypeTree('#budgettype1','#budgettypename1',$('#companyid').val(),callbackBudgettype);\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"bzrs1\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>编制人数(正式)：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"budgetnumber1\" name=\"budgetnumber1\" class=\"{number:true,maxlength:40} inputstyle\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"bzlb2\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>编制类别(劳务)：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"budgettype2\" name=\"budgettype2\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"budgettypename2\" name=\"budgettypename2\" class=\"inputselectstyle\" onclick=\"chooseBudgettypeTree('#budgettype2','#budgettypename2',$('#companyid').val(),callbackBudgettype);\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"search-trigger\" onclick=\"chooseBudgettypeTree('#budgettype2','#budgettypename2',$('#companyid').val(),callbackBudgettype);\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"bzrs2\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>编制人数(劳务)：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"budgetnumber2\" name=\"budgetnumber2\" class=\"{number:true,maxlength:40} inputstyle\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t            \t<li>\r\n");
      out.write("\t\t\t\t            \t\t<span>代码：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input id=\"interfacecode\" name=\"interfacecode\" class=\"{maxlength:30} inputstyle\"/>\r\n");
      out.write("\t\t\t                    </li>\r\n");
      out.write("\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>职务：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"jobid\" name=\"jobid\" type=\"hidden\" class=\"inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"jobidname\" name=\"jobidname\" class=\"inputselectstyle\" onclick=\"chooseJobTree('#jobid','#jobidname',selectNode.ename);\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"search-trigger\" onclick=\"chooseJobTree('#jobid','#jobidname',selectNode.ename);\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>描述：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea id=\"postduty\" name=\"postduty\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\" ></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>备注：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea id=\"memo\" name=\"memo\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\" ></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t\t\t\t    <div id=\"tab1\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t        \t<div style=\"padding-top:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"myTable\" style=\"margin:0px auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"gridbox\" ></div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t    <!--  <div id=\"tab2\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t        \t<div style=\"padding-top:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"myQuota\" style=\"margin:0px auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"gridQuotabox\" ></div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t    </div>-->\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
