package org.apache.jsp.pages.department;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>部门管理</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\"/>    \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/style.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/form.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/jquery-ui-1.8.15.custom.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeStyle.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeIcons.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/gt_grid.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/default/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/green/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/mac/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/china/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/skin/vista/skinstyle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/grid/calendar/calendar-blue.css\"  />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/public.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.layout.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-ui-1.8.5.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/tree/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/form/lib/jquery.metadata.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-en.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/calendar/calendar-setup.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_grid_all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/grid/gt_msg_cn.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"pages/department/post.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"pages/tree.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"pages/treedrag.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("var edit='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${edit}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t//tab页\r\n");
      out.write("\tloadTab();\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t//加载布局\r\n");
      out.write("\t$('#myContent').layout({\r\n");
      out.write("        west: {size:\"300\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t$('#myWest').layout({\r\n");
      out.write("        north: {size:\"28\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("  \t//加载树\r\n");
      out.write("    buildDepartmentTree();\r\n");
      out.write("  \t\r\n");
      out.write("  \t//获取岗位信息\r\n");
      out.write("  \tloadGrid();\r\n");
      out.write("    \r\n");
      out.write("  //加载表单验证\r\n");
      out.write("    $(\"#myForm\").validate();\r\n");
      out.write("    $('#myForm').ajaxForm(function(data) {\r\n");
      out.write("        //节点处理\r\n");
      out.write("    \tvar nameValue=data.deptname;\r\n");
      out.write("    \t\r\n");
      out.write("    \tif(add){//新增\r\n");
      out.write("    \t\tvar newNode = {id:data.deptid, name:nameValue,iconSkin:\"dept\",code:\"dept\",state:1,ename:data.companyid,deptcode:data.deptcode};\r\n");
      out.write("       \t\tzTree.addNodes(selectNode, newNode);\r\n");
      out.write("        }else{\r\n");
      out.write("        \tselectNode.name = nameValue;\r\n");
      out.write("   \t\t\tzTree.updateNode(selectNode);\r\n");
      out.write("   \t\t\tzTree.selectNode(selectNode);\r\n");
      out.write("        }\r\n");
      out.write("    \tadd=false;\r\n");
      out.write("    \t//不可编辑\r\n");
      out.write("    \tformDisabled(true);\r\n");
      out.write("    \t//取消状态\r\n");
      out.write("    \tonCancel();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("  \t//把表单置为不可编辑\r\n");
      out.write("    formDisabled(true);\r\n");
      out.write("  \t\r\n");
      out.write("\r\n");
      out.write("    //关闭等待层\r\n");
      out.write("    if(window.parent.hidenLoading)\r\n");
      out.write("    \twindow.parent.hidenLoading();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//tab页\r\n");
      out.write("var tabIndex=0;\r\n");
      out.write("function loadTab(){\r\n");
      out.write("\t$(\"#mytab\").tabs({\r\n");
      out.write("    \tselect: function(event, ui) {\r\n");
      out.write("    \t\ttabIndex=ui.index;\r\n");
      out.write("    \t\t$(\".gruop_hidden\").hide();\r\n");
      out.write("    \t\t$(\"#group\"+tabIndex).show();\r\n");
      out.write("    \t\t$(\"#tab\"+tabIndex).show();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t//控制tab\r\n");
      out.write("\t\t\tif(selectNode!=null&&selectNode.code=='dept'){\r\n");
      out.write("\t\t\t\tif(tabIndex==1){\r\n");
      out.write("\t\t\t\t\tmygrid.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#group\"+tabIndex).hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//树\r\n");
      out.write("var zTree;\r\n");
      out.write("//选中节点\r\n");
      out.write("var selectNode=null;\r\n");
      out.write("function buildDepartmentTree(){\r\n");
      out.write("//配置\r\n");
      out.write("var setting = {\r\n");
      out.write("\tedit: {\r\n");
      out.write("\t\tdrag: {\r\n");
      out.write("\t\t\tautoExpandTrigger: true,\r\n");
      out.write("\t\t\tprev: dropPrev,\r\n");
      out.write("\t\t\tinner: dropInner,\r\n");
      out.write("\t\t\tnext: dropNext\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tenable: true,\r\n");
      out.write("\t\tshowRemoveBtn: false,\r\n");
      out.write("\t\tshowRenameBtn: false\r\n");
      out.write("\t},\r\n");
      out.write("\tcallback:{\r\n");
      out.write("\t\tbeforeDrag: beforeDrag,\r\n");
      out.write("\t\tbeforeDrop: beforeDrop,\r\n");
      out.write("\t\tbeforeDragOpen: beforeDragOpen,\r\n");
      out.write("\t\tonDrag: onDrag,\r\n");
      out.write("\t\tonDrop: onDrop,\r\n");
      out.write("\t\tbeforeClick: function(treeId, treeNode) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t$(\"#myForm\").clearForm();\r\n");
      out.write("\t\tselectNode=treeNode;\r\n");
      out.write("\t\tformDisabled(true);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//节点权限\r\n");
      out.write("\t\t//公司节点且有权限\r\n");
      out.write("\t\tif(treeNode.code!='dept'&&!treeNode.isaudit){\r\n");
      out.write("\t\t\t$('#b1').hide();\r\n");
      out.write("\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//出现按钮组一\r\n");
      out.write("\t\t$('#b1').show();\r\n");
      out.write("\t\t$('#b2').hide();\r\n");
      out.write("\r\n");
      out.write("\t\t//只能新增\r\n");
      out.write("\t\tif(treeNode.code!='dept'){\r\n");
      out.write("\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${add==true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t$('#new').show();\r\n");
      out.write("\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t\t$(\".post\").hide();\r\n");
      out.write("\t\t}else if(treeNode.code=='dept'){\r\n");
      out.write("\t\t\t//有效的\r\n");
      out.write("\t\t\tif(treeNode.state==1){\r\n");
      out.write("\t\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${add==true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t\t$('#new').show();\r\n");
      out.write("\t\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${edit==true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t\t$('#edit').show();\r\n");
      out.write("\t\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${del==true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t\t$('#del').show();\r\n");
      out.write("\t\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t\t$('#new').hide();\r\n");
      out.write("\t\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${revert==true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t\t$(\"#recover\").show();\r\n");
      out.write("\t\t\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${valid==true}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(")\r\n");
      out.write("\t\t\t\t\t$(\"#remove\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\".post\").show();\r\n");
      out.write("\t\t\t//取数据\r\n");
      out.write("\t\t\tloadData(treeNode.id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t$('#new').hide();\r\n");
      out.write("\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}},\r\n");
      out.write("\tview: {\r\n");
      out.write("\t\tfontCss: getDeptFontCss\r\n");
      out.write("\t}};\r\n");
      out.write("\tvar myvalid=$(\"#myvalid\").attr(\"checked\")?1:0;\r\n");
      out.write("    $.getJSON(\"department/buildMyDepartmentTree.do\",{valid:myvalid}, function(tdata) {\r\n");
      out.write("    \tzTree = $.fn.zTree.init($(\"#tree\"),setting, tdata);\r\n");
      out.write("    \t\r\n");
      out.write("    \t//邦定定位事件\r\n");
      out.write("    \t$(\"#myMarker\").bind(\"keyup\",markTreeNode);\r\n");
      out.write("    \t$(\"#myMarker\").bind(\"blur\",markSelectTreeNode);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//节点搜索定位\r\n");
      out.write("function markSelectTreeNode(){\r\n");
      out.write("\tvar value=\"\";\r\n");
      out.write("\tvalue = $.trim($(\"#myMarker\").val());\r\n");
      out.write("\tif (value != \"\"){\r\n");
      out.write("\t\tnodeList = zTree.getNodesByParamFuzzy(\"name\", value);\r\n");
      out.write("\t\tif(nodeList.length<=0)\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\tfor( var i=0, l=nodeList.length; i<l; i++) {\r\n");
      out.write("\t\t\tvar node=nodeList[i];\r\n");
      out.write("\t\t\tif(i==0){\r\n");
      out.write("\t\t\t\tzTree.selectNode(node);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//节点搜索变色\r\n");
      out.write("function markTreeNode(e) {\r\n");
      out.write("\tif(!nodeState){\r\n");
      out.write("\t\tnodeState=true;\r\n");
      out.write("\t\tvar value=\"\";\r\n");
      out.write("\t\tvalue = $.trim($(\"#myMarker\").val());\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tchangeNodesColor(false);\r\n");
      out.write("\t\tif (value === \"\"){\r\n");
      out.write("\t\t\tnodeState=false;\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tnodeList = zTree.getNodesByParamFuzzy(\"name\", value);\r\n");
      out.write("\t\tchangeNodesColor(true);\r\n");
      out.write("\t\tnodeState=false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function changeNodesColor(highlight) {\r\n");
      out.write("\tif(nodeList.length<=0)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tfor( var i=0, l=nodeList.length; i<l; i++) {\r\n");
      out.write("\t\tvar node=nodeList[i];\r\n");
      out.write("\t\tnode.highlight = highlight;\r\n");
      out.write("\t\tzTree.updateNode(nodeList[i]);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function getDeptFontCss(treeId, treeNode) {\r\n");
      out.write("\treturn (!!treeNode.highlight) ? {color:\"#ff0000\", \"font-weight\":\"bold\"} : {color:\"#333\", \"font-weight\":\"normal\"};\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//节点排序\r\n");
      out.write("function onDrop(event, treeId, treeNodes, targetNode, moveType, isCopy) {\r\n");
      out.write("\tif(treeNodes.lenght>0){\r\n");
      out.write("\t\talert(\"请选择1个节点进行排序！\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(targetNode==null\t)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tselectNode=treeNodes[0];\r\n");
      out.write("\t$.post(\"department/orderDepartment.do\",{id:selectNode.id,targetid:targetNode.id,moveType:moveType}, function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("//==========================================\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//参数设置\r\n");
      out.write("var pam=null;\r\n");
      out.write("function initPostPagePam(){\r\n");
      out.write("\tpam={};\r\n");
      out.write("\tpam.expAll=0;\r\n");
      out.write("\tif(selectNode!=null){\r\n");
      out.write("\t\tpam.deptid=selectNode.id;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//加载数据\r\n");
      out.write("function loadData(tid){\r\n");
      out.write("\t$(\"#myForm\").clearForm();\r\n");
      out.write("\tif(tid!=null&&tid!=''&&tid!='null')\r\n");
      out.write("\t\t$.getJSON(\"department/getDepartmentById.do\", {id:tid}, function(data) {\r\n");
      out.write("\t\t\tif(data!=null){\r\n");
      out.write("\t\t\t\tfor (var key in data) {\r\n");
      out.write("\t\t\t        var el = $('#' + key);\r\n");
      out.write("\t\t\t        if(el) \r\n");
      out.write("\t\t\t            el.val(data[key]);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//控制tab\r\n");
      out.write("\t\t\t\tif(selectNode!=null&&selectNode.code=='dept'){\r\n");
      out.write("\t\t\t\t\t$(\"#group\"+tabIndex).show();\r\n");
      out.write("\t\t\t\t\tif(tabIndex==1){\r\n");
      out.write("\t\t\t\t\t\tmygrid.reload();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#group\"+tabIndex).hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//新增\r\n");
      out.write("var add=false;\r\n");
      out.write("function addNode(){\r\n");
      out.write("\t$('#b1').hide();\r\n");
      out.write("\t$('#b2').show();\r\n");
      out.write("\t$(\"#myForm\").clearForm();\r\n");
      out.write("\tformDisabled(false);\r\n");
      out.write("\tadd=true;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#myForm #state\").val(1);\r\n");
      out.write("\t$(\"#modiuser\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//设置上级\r\n");
      out.write("\tif(selectNode!=null&&selectNode.code=='dept'){\r\n");
      out.write("\t\tvar pdeptid=selectNode.id;\r\n");
      out.write("\t\tif(pdeptid!=null&&pdeptid!=''){\r\n");
      out.write("\t\t\t$('#pdeptid').val(pdeptid);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#companyid\").val(selectNode.ename);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$(\"#companyid\").val(selectNode.id);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//编辑\r\n");
      out.write("function editNode(){\r\n");
      out.write("\t$('#b1').hide();\r\n");
      out.write("\t$('#b2').show();\r\n");
      out.write("\tformDisabled(false);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//保存\r\n");
      out.write("function save(){\r\n");
      out.write("\t$('#myForm').submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//取消\r\n");
      out.write("function onCancel(){\r\n");
      out.write("\t//取数据\r\n");
      out.write("\tif(selectNode!=null){\r\n");
      out.write("\t\tif(selectNode.code=='dept'){\r\n");
      out.write("\t\t\tloadData(selectNode.id);\r\n");
      out.write("\t\t\t$('#b1').show();\r\n");
      out.write("\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#del').show();\r\n");
      out.write("\t\t\t$('#edit').show();\r\n");
      out.write("\t\t\t$('#new').show();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$('#b1').show();\r\n");
      out.write("\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#new').show();\r\n");
      out.write("\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tformDisabled(true);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//删除\r\n");
      out.write("function delNode(){\r\n");
      out.write("\t\r\n");
      out.write("\t$.post(\"employee/getPositionByDeptCode.do\",{deptcode:selectNode.deptcode},function(data){\r\n");
      out.write("\t\tif(!data){\r\n");
      out.write("\t\t\tif(!confirm('确认要删除吗？')){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.post(\"department/delDepartmentByDepartmentId.do\",{id:selectNode.id}, function() {\r\n");
      out.write("\t\t\t\tzTree.removeNode(selectNode);\r\n");
      out.write("\t\t\t\t$(\"#myForm\").clearForm();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t \t\t$('#b1').show();\r\n");
      out.write("\t\t\t\t$('#b2').hide();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#del').hide();\r\n");
      out.write("\t\t\t\t$('#edit').hide();\r\n");
      out.write("\t\t\t\t$('#new').hide();\r\n");
      out.write("\t\t \t\tformDisabled(true);\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"部门下面有员工任职信息,不能删除\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//无效\r\n");
      out.write("function validDepartment(valid){\r\n");
      out.write("\tif(selectNode==null)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tif(!confirm('确认要把选中的部门置为无效吗？')){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.post(\"department/validDepartmentById.do\",{Departmentid:selectNode.id,valid:valid}, function() {\r\n");
      out.write("\t\tselectNode.iconSkin = \"remove\";\r\n");
      out.write("\t\tselectNode.state = 0;\r\n");
      out.write("\t\tzTree.updateNode(selectNode);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#b1').show();\r\n");
      out.write("\t\t$('#b2').hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#del').hide();\r\n");
      out.write("\t\t$('#edit').hide();\r\n");
      out.write("\t\t$('#new').hide();\r\n");
      out.write("\t\t$(\"#recover\").show();\r\n");
      out.write("\t\t$(\"#remove\").show();\r\n");
      out.write("\t\tformDisabled(true);\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//还原\r\n");
      out.write("function recoverDepartment(valid){\r\n");
      out.write("\tif(selectNode==null)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t$.post(\"department/validDepartmentById.do\",{Departmentid:selectNode.id,valid:valid}, function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tselectNode.iconSkin = \"dept\";\r\n");
      out.write("\t\tselectNode.state = 1;\r\n");
      out.write("\t\tzTree.updateNode(selectNode);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#b1').show();\r\n");
      out.write("\t\t$('#b2').hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#del').show();\r\n");
      out.write("\t\t$('#edit').show();\r\n");
      out.write("\t\t$('#new').show();\r\n");
      out.write("\t\t$(\"#remove\").hide();\r\n");
      out.write("\t\t$(\"#recover\").hide();\r\n");
      out.write("\t\tformDisabled(true);\r\n");
      out.write("  });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//导出部门树\r\n");
      out.write("function expTree(){\r\n");
      out.write("\twindow.open(\"department/exportDepartment.do\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//岗位列表\r\n");
      out.write("var mygrid=null;\r\n");
      out.write("function loadGrid(){\r\n");
      out.write("\tvar size=20;\r\n");
      out.write("\tvar wh=$(document.body).outerWidth()-360;\r\n");
      out.write("\t$(\"#myTable\").css({width:wh,height:460});\r\n");
      out.write("\t\r\n");
      out.write("\tvar grid_demo_id = \"myGrid1\";\r\n");
      out.write("\tvar dsOption= {\r\n");
      out.write("\t\t\tfields :[\r\n");
      out.write("\t\t\t\t{name : 'postid'},\r\n");
      out.write("\t\t\t\t{name : 'companyid'},\r\n");
      out.write("\t\t\t\t{name : 'deptid'},\r\n");
      out.write("\t\t\t\t{name : 'jobid'},\r\n");
      out.write("\t\t\t\t{name : 'postname'},\r\n");
      out.write("\t\t\t\t{name : 'postcode'},\r\n");
      out.write("\t\t\t\t{name : 'postduty'},\r\n");
      out.write("\t\t\t\t{name : 'state'},\r\n");
      out.write("\t\t\t\t{name : 'interfacecode'},\r\n");
      out.write("\t\t\t    {name : 'memo'},\r\n");
      out.write("\t\t\t\t{name : 'modiuser'},\r\n");
      out.write("\t\t\t   \t{name : 'moditimestamp'},\r\n");
      out.write("\t\t\t\t{name : 'modimemo'}\r\n");
      out.write("\t\t\t]\r\n");
      out.write("\t\t};\r\n");
      out.write("\tvar colsOption = [\r\n");
      out.write("\t\t\t\t{id: '选择' ,isCheckColumn : true, editable:false,headAlign:'center',align:'center',filterable:false},\r\n");
      out.write("\t\t        {id: 'state', header: \"操作\", width :60 ,headAlign:'center',align:'center',renderer:function(value ,record,colObj,grid,colNo,rowNo){\r\n");
      out.write("\t\t        \tvar htm='';\r\n");
      out.write("\t\t        \thtm+='<a href=\"javascript:saveOrUpdatePost(false,\\''+record.postid+'\\');\" class=\"ui-button ui-button-icon-only\" title=\"修改\"><span class=\"ui-icon ui-icon-pencil\"></span>&nbsp;</a>';\r\n");
      out.write("\t\t\t\t\tif(value==1)\r\n");
      out.write("\t\t        \t\thtm+='<a href=\"javascript:recoverPost(\\''+record.postid+'\\',0);\" class=\"ui-button ui-button-icon-only\" title=\"置为无效\"><span class=\"ui-icon ui-icon-trash\"></span>&nbsp;</a>';\r\n");
      out.write("\t\t        \telse if(value==0)\r\n");
      out.write("\t\t        \t\thtm+='<a href=\"javascript:recoverPost(\\''+record.postid+'\\',1);\" class=\"ui-button ui-button-icon-only\" title=\"还原\"><span class=\"ui-icon ui-icon-check\"></span>&nbsp;</a>';\r\n");
      out.write("\t\t\t\t\treturn htm;\r\n");
      out.write("\t\t\t\t}},\r\n");
      out.write("              \t{id: 'postname' , header: \"岗位名称\" ,headAlign:'center',align:'left', width :120},\r\n");
      out.write("          \t\t{id: 'jobidname' , header: \"职务\",headAlign:'center',align:'center', width :80},\r\n");
      out.write("          \t  \t{id: 'postduty' , header: \"描述\",headAlign:'left', width :200},\r\n");
      out.write("          \t\t{id: 'memo' , header: \"备注\" ,headAlign:'left', width :200}\r\n");
      out.write("          \t];\r\n");
      out.write("\tvar gridOption={\r\n");
      out.write("\t\t\tid : grid_demo_id,\r\n");
      out.write("\t\t\tloadURL : 'department/searchPost.do',\r\n");
      out.write("\t\t\tbeforeLoad:function(reqParam){\r\n");
      out.write("\t\t\t\tinitPostPagePam();\r\n");
      out.write("\t\t\t\treqParam['parameters']=pam;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\texportURL : 'department/searchPost.do?export=true',\r\n");
      out.write("\t\t\tbeforeExport:function(){\r\n");
      out.write("\t\t\t\tinitPostPagePam();\r\n");
      out.write("\t\t\t\tpam.expAll=$('input[name=\"xls\"]:checked').val();\r\n");
      out.write("\t\t\t\tmygrid.parameters=pam;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\texportFileName : '岗位信息表.xls',\r\n");
      out.write("\t\t\twidth:'100%',\r\n");
      out.write("\t\t\theight:\"460\",  //\"100%\", // 330,\r\n");
      out.write("\t\t\tcontainer : 'gridbox',\r\n");
      out.write("\t\t\tautoLoad:false,\r\n");
      out.write("\t\t\tstripeRows: false,\r\n");
      out.write("\t\t\tshowIndexColumn:false,\r\n");
      out.write("\t\t\tselectRowByCheck:true,\r\n");
      out.write("\t\t\treplaceContainer : true,\r\n");
      out.write("\t\t\tdataset : dsOption ,\r\n");
      out.write("\t\t\tcolumns : colsOption,\r\n");
      out.write("\t\t\ttoolbarContent : 'nav | pagesize  state',\r\n");
      out.write("\t\t\tpageSizeList : [size,size*2,size*4,size*6,size*8,size*10],\r\n");
      out.write("\t\t\tpageSize:size,\r\n");
      out.write("\t\t\tskin:getGridSkin(),\r\n");
      out.write("\t\t\tonDblClickCell:function(value, record , cell, row, colNO, rowNO,columnObj,grid){\r\n");
      out.write("\t\t\t\tif(colNO!=0){\r\n");
      out.write("\t\t\t\t\tsaveOrUpdatePost(false,record.postid);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tmygrid=new Sigma.Grid( gridOption );\r\n");
      out.write("\t\tSigma.Util.onLoad( Sigma.Grid.render(mygrid) );\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"sort\">\r\n");
      out.write("\t<div class=\"sort-title\">\r\n");
      out.write("\t\t<h3>部门管理</h3>\r\n");
      out.write("\t\t<div class=\"title-ctrl\">\r\n");
      out.write("\t\t\t<a class=\"btn-ctrl\" href=\"javascript:chevronUpDown('.sort-cont',false);\"><i class=\"icon icon-chevron-up\"></i></a>\r\n");
      out.write("\t\t\t<a class=\"btn-ctrl\" href=\"javascript:chevronUpDown('.sort-cont',true);\"><i class=\"icon icon-chevron-down\"></i></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"sort-cont sort-table\">\r\n");
      out.write("\t\t<div class=\"table\">\r\n");
      out.write("\t\t\t<div class=\"table-bar\">\r\n");
      out.write("\t\t\t\t<div class=\"table-title\">\r\n");
      out.write("\t\t\t\t表格名称 \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"table-ctrl\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<span id=\"group0\" class=\"gruop_hidden\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"float:left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"myvalid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"myvalid\" type=\"checkbox\" class=\"checkboxstyle\" onclick=\"javascript:buildDepartmentTree();\" checked=\"true\"/> 只显示当前有效的部门\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a id=\"exp\" class=\"btn\" href=\"javascript:expTree();\" style=\"display:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exp?'':'none'}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"><i class=\"icon icon-download\"></i><span>导出</span></a>\r\n");
      out.write("\t\t\t\t\t   \t<span id=\"b1\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"new\" class=\"btn\" href=\"javascript:addNode();\" style=\"display:none;\"><i class=\"icon icon-plus\"></i><span>新增</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"edit\" class=\"btn\" href=\"javascript:editNode()\" style=\"display:none;\"><i class=\"icon icon-pencil\"></i><span>修改</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"del\"  class=\"btn\"  href=\"javascript:validDepartment(0);\" style=\"display:none;\"><i class=\"icon icon-trash\"></i><span>失效</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"recover\" class=\"btn\" href=\"javascript:recoverDepartment(1);\" style=\"display:none;\"><i class=\"icon icon-repeat\"></i><span>恢复</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"remove\"  class=\"btn\" href=\"javascript:delNode();\" style=\"display:none;\"><i class=\"icon icon-remove\"></i><span>删除</span></a>\r\n");
      out.write("\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t   \t\t<span id=\"b2\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn\"  href=\"javascript:save();\"><i class=\"icon icon-check\"></i><span>保存</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn\"  href=\"javascript:onCancel();\"><i class=\"icon icon-share\"></i><span>取消</span></a>\r\n");
      out.write("\t\t\t\t   \t\t</span>\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t   \t<span id=\"group1\" class=\"gruop_hidden\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t   \t\t<a class=\"btn post\" href=\"javascript:expPost();\" style=\"display:none;\"><i class=\"icon icon-download\"></i><span>导出</span></a>\r\n");
      out.write("\t\t\t\t   \t\t<a class=\"btn post\" href=\"javascript:saveOrUpdatePost(true);\"  style=\"display:none;\"><i class=\"icon icon-plus\"></i><span>新增</span></a>\r\n");
      out.write("\t\t\t\t   \t\t<a class=\"btn post\" href=\"javascript:invalidOrReductionPostById(0);\" style=\"display:none;\"><i class=\"icon icon-trash\"></i><span>失效</span></a>\r\n");
      out.write("\t\t\t\t   \t\t<a class=\"btn post\" href=\"javascript:invalidOrReductionPostById(1);\" style=\"display:none;\"><i class=\"icon icon-repeat\"></i><span>恢复</span></a>\r\n");
      out.write("\t\t\t\t   \t\t<a class=\"btn post\" href=\"javascript:delPostById();\" style=\"display:none;\"><i class=\"icon icon-remove\"></i><span>删除</span></a>\r\n");
      out.write("\t\t\t\t   \t</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"table-wrapper\" id=\"myContent\" style=\"height:550px;\">\r\n");
      out.write("\t\t\t\t<div class=\"ui-layout-west\" id=\"myWest\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ui-layout-north\">\r\n");
      out.write("\t\t\t\t\t\t<table width=\"100%\" height=\"100%\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"padding-left:1px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"myMarker\" id=\"myMarker\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"ui-layout-center\" style=\"border:0px;\">\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"tree\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"ui-layout-center\" style=\"overflow:hidden;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"mytab\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#tab0\">基本信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"display:none;\"><a href=\"#tab1\">岗位信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"tab0\">\r\n");
      out.write("\t\t\t\t\t        <form action=\"department/saveOrUpdateDepartment.do\" method=\"post\" id=\"myForm\" class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"deptid\" name=\"deptid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"pdeptid\" name=\"pdeptid\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"companyid\" name=\"companyid\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"deptcode\" name=\"deptcode\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"state\" name=\"state\" type=\"hidden\" value=\"1\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"modiuser\" name=\"modiuser\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"modimemo\" name=\"modimemo\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<legend>基本信息</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t            \t<li>\r\n");
      out.write("\t\t\t\t\t\t            \t\t<span><em class=\"red\">* </em>部门名称：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"deptname\" name=\"deptname\" class=\"{required:true,maxlength:40} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t                    </li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t            \t<li>\r\n");
      out.write("\t\t\t\t\t\t            \t\t<span>代码：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"interfacecode\" name=\"interfacecode\" class=\"{maxlength:30} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t                    </li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span>部门类型：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"depttype\" name=\"depttype\" type=\"hidden\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"depttypename\" name=\"depttypename\" class=\"inputselectstyle\" onclick=\"chooseOptionTree('#depttype','#depttypename','H_O_DEPARTMENT_DEPTTYPE');\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"select-trigger\" onclick=\"chooseOptionTree('#depttype','#depttypename','H_O_DEPARTMENT_DEPTTYPE');\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t                <span>部门体系：</span>\r\n");
      out.write("\t\t\t\t\t\t\t                <input id=\"assesshierarchy\" name=\"assesshierarchy\" type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"assesshierarchyname\" name=\"assesshierarchyname\" class=\"inputselectstyle\" onclick=\"chooseOptionTree('#assesshierarchy','#assesshierarchyname','ASSESSHIERARCHY');\"/>\r\n");
      out.write("\t\t\t\t\t\t\t           \t\t <div class=\"search-trigger\" onclick=\"chooseOptionTree('#assesshierarchy','#assesshierarchyname','ASSESSHIERARCHY');\"/>\r\n");
      out.write("\t\t\t\t\t\t\t            </li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span><em class=\"red\">* </em>部门职能：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"deptfunction\" name=\"deptfunction\" class=\"{required:true,maxlength:500} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span><em class=\"red\">* </em>部门职责：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <input id=\"deptduty\" name=\"deptduty\" class=\"{required:true,maxlength:500} inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span>部门简介：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t     \t<textarea id=\"description\" name=\"description\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\" ></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <span>备注：</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     <textarea id=\"memo\" name=\"memo\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\" ></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t       </form>\r\n");
      out.write("   \t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t        <div id=\"tab1\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t        \t<div style=\"padding-top:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"myTable\" style=\"margin:0px auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"gridbox\" ></div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  \r\n");
      out.write("\t<div id=\"postWindow\" title=\"岗位信息\">\r\n");
      out.write("\t\t<form action=\"department/saveOrUpdatePost.do\" method=\"post\" id=\"postForm\" class=\"form\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"postid\" name=\"postid\" value=\"\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"companyid\" name=\"companyid\" value=\"\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"deptid\" name=\"deptid\" value=\"\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"state\" name=\"state\" value=\"1\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"modiuser\" name=\"modiuser\" value=\"\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"modimemo\" name=\"modimemo\" value=\"\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"moditimestamp\" name=\"moditimestamp\" value=\"\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"interfacecode\" name=\"interfacecode\" value=\"\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"postcode\" name=\"postcode\" value=\"\"/>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"memo\" name=\"memo\" value=\"\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<span><em class=\"red\">* </em>岗位名称：</span>\r\n");
      out.write("\t\t\t\t\t<input id=\"postname\" name=\"postname\" class=\"{required:true,maxlength:30} inputstyle\" value=\"\"  onblur=\"checkPostname();\"/>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<span>职务：</span>\r\n");
      out.write("\t\t\t\t\t<input id=\"jobid\" name=\"jobid\" type=\"hidden\" class=\"inputstyle\"/>\r\n");
      out.write("\t\t\t\t\t<input id=\"jobidname\" name=\"jobidname\" class=\"inputselectstyle\" onclick=\"chooseJobTree('#jobid','#jobidname',selectNode.ename);\"/>\r\n");
      out.write("\t\t\t\t\t<div class=\"search-trigger\" onclick=\"chooseJobTree('#jobid','#jobidname',selectNode.ename);\"/>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<span>描述：</span>\r\n");
      out.write("\t\t\t\t\t<textarea id=\"postduty\" name=\"postduty\" rows=\"3\" cols=\"40\" class=\"{maxlength:500} areastyle\" ></textarea>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 导出窗口 -->\r\n");
      out.write("<div id=\"dialog_exp\" style=\"display:none;\" title=\"数据导出\" >\r\n");
      out.write("\t<table width=\"100%\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t  \t&nbsp;\r\n");
      out.write("\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t  \t&nbsp;\r\n");
      out.write("\t\t\t\t<label for=\"xls1\">\r\n");
      out.write("\t\t\t\t\t<input id=\"xls1\" type=\"radio\" name=\"xls\" value=\"0\" checked=\"true\" class=\"checkboxstyle\"/>导出本页\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t  \t&nbsp;\r\n");
      out.write("\t\t\t  \t&nbsp;\r\n");
      out.write("\t\t\t  \t<label for=\"xls2\">\r\n");
      out.write("\t\t\t  \t\t<input id=\"xls2\" type=\"radio\" name=\"xls\" value=\"1\" class=\"checkboxstyle\"/>全部导出\r\n");
      out.write("\t\t\t  \t</label>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
