package org.apache.jsp.pages.addresslist.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>通讯录管理</title>\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\"/>    \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/style.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"pages/addresslist/css/web.css\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"skins/css/jquery-ui-1.8.15.custom.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeStyle.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"plugin/tree/zTreeIcons.css\"/>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".ui-layout-pane {\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"pages/addresslist/css/web.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery.layout.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"skins/js/jquery-ui-1.8.5.custom.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"plugin/tree/jquery.ztree.all.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var searchContentWS=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.searchContentWS}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t//加载布局\r\n");
      out.write("\t$('body').layout({\r\n");
      out.write("        north: {size:\"72\",resizable:false,spacing_open:0,spacing_closed:0},\r\n");
      out.write("        south: {size:\"21\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t$('#myContent').layout({\r\n");
      out.write("        west: {size:\"230\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\t$('#myWest').layout({\r\n");
      out.write("        north: {size:\"31\",resizable:false,spacing_open:0,spacing_closed:0},\r\n");
      out.write("        south: {size:\"23\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t$('#myCenter').layout({\r\n");
      out.write("        north: {size:\"31\",resizable:false,spacing_open:0,spacing_closed:0}\r\n");
      out.write("    });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//树的展示\r\n");
      out.write("\tbuildDepartmentTree();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//展示数据\r\n");
      out.write("\tloadData();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//判断用户是否同步\r\n");
      out.write("\tvar userid='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\tif(userid==null||userid==''||userid=='null'){\r\n");
      out.write("\t\talert(\"登录用户信息不存在，请联系系统管理员！\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//树\r\n");
      out.write("var zTree;\r\n");
      out.write("//选中节点\r\n");
      out.write("var selectNode=null;\r\n");
      out.write("var url=\"pages/addresslist/web/phone.htm\";\r\n");
      out.write("function buildDepartmentTree(){\r\n");
      out.write("\t//配置\r\n");
      out.write("\tvar setting = {\r\n");
      out.write("\t\t\t\tcallback:{\r\n");
      out.write("\t\t\t\t\tbeforeClick: function(treeId, treeNode) {\r\n");
      out.write("\t\t\t\t\t\tselectNode=treeNode;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t//点击\r\n");
      out.write("\t\t\t\t\t\tif(selectNode!=null&&selectNode.id!=null){\r\n");
      out.write("\t\t\t\t\t\t\tvar hasurl=$(\"#detail\").attr(\"src\");\r\n");
      out.write("\t\t\t\t\t\t\tvar companycode=selectNode.companycode;\r\n");
      out.write("\t\t\t\t\t\t\tvar deptcode=selectNode.deptcode;\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar content = document.getElementById('detail');\r\n");
      out.write("\t\t\t\t\t\t\tif (content != null && content.contentWindow!=null&& content.contentWindow.reloadWebGrid != null)\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent.contentWindow.reloadWebGrid(companycode,deptcode,null);\r\n");
      out.write("\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\tcontent.contentWindow.location.href=encodeURI(\"address.do?page=list&companycode=\"+companycode+\"&deptcode=\"+deptcode);\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#detail\").attr(\"src\",url);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tview: {\r\n");
      out.write("\t\t\t\t\tfontCss: getDeptFontCss\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("    $.getJSON(\"webaddresslist/buildMyDepartmentTree.do\", function(tdata) {\r\n");
      out.write("    \tzTree = $.fn.zTree.init($(\"#tree\"),setting, tdata);\r\n");
      out.write("    \t\r\n");
      out.write("    \t//邦定定位事件\r\n");
      out.write("    \t$(\"#myMarker\").bind(\"keyup\",markTreeNode);\r\n");
      out.write("    \t$(\"#myMarker\").bind(\"blur\",markSelectTreeNode);\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//节点搜索定位\r\n");
      out.write("function markSelectTreeNode(){\r\n");
      out.write("\tvar value=\"\";\r\n");
      out.write("\tvalue = $.trim($(\"#myMarker\").val());\r\n");
      out.write("\tif (value != \"\"){\r\n");
      out.write("\t\tnodeList = zTree.getNodesByParamFuzzy(\"name\", value);\r\n");
      out.write("\t\tif(nodeList.length<=0)\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\tfor( var i=0, l=nodeList.length; i<l; i++) {\r\n");
      out.write("\t\t\tvar node=nodeList[i];\r\n");
      out.write("\t\t\tif(i==0){\r\n");
      out.write("\t\t\t\tzTree.selectNode(node);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//节点搜索变色\r\n");
      out.write("var nodeList = [];\r\n");
      out.write("var key;\r\n");
      out.write("var nodeState=false;\r\n");
      out.write("function markTreeNode(e) {\r\n");
      out.write("\tif(!nodeState){\r\n");
      out.write("\t\tnodeState=true;\r\n");
      out.write("\t\tvar value=\"\";\r\n");
      out.write("\t\tvalue = $.trim($(\"#myMarker\").val());\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tchangeNodesColor(false);\r\n");
      out.write("\t\tif (value === \"\"){\r\n");
      out.write("\t\t\tnodeState=false;\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tnodeList = zTree.getNodesByParamFuzzy(\"name\", value);\r\n");
      out.write("\t\tchangeNodesColor(true);\r\n");
      out.write("\t\tnodeState=false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function changeNodesColor(highlight) {\r\n");
      out.write("\tif(nodeList.length<=0)\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tfor( var i=0, l=nodeList.length; i<l; i++) {\r\n");
      out.write("\t\tvar node=nodeList[i];\r\n");
      out.write("\t\tnode.highlight = highlight;\r\n");
      out.write("\t\tzTree.updateNode(nodeList[i]);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function getDeptFontCss(treeId, treeNode) {\r\n");
      out.write("\treturn (!!treeNode.highlight) ? {color:\"#ff0000\", \"font-weight\":\"bold\"} : {color:\"#333\", \"font-weight\":\"normal\"};\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//全部关闭\r\n");
      out.write("var state=true;\r\n");
      out.write("function expandNode() {\r\n");
      out.write("\tstate=!state;\r\n");
      out.write("\tzTree.expandAll(state);\r\n");
      out.write("}\r\n");
      out.write("//===============\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("//定位部门\r\n");
      out.write("function makerTreePosation(treeid){\r\n");
      out.write("\tvar nodes = zTree.getNodesByParam(\"id\", treeid, null);\r\n");
      out.write("\tzTree.selectNode(nodes[0]);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("//从wasu搜索得到通讯录数据\r\n");
      out.write("function loadData(){\r\n");
      out.write("\tif(searchContentWS!=null&&searchContentWS!=\"\"&&searchContentWS!='null'){\r\n");
      out.write("\t\tsearch();\r\n");
      out.write("\t}\r\n");
      out.write("}\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("//员工搜索\r\n");
      out.write("function search(){\r\n");
      out.write("\tvar hasurl=$(\"#detail\").attr(\"src\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar companycode=\"\";\r\n");
      out.write("\tvar deptcode=\"\";\r\n");
      out.write("\t\r\n");
      out.write("\t/*if(selectNode!=null&&selectNode.id!=null){\r\n");
      out.write("\t\tcompanycode=selectNode.companycode;\r\n");
      out.write("\t\tdeptcode=selectNode.deptcode;\r\n");
      out.write("\t}*/\r\n");
      out.write("\tvar content = document.getElementById('detail');\r\n");
      out.write("\tvar name=$(\"#myname\").val();\r\n");
      out.write("\t\r\n");
      out.write("\tif (content != null && content.contentWindow!=null&& content.contentWindow.reloadWebGrid != null)\r\n");
      out.write("\t\tcontent.contentWindow.reloadWebGrid(companycode,deptcode,name);\r\n");
      out.write("\telse\r\n");
      out.write("\t\tcontent.contentWindow.location.href=encodeURI(\"address.do?page=list&companycode=\"+companycode+\"&deptcode=\"+deptcode+\"&name=\"+name);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//回车搜索\r\n");
      out.write("function formSubmit(e){\r\n");
      out.write("\tif(e.keyCode==13){\r\n");
      out.write("\t\tsearch();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//切换视图\r\n");
      out.write("function convertView(){\r\n");
      out.write("\t$(\"#detail\").attr(\"src\",url);\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"ui-layout-north top\">\r\n");
      out.write("\t<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"logo\">\r\n");
      out.write("        <tbody>\r\n");
      out.write("\t        <tr>\r\n");
      out.write("\t            <td align=\"right\">\r\n");
      out.write("\t                \r\n");
      out.write("\t            </td>\r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t    </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"ui-layout-center box\" id=\"myContent\" style=\"overflow:hidden;\">\r\n");
      out.write("\t<div class=\"ui-layout-west\" id=\"myWest\">\r\n");
      out.write("\t\t<div class=\"ui-layout-north left-top\">\r\n");
      out.write("\t\t\t<img width=\"16\" height=\"16\" src=\"pages/addresslist/css/images/inco-shu.gif\">\r\n");
      out.write("\t\t\t<span class=\"font-01\">公司/部门</span>\r\n");
      out.write("\t\t\t<a href=\"javascript:expandNode();\" style=\"margin-left:110px;\">折叠</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"ui-layout-center\" style=\"background:#fff;overflow-x:hidden;overflow-y:scroll;border:1px solid #888;border-top:0px;\">\r\n");
      out.write("\t\t\t<ul id=\"tree\" class=\"ztree\">\r\n");
      out.write("\t\t\t\t<img src=\"skins/images/ajax-loader-small.gif\"/>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"ui-layout-south\">\r\n");
      out.write("\t\t\t <table width=\"100%\" height=\"100%\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"myMarker\" id=\"myMarker\" style=\"width:206px;border:1px solid #888888;\"/>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"ui-layout-center\" id=\"myCenter\" style=\"padding-left:5px;\">\r\n");
      out.write("\t\t<div class=\"ui-layout-north\">\r\n");
      out.write("\t\t\t<table width=\"100%\" height=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" >\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:25px;\">\r\n");
      out.write("\t\t                <img width=\"24\" height=\"23\" src=\"pages/addresslist/css/images/inco-pp.gif\">\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t\t            <td style=\"width:420px;\">\r\n");
      out.write("\t\t                <input class=\"input\" id=\"myname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.searchContentWS}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" style=\"width:415px;\" onkeypress=\"formSubmit(event);\">\r\n");
      out.write("\t\t            </td>\r\n");
      out.write("\t                <td style=\"width:65px;\" align=\"right\">\r\n");
      out.write("\t                    <a href=\"javascript:search();\" >\r\n");
      out.write("\t                        <img width=\"62\" height=\"23\" border=\"0\" src=\"pages/addresslist/css/images/b-suosou.gif\">\r\n");
      out.write("\t                    </a>\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t                <td align=\"right\">\r\n");
      out.write("\t                    <a target=\"detail\" href=\"address.do?page=selfedit\">\r\n");
      out.write("\t                        <img width=\"120\" height=\"23\" border=\"0\" src=\"pages/addresslist/css/images/p-modify.gif\">\r\n");
      out.write("\t                    </a>\r\n");
      out.write("\t                </td>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"ui-layout-center\" style=\"background:#ffffff;overflow:hidden;\">\r\n");
      out.write("\t\t\t<iframe id=\"detail\" name=\"detail\" width=\"100%\" height=\"100%\" src=\"pages/addresslist/web/phone.htm\" frameborder=\"0\" scrolling=\"no\"></iframe>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\t\t\r\n");
      out.write("<div class=\"ui-layout-south\">\r\n");
      out.write("\t<table width=\"100%\" height=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"bottom-bg\">\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t    <td width=\"\">&nbsp;</td>\r\n");
      out.write("\t\t\t    <td width=\"200\" valign=\"bottom\" background=\"pages/addresslist/css/images/bottom-pic.gif\" align=\"right\" style=\"background-repeat:no-repeat; background-position:right;font-size:12px;\" class=\"yejiao\">\r\n");
      out.write("\t\t\t    \t版权所有 &copy; 2009- 2014 华数\r\n");
      out.write("\t\t        </td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
